### ISSUE TITLE
显示捐助者徽章

### ISSUE THREAD

**Issue by MewX** [pt-plugins/PT-Plugin-Plus#1003]
## 您的功能请求是否与问题有关？ 请描述一下。
在site列表/timeline显示捐助标志 😊

## 描述你想要的解决方案
显示 💖 或者⭐在账号名称附近（不需要隐藏）

## 描述您考虑过的替代方案
n/a

## 其他附加信息
n/a 毕竟大部分捐助的站点都有标记

**Comment by ted423** [comment]
emmm

**Comment by MewX** [comment]
反正就是个建议，说来直接使用站点图标也行 🤣

比如AB的是团子大家族的团子： ![AB](https://animebytes.tv/static/common/symbols/donor.png)

**Comment by IITII** [comment]
> 反正就是个建议，说来直接使用站点图标也行 🤣
> 
> 比如AB的是团子大家族的团子： ![AB](https://camo.githubusercontent.com/3f85559291860507c6b30092573149f0493adcb58c382a3706746a7e1f042b9e/68747470733a2f2f616e696d6562797465732e74762f7374617469632f636f6d6d6f6e2f73796d626f6c732f646f6e6f722e706e67)

可以简单理解为黄星用户吗?

**Comment by IITII** [comment]
说起来那些站有黄星? hdhome, chd? 还有? @MewX 站不多的话, 就没必要弄了. 

~~VIP 目前有单独标记, 都黄星了,要不直接 VIP 吧~~
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1555#issuecomment-1703806460
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/ab5c8edd-b4a0-48ef-ba0d-0d413b5f8256)

**Comment by MewX** [comment]
> 说起来那些站有黄星? hdhome, chd, pter 还有? @MewX 站不多的话, 就没必要弄了. 
> 
> ~~VIP 目前有单独标记, 都黄星了,要不直接 VIP 吧~~
> https://github.com/pt-plugins/PT-Plugin-Plus/pull/1555#issuecomment-1703806460
> ![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/ab5c8edd-b4a0-48ef-ba0d-0d413b5f8256)
> 

哦可能我说的不是VIP？我的意思是捐赠用户，所有站都有的吧，就类似于gazelle站点的❤️？

**Comment by IITII** [comment]
内站见的比较多的捐赠方式就是 黄星和 VIP, gazelle站点没怎么见过

**Comment by IITII** [comment]
1. 已知黄星站点不多/并非所有站都有黄星(捐赠)图标
2. 该信息应该存放于 UserInfo 中, 需从 config.json 开始修改, 有一定工作量且可能还需单独适配特定站点.
3. ~~无号~~
4. 欢迎 PR
