### ISSUE TITLE
pttime 适配相关问题 9kg 简体中文

### ISSUE THREAD

**Issue by qitayun** [pt-plugins/PT-Plugin-Plus#1038]
- PT 助手版本:最新版
- PT 助手安装方式：（市场安装，或zip包安装）zip安装
- 浏览器名称及版本：谷歌浏览器
- 浏览器是否安装了其他插件：嗯
- 停用其他插件后是否正常工作：不行
- 问题描述：pttime 新增了9kg区  但获取第一页种子中并不能获取到9kg分区的内容

- 相关截图：![image.png](https://pic.rmb.bdstatic.com/bjh/e9c7f97aa796b5b034a453b2888aa55c.png)
![image.png](https://pic.rmb.bdstatic.com/bjh/c40c73cbe8955828c6fb2005cddd7581.png)

- 重现步骤：直接点击获取获取第一页种子获取不到9kg区的内容

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/1047

**Comment by ted423** [comment]
集中到一个issue
https://github.com/ronggang/PT-Plugin-Plus/issues/966

**Comment by txuw** [comment]
稍作修改即可
修改地址如下:
/adults.php?search=$key$
/torrents.php?search=$key$
![%AF@ELA}C }IC{OFVUB(GK1](https://user-images.githubusercontent.com/52928346/176762905-7e644853-785f-489f-ab0d-f8b0281d8d6d.png)
![1F)O_ S8T{2C)6BTYGIH{~C](https://user-images.githubusercontent.com/52928346/176762919-3341ee0d-aa6b-42ef-a13b-4d8a33859ec0.png)
![3OY(` 9$%T`D$M9M@S{SD(P](https://user-images.githubusercontent.com/52928346/176762939-dc77db4e-81f5-4935-b666-6af993cd9862.png)
