### ISSUE TITLE
扩展发送到下载器下载重试过多

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#1046]
目前扩展是只要失败就会不断的尝试，用户名密码错误，存在重复任务，甚至无效的种子文件也会多次尝试发送
用户名密码错误的时候会直接导致客户端将当前IP加入黑名单。
存在重复任务的情况TR不会多次发送，而QB因为 https://github.com/ronggang/PT-Plugin-Plus/issues/386 相关问题也会多次发送
但个人认为在QB有返回False的情况下不应该多次发送

无效的种子本身扩展会检测的情况下 https://github.com/ronggang/PT-Plugin-Plus/blob/f2e4f20c47eca1ac65766be79f6cae988621547e/src/background/controller.ts#L908 不需要多次重试

**Comment by Rhilip** [comment]
关于用户密码错误这个问题，我不认为应该在发送种子的时候来处理。
在添加客户端时，我们已要求用户进行可连接性验证，确保身份信息正确。

**Comment by ted423** [comment]
> 关于用户密码错误这个问题，我不认为应该在发送种子的时候来处理。 在添加客户端时，我们已要求用户进行可连接性验证，确保身份信息正确。

我指的
![image](https://user-images.githubusercontent.com/7042766/164426583-9dfd6892-3f16-484d-8eb3-954e6079d213.png)

**Comment by ted423** [comment]
目前还没研究客户端密码错误返回信息如何，主要情形是改了客户端密码，忘了ptpp里设置

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/164735482-357eab52-a8b3-498c-8d2e-6483ca51e523.png)
https://github.com/ronggang/PT-Plugin-Plus/issues/912
突然想到这个问题，这个是不是也能检测一下下载的是不是真的种子

**Comment by ted423** [comment]
或者扩展的下载种子可以直接丢给浏览器下载。
这样也可以避免这个问题
https://github.com/ronggang/PT-Plugin-Plus/issues/555

**Comment by pxwang85** [comment]
个人建议，这方面更好的解决办法是
下载器对PTPP浏览器的IP地址 增加白名单，如果白名单就可以忽视密码错误问题

**Comment by ted423** [comment]
> 个人建议，这方面还一个解决办法是 下载器对PTPP浏览器的IP地址 增加白名单，如果白名单就可以忽视密码错误问题

这不能解决根本问题，ptpp的逻辑是重试一次就下一次种子。对于有短时间下载种子限制的站是灾难性的。

**Comment by ted423** [comment]
test

**Comment by IITII** [comment]
#1573  改完, 在测试的时候倒是没复现...
