### ISSUE TITLE
dateTime 不支持带中文的日期(例如其他语言如俄罗斯站的也无法解析)

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#1068]
## 您的功能请求是否与问题有关？ 请描述一下。

如Speedapp.io 的入站时间为
2022年5月9日 上午9:43:54
目前仅在英文下可以解析

## 描述你想要的解决方案

https://blog.csdn.net/qq_39401400/article/details/78835810

或者有没有在维护的多语言识别转换解析的现成方案

**Comment by fzlins** [comment]
感觉用一些第三方的lib会比较方便。比如momentjs(https://momentjs.com/) ，Datejs(https://github.com/datejs/Datejs)

**Comment by fzlins** [comment]
> ## 您的功能请求是否与问题有关？ 请描述一下。
> 如Speedapp.io 的入站时间为 2022年5月9日 上午9:43:54 目前仅在英文下可以解析
> 
> ## 描述你想要的解决方案
> https://blog.csdn.net/qq_39401400/article/details/78835810
> 
> 或者有没有在维护的多语言识别转换解析的现成方案
> 
> ## 描述您考虑过的替代方案
> ## 其他附加信息

项目已经有dayjs了，我没有其它语言时间的站，你可以试试看这样改行吗？

ref: https://day.js.org/docs/zh-CN/parse/string-format

infoParser.ts: import 'dayjs/locale/zh-cn'

config.json: "filters": ["query.text()", "dateTime(query).isValid() ? dateTime(query).valueOf() : dateTime(query, 'YYYY年M月D AH:mm:ss', 'zh-cn').valueOf()"]

**Comment by ted423** [comment]
https://metacpan.org/dist/DateTime-Locale/view/lib/DateTime/Locale/ru_RU.pod#Wide-(format)1

**Comment by ted423** [comment]
被上午下午打败了
![image](https://user-images.githubusercontent.com/7042766/197993980-0592c5f8-71ad-438c-801d-366515523f03.png)

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/197994191-d4ceb42e-5c50-4a82-a537-b8622b8c5f1a.png)

**Comment by ted423** [comment]
感觉只支持输出上午下午，并不支持反过来

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/197996232-8417943b-ce71-4dca-a95d-fb5b0b1b622f.png)
emmm

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/197996412-303937df-4082-479a-b824-2f03620b9cb7.png)

**Comment by IITII** [comment]
## 测试结论
* 无法识别 `上午`, `下午`, 即使是指定了 locale
* 这种是缺少加载对应的库, `dayjs('2022年5月9日 下午9:43:54', 'YYYY年M月D Ah:mm:ss', 'zh-cn'`
* 可以尝试自定义 locale 实现 上午下午的解析, ~~不过没有必要~~
* https://day.js.org/docs/en/customization/customization
* https://juejin.cn/post/7188855653845172261
## 测试代码

https://github.com/pt-plugins/PT-Plugin-Plus/blob/e15d28602ca72add7681da2f6b3a518838dbe1c9/src/background/infoParser.ts#L109-L112

```js
const dayjs = require('dayjs')
const customParseFormat = require('dayjs/plugin/customParseFormat')
const advancedFormat = require('dayjs/plugin/advancedFormat')
require('dayjs/locale/zh-cn')
dayjs.extend(customParseFormat);
dayjs.extend(advancedFormat);


console.log(dayjs('2022年5月9日 上午9:43:54', 'YYYY年M月D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 下午9:43:54', 'YYYY年M月D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022-5-9 AM9:43:54', 'YYYY-M-D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022-5-9 PM9:43:54', 'YYYY-M-D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 AM9:43:54', 'YYYY年M月D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 PM9:43:54', 'YYYY年M月D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 PM9:43:54', 'YYYY年M月D Ah:mm:ss', 'zh-cn').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 上午9:43:54', 'YYYY年M月D Ah:mm:ss', 'zh-cn').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 下午9:43:54', 'YYYY年M月D Ah:mm:ss', 'zh-cn').format('YYYY-MM-DD HH:mm:ss'))
console.log(dayjs('2022年5月9日 下午9:43:54', 'YYYY年M月D Ah:mm:ss').format('YYYY-MM-DD HH:mm:ss'))
```

## 结果
```
2022-05-09 09:43:54
2022-05-09 09:43:54
2022-05-09 09:43:54
2022-05-09 21:43:54
2022-05-09 09:43:54
2022-05-09 09:43:54
2022-05-09 09:43:54
2022-05-09 09:43:54
2022-05-09 09:43:54
2022-05-09 09:43:54
```
