### ISSUE TITLE
使用Manifest V3

### ISSUE THREAD

**Issue by XCwosjw** [pt-plugins/PT-Plugin-Plus#1073]
## 您的功能请求是否与问题有关？ 请描述一下。

Chrome将在2023 年 1 月停止Manifest V2的支持，届时所有基于Manifest V2的扩展程序将无法在Chrome上运行

## 描述你想要的解决方案

由Manifest V2转向Manifest V3

## 描述您考虑过的替代方案

https://developer.chrome.com/blog/mv2-transition/

**Comment by vivodi** [comment]
主要维护者目前的意向是只对v1进行bug修复。大的改动好像都要等v2。目前用的Vuetify v1也已经不受支持了。

**Comment by ted423** [comment]
之前讨论过了，Manifest V3移除了DOM相关的东西会导致扩展无法使用

**Comment by Rhilip** [comment]
在此issue https://github.com/w3c/webextensions/issues/72 中有关`HTML/XML parsing` , `Clipboard access`, `WebSockets` 的问题解决前，都不会考虑 MV3

**Comment by ted423** [comment]
https://ourl.co/96352
