### ISSUE TITLE
MT柱状图变负

### ISSUE THREAD

**Issue by sappleNN** [pt-plugins/PT-Plugin-Plus#1078]
- PT 助手版本:1.52 edge商店版  Actions最新版（2个版本都试过）
- PT 助手安装方式：edge市场安装 和 ZIP安装（市场安装，或zip包安装）
- 浏览器名称及版本：EDGE 版103.0.1264.37
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：
情况出现就是 我设置的每晚23点55刷新  结果昨天27号MT刷新失败 其他站成功 然后27号早起看到 单点了MT刷新（其实这步错了，应该全站刷新可能就不会出这个问题，我一直都是全站刷新，唯独这次手欠。。）结果就MT就负了   数据里记录的是26号（延迟一天） 然后今天的数据显示为27号 所以怎么刷新都没用应该（猜测）  可能的解决办法（个人猜测）：等0点第二天后刷新，或者删除lastest数据统计（可惜不能删除）

- 相关截图：
![QQ截图20220628180027](https://user-images.githubusercontent.com/56980316/176152133-9645dc7f-3431-4ffb-b9fa-9eb8aaf79835.png)

- 重现步骤：之前U2万圣节问题也引发了一次复数显示，那次是隔天第二天刷新后解决。猜测重现步骤就是每天定时自动刷新后的失败站点，等第二天发现后直接单点此站就可能触发此问题，而全站刷新就没事。

-中间切换了Actions最新版，对MT数据统计进行单独条目删除，删除后重新刷新（不管是单刷MT还是全站刷新），均无法解决（删除的条目重新刷新后依旧出现），怀疑出错的是lestest条目但是不能删除。 PS：红圈处都是有正常数据的，但是由于负数柱状图给压缩的非常小，鼠标放上可以看到数据。

**Comment by ted423** [comment]
目前感觉刷新失败会写入一条空白数据的思路不太对，应该不计入数据

**Comment by befantasy** [comment]
> [#537 (comment)](https://github.com/ronggang/PT-Plugin-Plus/issues/537#issue-631312994) 通过此条目1楼命令行 成功删除了27号的数据统计（通过插件内删除无效），然后插件列表里关闭PTPP开启PTPP重新刷新数据解决了

遇到了同样问题。请问这个命令在哪里输入。。。
