### ISSUE TITLE
群晖7.1.1 Synology Download Station下载报错

### ISSUE THREAD

**Issue by 261032568** [pt-plugins/PT-Plugin-Plus#1139]
- PT 助手版本:v1.5.2.99ab2de zip
- PT 助手安装方式：zip（市场安装，或zip包安装）
- 浏览器名称及版本：Microsoft Edge
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
background | service.controller.doDownload.error | 2022-10-14 11:35:14 | 下载服务器Synology Download Station处理[addTorrentFromURL]命令失败！
-- | -- | -- | -- | --
{"error":{"code":119},"success":false}

DSM系统版本是7.1.1，下载服务器连接正常，下载是报错，7.1升级到7.1.1后才出现这个问题

- 相关截图：
<img width="1352" alt="截屏2022-10-14 11 44 35" src="https://user-images.githubusercontent.com/74848048/195757729-a55755e2-97bc-4c21-b872-218b47008887.png">

**Comment by ted423** [comment]
在这里讨论吧

**Comment by 261032568** [comment]
你好


﹏゛Style^浅墨ぃ&nbsp;。
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ronggang/PT-Plugin-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 下午3:07
***@***.***&gt;;
抄送:&nbsp;"﹏゛Style^浅墨ぃ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ronggang/PT-Plugin-Plus] 群晖7.1.1 Synology Download Station下载报错 (Issue #1139)





 
在这里讨论吧

**Comment by ted423** [comment]
请去我提供的那个issue里讨论，再已有issue open的情况下，不要新开issue,
一个主题讨论才能确保有效的讨论

**Comment by Rhilip** [comment]
> 在这里讨论吧 #687

@ted423 我觉得还是在这个issue中讨论好些， DSM 7.0 的升级已经在 #687 中解决。目前的问题是 7.1 升级到 7.1.1 之后的兼容性被破坏了。

**Comment by tyejuan** [comment]
> 

是这样的，现在只差这个DSM7.1.1没法解决了。我准备降级到7.1试一下

**Comment by ted423** [comment]
我看我这边的请求都是
http://nas:5000/webapi/entry.cgi

**Comment by ted423** [comment]
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/Calendar/2.4/enu/Synology_Calendar_API_Guide_enu.pdf

我发现我这边的请求有 X-SYNO-HASH 和 X-SYNO-TOKEN
然后搜到了这个文档

**Comment by ted423** [comment]
https://github.com/thomasfady/Synology_SA_20_25

**Comment by ted423** [comment]
POST /webapi/entry.cgi?api=SYNO.API.Auth HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5
Connection: keep-alive
Content-Length: 196
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: _SSID=？？？
DNT: 1
Host: nas.?:5000
Origin: http://nas.?:5000
Referer: http://nas.?:5000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

这个请求里会有个 
```
{"data":{"kk_message":"???","synotoken":"??"},"success":true}
```

**Comment by ted423** [comment]
GET /webapi/entry.cgi?api=SYNO.API.Auth&version=6&method=token&_dc=???&SynoToken=???
HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5
Connection: keep-alive
Cookie: _SSID=???
DNT: 1
Host: nas.?:5000
Referer: http://nas.?:5000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
X-SYNO-HASH: ?
X-SYNO-TOKEN: ???

**Comment by Mmx88** [comment]
原来没解决，试了好久找不到问题。。。

**Comment by sdjnmxd** [comment]
关联PR：https://github.com/pt-plugins/PT-Plugin-Plus/pull/1340
已经合并至dev

**Comment by 261032568** [comment]
> 关联PR：#1340 已经合并至dev
现在可以正常使用了，非常感谢！

**Comment by tyejuan** [comment]
> > 关联PR：#1340 已经合并至dev
> > 现在可以正常使用了，非常感谢！

我按说明修改了代码，修改了以下三个位置，还是不能添加种子。请问能指点一下吗？
******** * 获取 SID
     */
    getSessionId() {
      return new Promise((resolve, reject) => {
        let url = `${this.options.address}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=${encodeURIComponent(this.options.loginName)}&passwd=${encodeURIComponent(this.options.loginPwd)}&session=DownloadStation&format=sid_&enable_syno_token=yes_`;*********
   
*******_sid: this.sessionId  // fxxk， _sid 参数不能放在第一位，不然会直接 101 报错
      }

     let headers = {
      'X-SYNO-T0KEN': this.synoToken
     }

      // fxxk， 没有 destination 参数也会直接报错
      let savePath = (options.savePath || "") + "";*********

******* addTorrent(formData, options, callback) {
      $.ajax({
        url: `${this.options.address}/webapi/entry.cgi`,
        headers,
        timeout: PTBackgroundService.options.connectClientTimeout,********

**Comment by sdjnmxd** [comment]
> > > 关联PR：#1340 已经合并至dev
> > > 现在可以正常使用了，非常感谢！
> 
> 我按说明修改了代码，修改了以下三个位置，还是不能添加种子。请问能指点一下吗？ ******** * 获取 SID _/ getSessionId() { return new Promise((resolve, reject) => { let url = `${this.options.address}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=${encodeURIComponent(this.options.loginName)}&passwd=${encodeURIComponent(this.options.loginPwd)}&session=DownloadStation&format=sid_&enable_syno_token=yes_`;_********
> 
> *******_sid: this.sessionId // fxxk， _sid 参数不能放在第一位，不然会直接 101 报错 }
> 
> ```
>  let headers = {
>   'X-SYNO-T0KEN': this.synoToken
>  }
> 
>   // fxxk， 没有 destination 参数也会直接报错
>   let savePath = (options.savePath || "") + "";*********
> ```
> 
> ******* addTorrent(formData, options, callback) { $.ajax({ url: `${this.options.address}/webapi/entry.cgi`, headers, timeout: PTBackgroundService.options.connectClientTimeout,********

为什么不直接基于dev分支构建扩展？
此外修改不止三处，详情请看[diff](https://github.com/pt-plugins/PT-Plugin-Plus/pull/1340/files)

**Comment by 261032568** [comment]
> > > 关联PR：#1340 已经合并至dev
> > > 现在可以正常使用了，非常感谢！
> 
> 我按说明修改了代码，修改了以下三个位置，还是不能添加种子。请问能指点一下吗？ ******** * 获取 SID _/ getSessionId() { return new Promise((resolve, reject) => { let url = `${this.options.address}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=${encodeURIComponent(this.options.loginName)}&passwd=${encodeURIComponent(this.options.loginPwd)}&session=DownloadStation&format=sid_&enable_syno_token=yes_`;_********
> 
> *******_sid: this.sessionId // fxxk， _sid 参数不能放在第一位，不然会直接 101 报错 }
> 
> ```
>  let headers = {
>   'X-SYNO-T0KEN': this.synoToken
>  }
> 
>   // fxxk， 没有 destination 参数也会直接报错
>   let savePath = (options.savePath || "") + "";*********
> ```
> 
> ******* addTorrent(formData, options, callback) { $.ajax({ url: `${this.options.address}/webapi/entry.cgi`, headers, timeout: PTBackgroundService.options.connectClientTimeout,********

需要先清除一下浏览器缓冲，重新载入插件，登陆你的DSM服务器后，再去下载

**Comment by tyejuan** [comment]
> @tyejuan 参考[文档](https://github.com/pt-plugins/PT-Plugin-Plus/wiki/get-from-gh-actions)直接使用构建好的吧 没必要自己再对着代码改一遍了

我没找到dev频道的链接，麻烦能发一下吗

**Comment by sdjnmxd** [comment]
> > @tyejuan 参考[文档](https://github.com/pt-plugins/PT-Plugin-Plus/wiki/get-from-gh-actions)直接使用构建好的吧 没必要自己再对着代码改一遍了
> 
> 我没找到dev频道的链接，麻烦能发一下吗

这是最新dev分支构建结果：https://github.com/pt-plugins/PT-Plugin-Plus/actions/runs/4164203901
从下面的Artifacts出下载crx或是zip，然后根据文档更新即可

**Comment by tyejuan** [comment]
> > > @tyejuan 参考[文档](https://github.com/pt-plugins/PT-Plugin-Plus/wiki/get-from-gh-actions)直接使用构建好的吧 没必要自己再对着代码改一遍了
> > 
> > 
> > 我没找到dev频道的链接，麻烦能发一下吗
> 
> 这是最新dev分支构建结果：https://github.com/pt-plugins/PT-Plugin-Plus/actions/runs/4164203901 从下面的Artifacts处下载crx或是zip，然后根据文档更新即可

已能用，非常感谢！Mac版的edge加载扩展也搞定能用。
