### ISSUE TITLE
[Freature Request] 搜索界面多选种子进行操作后自动清除选择

### ISSUE THREAD

**Issue by leoleoasd** [pt-plugins/PT-Plugin-Plus#1149]
## 您的功能请求是否与问题有关？ 请描述一下。

搜索界面多选种子进行操作后可以自动清除选择，如选择生成辅种任务后

这样如果同一个搜索界面想多次辅种，不需要取消选择原先的东西。
## 描述你想要的解决方案

搜索界面批量操作后自动取消选择

## 描述您考虑过的替代方案

无
## 其他附加信息

无

**Comment by ted423** [comment]
没太懂，完全相同的任务多次辅种？

**Comment by leoleoasd** [comment]
比如搜索电视剧名字，搜到的结果里有好几季，如果这样改之后，我选中第一季的种子、创建任务后，不需要取消选择第一季，可以直接选第二季进行辅种

**Comment by leoleoasd** [comment]
有什么使用场景需要选中同样的种子，操作两次吗？没有的话似乎自动取消选择就挺合理的？🤔

**Comment by ted423** [comment]
想了一下，感觉这样的应用场景非常少，反而这么实行之后可能会造成问题，理论第一季一个辅种任务，第二季另一个辅种任务是可以的。没必要都丢到一个辅种任务里

**Comment by leoleoasd** [comment]
我的意思就是分开成两个辅种任务。如果能自动取消选择，在创建第一个辅种任务之后就不需要取消选择第一季的内容（会自动取消），直接选中第二季的创建第二个辅种任务就行

**Comment by fzlins** [comment]
点一下左上拿个➖号（全选）就能全部取消了。

**Comment by ted423** [comment]
好像是描述以及理解上的一些问题。我等下看看
