### ISSUE TITLE
侧边栏受浏览器翻译影响

### ISSUE THREAD

**Issue by luckiestone** [pt-plugins/PT-Plugin-Plus#1157]
- PT 助手版本: any
- PT 助手安装方式：crx
- 浏览器名称及版本：Edge
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
PTPP侧边栏受浏览器翻译影响可能会导致显示不正常，尝试使用油猴脚本并不起作用，建议能够直接对侧边栏的`div.pt-plugin-body`添加属性`translate = no`，该属性会禁用浏览器翻译本元素。

**Comment by ted423** [comment]
开着吧，有空改下好了
