### ISSUE TITLE
AB 无法获取状态信息

### ISSUE THREAD

**Issue by MewX** [pt-plugins/PT-Plugin-Plus#1176]
- PT 助手版本: v1.5.2.d1e8200
- PT 助手安装方式：zip
- 浏览器名称及版本：107.0.5304.107
- 浏览器是否安装了其他插件：n/a
- 停用其他插件后是否正常工作：n/a
- 问题描述：点击刷新按钮

```
error {type: 'error', msg: '[{site.name}]Network request failed! (404 , error)', success: false}
  msg: "[{site.name}]Network request failed! (404 , error)"
  success: false
  type: "error"
```

- 相关截图：
<img width="791" alt="image" src="https://user-images.githubusercontent.com/5752560/202874755-75cee51f-3da5-4fa3-a024-cd6cd20a0fe7.png">

- 重现步骤：点击刷新按钮

**Comment by ted423** [comment]
不知道是否跟这个有关
https://github.com/ronggang/PT-Plugin-Plus/issues/1161

**Comment by ted423** [comment]
域名没改的话，index.php访问改了？
