### ISSUE TITLE
hdatmos12月的站点升级后无法读取做种体积

### ISSUE THREAD

**Issue by ChrnoChou** [pt-plugins/PT-Plugin-Plus#1190]
- PT 助手版本:  v1.5.2.36a7892
- PT 助手安装方式：crx
- 浏览器名称及版本：Chromium 102.0.5005.167

- 问题描述：hdatmos.club在12月进行了系统升级,升级后做种体积显示为0,其他正常

- 相关截图：
![微信截图_20221208011358](https://user-images.githubusercontent.com/100701833/206245904-91081b1f-f29a-4cff-a374-ffd54c51c83c.png)

**Comment by fzlins** [comment]
已修复
