### ISSUE TITLE
BYRBT等站点在搜索界面不显示做种状态

### ISSUE THREAD

**Issue by LoneFireBlossom** [pt-plugins/PT-Plugin-Plus#1194]
- PT 助手版本: 栽培者 2022, 版本 v1.5.2.c81e4e7 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：版本 108.0.5359.98（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：依旧有下面的问题
- 问题描述：

有些站点的种子我有在做种，但是在PTPP里搜索出来的展示结果是没有做种。
我手头有的站点里，CHD和BYRBT, FileList,IPT,（等）有这种问题。
如下图所示，CHD是把做种的种子也显示为“已完成下载”，其它站是不显示做种状态。

- 相关截图：

<img width="989" alt="image" src="https://user-images.githubusercontent.com/50087596/206663661-432b1121-377d-4ac7-b3bb-350dba7a17a3.png">

- 重现步骤：

在PTPP里搜索

- 个人想法：

我辅种的方法是在PTPP里搜索，下载种子，而不是用iyuu等方式，因为第一，iyuu等自动化辅种终究不能覆盖所有情况，会有漏掉的种子；第二，每一段时间用PTPP搜索辅种就相当于能顺带进行一次可能的洗版。
所以PTPP是否能显示出一个站的种子的做种状态对我个人来说需求比较强，看到有做种的小绿条我就不用专门去点一下下载按钮以及后续加入qBittorrent了。

有些架构不是很通用的站点（如IPT等）是否能显示做种状态感觉在其次，我是想岛，BYRBT这俩站点能不能修一下呢，不知道是站点不支持还是PTPP的bug。
想来最直接粗暴的方法就是对这类站点，在读取站点个人信息的时候记录下所有做种种子的链接，在PTPP里搜索展示时做比对就好了，不过感觉实现起来可能会有点儿麻烦

**Comment by ted423** [comment]
byr没号
chd这块是我配的，页面只能判断出是100%，无法判断是否在做种。故目前只能如此。
剩下的站点需要具体问题具体分析。只有站点搜索列表页能判断出来，ptpp才有可能去显示
