### ISSUE TITLE
关于升级要求时魔等新特性的一些建议

### ISSUE THREAD

**Issue by luckiestone** [pt-plugins/PT-Plugin-Plus#1198]
还是正式提个issue吧。
近期的一些dev的PR合并引入了一些新的功能，包括但不限于：用户名下方显示id、新增时魔列、等级列显示升级要求、魔力值/积分列支持的站点分行显示魔力和做种积分等等。
当然，对于很多关注站点升级、求邀请或者一些关注数据的朋友们来说很实用。但是，对于另一些用户，比如本人，需要另一个选择。
本人不关注站点升级，不关注积分高低，也不需要求邀请，同时拥有站点数比较多再加上稍许强迫症。因此在当前状态下，站点数据页对来我说完全不能接受。主要表现为：
1. 设计风格不统一，主要为过滤列选项；
2. 用户名下方显示id，使得页面凌乱，而且个别站点不支持，视觉上列元素不统一。更新：已更新为悬停显示，这个实现得比较优雅；
3. 时魔列（当前可隐藏）相当部分的站点并不支持，页面大量空白；
4. 升级要求，魔力及做种积分双行显示（当前两者均可隐藏）同样相当部分站点不支持，列显示不统一。

是否可能的解决方案：
a) 更改当前主页显示架构的feature另开分支，dev主要致力于当前的修补，next将承担全新版本的重任；
b) 所有的更改都应该可以隐藏，给不需要的用户一个选择权。过滤列选项按钮等最好和页面风格统一，或者做到设置菜单内。

主要涉及的PR（如有遗漏麻烦补充）：
https://github.com/ronggang/PT-Plugin-Plus/pull/1197 https://github.com/ronggang/PT-Plugin-Plus/pull/1191 https://github.com/ronggang/PT-Plugin-Plus/pull/1187 https://github.com/ronggang/PT-Plugin-Plus/pull/1185 https://github.com/ronggang/PT-Plugin-Plus/pull/1184 https://github.com/ronggang/PT-Plugin-Plus/pull/1183 https://github.com/ronggang/PT-Plugin-Plus/pull/1182 https://github.com/ronggang/PT-Plugin-Plus/pull/1181

**Comment by starsjf** [comment]
刚被自动更新到1.60之后，红色的等级升级提醒有点吓人，我还以为账号出了问题。建议再等级下方的提示不要用大红色字体来显示，普通黑色即可，或者用绿色蓝色都比大红色警示要好。我认为一般账号有问题或者消息才应该大红色字体提醒。

**Comment by starsjf** [comment]
> 刚被自动更新到1.60之后，红色的等级升级提醒有点吓人，我还以为账号出了问题。建议再等级下方的提示不要用大红色字体来显示，普通黑色即可，或者用绿色蓝色都比大红色警示要好。我认为一般账号有问题或者消息才应该大红色字体提醒。

这个功能还是挺不错的，就是这个红色不好接受。

**Comment by 254327902** [comment]
> 

大佬你好，试了新版几个DEV和1.6   只有MT不显示时魔 其他保种站点都没问题
