### ISSUE TITLE
v1.6.0在選單添加的ACM會導致 '我的數據' 無法顯示

### ISSUE THREAD

**Issue by 010203le** [pt-plugins/PT-Plugin-Plus#1211]
- PT 助手版本:v1.6.0.ba3d87e zip
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome 108.0.5359.99
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
v1.6.0使用選單添加acm後會導致 我的數據 頁面無法顯示

- 相关截图：
詳見重現步驟

- 重现步骤：
step 1 添加站點
![image7e8265d5587309f9.png](https://s3.pterclub.com/images/2022/12/12/image7e8265d5587309f9.png)
step 2 回到 '我的數據'  頁面會發現按鈕不工作
![image94e91d558f8b8a25.png](https://s3.pterclub.com/images/2022/12/12/image94e91d558f8b8a25.png)
step 3 重新整理後，頁面變空白
[![image85f0dd8ffdb76db5.png](https://s3.pterclub.com/images/2022/12/12/image85f0dd8ffdb76db5.png)](https://s3.pterclub.com/image/zzsiYZ)

刪除acm後一切恢復正常(選單添加的hdsky、GPW也有此問題

已知手動添加的不會觸發此問題(如圖添加方法
![imagea83a330e357997ac.png](https://s3.pterclub.com/images/2022/12/12/imagea83a330e357997ac.png)

**Comment by ted423** [comment]
NP站似乎也炸了

**Comment by ted423** [comment]
应该是默认会去判断下一级的条件，但是默认新加入站点是没有当前等级，导致了问题。
目前没有升级条件的站可以正常添加

**Comment by ted423** [comment]
临时解决方案 ，关掉 等级要求
![image](https://user-images.githubusercontent.com/7042766/206983503-a5228841-3a7d-423e-a946-189e30d6f0de.png)

**Comment by ted423** [comment]
这种情况下是否需要release一版@ronggang @Rhilip

**Comment by Rhilip** [comment]
> 这种情况下是否需要release一版@ronggang @Rhilip

鉴于近期新功能增加和管理变更的一些变动，建议缓几天。

**Comment by ted423** [comment]
现状是似乎不显示可以进行刷新，然后就显示了。
不过万一遇到站点未登录或者刷不出数据不知道会怎么样
