### ISSUE TITLE
天空站点无法读取个人信息

### ISSUE THREAD

**Issue by xuanyepan** [pt-plugins/PT-Plugin-Plus#1212]
- PT 助手版本:1.6
- PT 助手安装方式：zip（市场安装，或zip包安装）
- 浏览器名称及版本：edge 版本 108.0.1462.46 (正式版本) (64 位)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
天空站点无法读取用户信息，状态显示未知错误

- 相关截图：https://im.0668.cf/file/661e7198acf4b5dbdf62a.jpg

- 重现步骤：

**Comment by mitlearn** [comment]
HDSky无法刷新个人数据
由于HDSky开启了CF盾，导致PTPP刷新该站点数据时出现错误

解决方案：
手动访问一次userdetails.php页面(个人页面)，等待 Please stand by, while we are checking your browser... 消失并正常显示页面内容后再回到PTPP刷新数据
感谢这位群友提供  https://t.me/c/1276598895/73610

#HDSky

[https://t.me/ptpluginplus/131](https://t.me/ptpluginplus/131)
