### ISSUE TITLE
关于站点升级要求的一些反馈和建议

### ISSUE THREAD

**Issue by RoninAaron** [pt-plugins/PT-Plugin-Plus#1220]
- 第一次写issues 如格式或其他有问题的地方请见谅
- 观众[Audiences]的升级做种积分要求显示与站点要求不相符，
所有升级提示中的做种积分显示能否去除小数点后两位，有一些站点没有升级提示，如果能增加自由添加站点升级要求的功能会不会好一些（不知道有没有可行性）
感谢大佬对PT的付出！

**Comment by ted423** [comment]
自由添加 -> 提 pr是可行的

**Comment by ted423** [comment]
小数点这个是数据类型就会带的，暂时就这样吧
