### ISSUE TITLE
Edge浏览器crx安装报"包无效"错误

### ISSUE THREAD

**Issue by a490077** [pt-plugins/PT-Plugin-Plus#1223]
- PT 助手版本: 1.6.0
- PT 助手安装方式：crx安装（市场安装，或zip包安装）
- 浏览器名称及版本：Microsoft Edge 版本 108.0.1462.46 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
无法安装1.6.0

- 相关截图：
![image](https://user-images.githubusercontent.com/32692385/207200432-893f2683-7067-4f1b-a3b7-421ebfadeead.png)

- 重现步骤：
github下载1.6.0 crx安装包安装

**Comment by a490077** [comment]
商店最新版只有1.5.2

**Comment by fqh1995** [comment]
下载zip版本安装可以

**Comment by a490077** [comment]
> https://github.com/pt-plugins/PT-Plugin-Plus/wiki/install-from-crx

![image](https://user-images.githubusercontent.com/32692385/207203320-de268f5b-86ca-45bf-8631-7a4a7455fd13.png)
运行以后重启浏览器, 问题依旧, 暂时用回1.5.2了. .

**Comment by fqh1995** [comment]
> > https://github.com/pt-plugins/PT-Plugin-Plus/wiki/install-from-crx
> 
> ![image](https://user-images.githubusercontent.com/32692385/207203320-de268f5b-86ca-45bf-8631-7a4a7455fd13.png)运行以后重启浏览器, 问题依旧, 暂时用回1.5.2了..

我这没问题啊，解压完成后，浏览器设置，管理扩展，加载已解压的扩展，然后重启

**Comment by fzlins** [comment]
> > https://github.com/pt-plugins/PT-Plugin-Plus/wiki/install-from-crx
> 
> ![image](https://user-images.githubusercontent.com/32692385/207203320-de268f5b-86ca-45bf-8631-7a4a7455fd13.png) 运行以后重启浏览器, 问题依旧, 暂时用回1.5.2了. .

要点一下由贵单位管理才能看到

**Comment by ted423** [comment]
not a bug

**Comment by ted423** [comment]
确认你下的包是完整的

**Comment by a490077** [comment]
商店版更新了 😄

**Comment by wiiii** [comment]
勾选开发者模式,才能把crx扩展包安装上去.
