### ISSUE TITLE
提高反馈效率的建议和bug反馈

### ISSUE THREAD

**Issue by fqh1995** [pt-plugins/PT-Plugin-Plus#1224]
- 

- PT 助手版本:1.6.0
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Microsoft Edge
版本 108.0.1462.46 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：
搜索影视z相关影视总会有hdtime站点的种子
https://hdtime.org/details.php?id=47767&hit=1
- 相关截图：
照片太大没法上传
- 重现步骤：
【能不能建一个qq群，方便反馈问题。这个站点太慢了，不方便联系，下载也不方便】

**Comment by fqh1995** [comment]
> P主界面右下方有TG群组链接 图太大可以借助
> 图床上传

这个我知道，我的意思是用qq群交流方便，梯子很多人还不太实用

**Comment by fzlins** [comment]
可以发个外链的图片

**Comment by ted423** [comment]
我说下我对开源软件的理解。
开源软件是没有售后的，自然也没有高效客服，虽然我们有Mit.
你可以在任何相关的地方提出问题
