### ISSUE TITLE
希望增加对m-team馒头的时魔适配

### ISSUE THREAD

**Issue by ChrnoChou** [pt-plugins/PT-Plugin-Plus#1230]
## 您的功能请求是否与问题有关？ 请描述一下。

一些小站都有了时魔的适配,馒头暂时还没有,请求能适配一下,谢谢!

**Comment by 254327902** [comment]
馒头时魔获取在最新dev版本暂时还有问题，可能是因为捐助过后，字段增加 插件没有抓出来 等大佬fix
