### ISSUE TITLE
好像站点等级显示有bug？

### ISSUE THREAD

**Issue by jameszhu1987** [pt-plugins/PT-Plugin-Plus#1239]
PT 助手版本：1.6.0

PT 助手安装方式：zip包安装

浏览器名称及版本：Microsoft Edge 版本 108.0.1462.46 (正式版本) (64 位)

问题描述：
目前发现站点等级中，计算上传量有bug，举个例子：我的某站的现等级为Insane User，其要求为下载600G，分享率3.5，账号的现下载数据623.10G，现上传数据2.382T，实际分享率为3.91。下一等级Veteran User要求下载900G，分享率4.0，在“等级”一栏中，尚需的下载量数据（276.90G）是正确的，但是尚需的上传量数据是错误的。经过研究发现，尚需的上传量是以账号的现下载数据（623.10G）以下一等级Veteran User要求的分享率4.0来计算，显示尚需上传量53.23G（623.10×4-2.382×1024），这个应该是错误的，理应显示尚需上传量1.134T（900×4÷1024-2.382）。

相关截图：
![image](https://user-images.githubusercontent.com/1875131/207485413-6dc42695-8784-4a63-8d1c-4f4a701617ee.png)

**Comment by ted423** [comment]
应该是，因为他是拿你现在的下载去算了大概

**Comment by jameszhu1987** [comment]
> 不过还是请你下下最新版本的试试，因为我看我目前的分享率过高，基本不会提示有上传量需求

我安装的就是1.6.0最新的版本。。。

**Comment by jameszhu1987** [comment]
> 应该是，因为他是拿你现在的下载去算了大概

是的，按照我现在的下载量去计算了，看看下个版本是否会纠正这个bug吧，不过影响不大，其他数据都是正确的。

**Comment by jameszhu1987** [comment]
感谢两位大佬~~~
