### ISSUE TITLE
一个标题的小细节问题,希望能统一下

### ISSUE THREAD

**Issue by ChrnoChou** [pt-plugins/PT-Plugin-Plus#1260]
- 
![微信截图_20221216194735](https://user-images.githubusercontent.com/100701833/208091922-8403de24-dc74-43ce-ab03-d476b4c6b62e.png)

标题栏现在有左对齐的,有居中的,有右对齐的,数据更新于的"于"字在右对齐的外面了....有点逼死强迫症,希望大佬能优化下,感激不尽

**Comment by ted423** [comment]
感觉应该居中对齐

**Comment by ChrnoChou** [comment]
> 

都可以其实,只要统一了就行,那个"于"字我强迫症看的太难受了

**Comment by cnsunyour** [comment]
感觉标题栏前面三列“站点、用户名、等级”和后面两列“数据更新于、状态”都居中好看点。

**Comment by Rhilip** [comment]
> 感觉应该居中对齐

不是的，从UI设计上，数字右对齐是合理的。我觉得除了最后两列“数据更新于、状态”可以居中外，其他的都不用改。

至于目前 `数据更新于` 列，实际是都右对齐的。只是具体时间有个 `margin: 6px 8px`的外框。。。。
