### ISSUE TITLE
希望能适配下站点的special专区，如猪猪的儿童专区，冬樱的学术专区，自由农场和1ptba的特别区。

### ISSUE THREAD

**Issue by jjzinsser** [pt-plugins/PT-Plugin-Plus#1262]
- 
现在好多站都设有special专区，希望能适配。

**Comment by ted423** [comment]
比如

**Comment by cnsunyour** [comment]
啥是 special 区？

**Comment by jjzinsser** [comment]
比如 猪猪的儿童专区，冬樱的学术专区，自由农场和1ptba的特别区。

**Comment by EX-XD** [comment]
附议。
比如猪的儿童区里面有些种子其他站也能搜到，其实可以合并辅种的

**Comment by IITII** [comment]
应该都适配了, 没适配的站点贴出具体 url.

**未贴出的站点延后处理或者等 PR**

**Comment by tmzg0000** [comment]
> 应该都适配了, 没适配的站点贴出具体 url.
> 
> **未贴出的站点延后处理或者等 PR**

https://pt.0ff.cc/special.php  目前没有适配。
