### ISSUE TITLE
求教如何编辑站点等级？

### ISSUE THREAD

**Issue by jameszhu1987** [pt-plugins/PT-Plugin-Plus#1264]
之前有个版本的PTPP是可以自己编辑站点等级的，在rank里面就可以，新版本能自行编辑站点等级吗？手头有很多站点都没有显示等级，如果需要，我也可以把站点等级代码上传，就是不知道新版本在哪修改/新增。请指教。

**Comment by ted423** [comment]
你说的是不是白大版？原版是一直不行的

**Comment by fzlins** [comment]
自己编辑站点等级有什么意义？

**Comment by ted423** [comment]
@fzlins https://github.com/pt-plugins/PT-Plugin-Plus/issues/1221 可能跟这个类似

**Comment by jackycher** [comment]
![QQ截图20221226091145](https://user-images.githubusercontent.com/37903399/209487662-3ce00439-0305-4ee5-837c-16785e6399f2.png)
应该是类似于这样，把每个站点的升级条件列出来。
我试了一下，可以自行增加./resource/systemConfig.json文件中的levelRequirements字段，如图
![QQ截图20221226091825](https://user-images.githubusercontent.com/37903399/209487811-b8e798db-d37b-47ff-b1bd-e528f3512614.png)
其中的level、name、interval、uploaded、downloaded、bonus、ratio、seedingPoints、privilege等分别对应等级、名称、时间、上传量、下载量、魔力值、分享率、做种积分、特权等内容。
修改保存后需要重启浏览器加载新的.json文件生效，改了几个网站是可以的
但是现在不太清楚./resource/systemConfig.json  ./resource/schemas/config.json 以及 ./resource/网站域名/config.json三个配置之间的关系，暂时发现修改网站域名下的不生效，修改systemConfig.json有效。

**Comment by fzlins** [comment]
> ![QQ截图20221226091145](https://user-images.githubusercontent.com/37903399/209487662-3ce00439-0305-4ee5-837c-16785e6399f2.png) 应该是类似于这样，把每个站点的升级条件列出来。 我试了一下，可以自行增加./resource/systemConfig.json文件中的levelRequirements字段，如图 ![QQ截图20221226091825](https://user-images.githubusercontent.com/37903399/209487811-b8e798db-d37b-47ff-b1bd-e528f3512614.png) 其中的level、name、interval、uploaded、downloaded、bonus、ratio、seedingPoints、privilege等分别对应等级、名称、时间、上传量、下载量、魔力值、分享率、做种积分、特权等内容。 修改保存后需要重启浏览器加载新的.json文件生效，改了几个网站是可以的 但是现在不太清楚./resource/systemConfig.json ./resource/schemas/config.json 以及 ./resource/网站域名/config.json三个配置之间的关系，暂时发现修改网站域名下的不生效，修改systemConfig.json有效。

在./resource/网站域名/config.json下添加站点的配置，添加后需要build一下才能使用。参考下面的连接：
https://github.com/pt-plugins/PT-Plugin-Plus/wiki/develop-define-site
