### ISSUE TITLE
建议发送到qbittorrent支持添加category以及设定分享率

### ISSUE THREAD

**Issue by zx900930** [pt-plugins/PT-Plugin-Plus#1268]
## 您的功能请求是否与问题有关？ 请描述一下。
发送到qbittorent目前只支持设置下载路径

## 描述你想要的解决方案
建议支持添加类别category, 以及设定目标分享率

## 描述您考虑过的替代方案
无

## 其他附加信息
无

**Comment by Rhilip** [comment]
#821 目前ptpp在上层没有开放对应接口给到qbt client的实现中，该feature实现不了。
