### ISSUE TITLE
BeyondHD刷新数据异常，显示“未登录”

### ISSUE THREAD

**Issue by jaaaaaaaah** [pt-plugins/PT-Plugin-Plus#1277]
- PT 助手版本: v1.6.0.2111
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Microsoft Edge 版本 108.0.1462.54 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
刷新该站点显示“未登录”，数据图表中只查看该站点数据未更新且未清零，但查看所有站点数据时中该站点数据清零。

- 相关截图：
![image](https://user-images.githubusercontent.com/44402079/209613601-9c85e667-834f-46fd-b122-acd635118e09.png)

- 重现步骤：
刷新数据

**Comment by ted423** [comment]
更下最新action版本
