### ISSUE TITLE
TLFBits在搜索界面不显示做种状态

### ISSUE THREAD

**Issue by LoneFireBlossom** [pt-plugins/PT-Plugin-Plus#1278]
- PT 助手版本: © 栽培者 2022, 版本 v1.6.0.2112 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 版本 108.0.5359.124（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：依旧有下面的问题
- 问题描述：

TLFBits、BLU、HD-Space、TorrentLeech在PTPP搜索界面不显示做种状态。

https://github.com/pt-plugins/PT-Plugin-Plus/issues/1194#issuecomment-1346743763

TLF在搜索页能显示做种状态，所以应该能显示吧。
BLU不知道行不行？
HD-Space和TL我想不太可能，不过还是问一下。

- 相关截图：

- 重现步骤：

**Comment by fzlins** [comment]
#1483
