### ISSUE TITLE
我的数据部分空白

### ISSUE THREAD

**Issue by Xm798** [pt-plugins/PT-Plugin-Plus#1281]
- PT 助手版本: v1.6.0.ba3d87e
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome 108.0.5359.124 (arm64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

我的数据部分空白，但站点设置已添加站点。

- 相关截图：

<img width="2321" alt="CleanShot 2022-12-29 at 23 43 04@2x" src="https://user-images.githubusercontent.com/48074861/209976459-dbd6300c-6e16-4087-be2a-0aed48787320.png">

![CleanShot 2022-12-29 at 23 43 36@2x](https://user-images.githubusercontent.com/48074861/209976554-0bb503f1-de9d-467d-b880-e79a90e92ba1.png)

- 重现步骤：

不清楚能否复现，但是问题是在添加一个站点后出现的。添加之前一切正常。

- 尝试修复：

已尝试卸载插件后重新安装，并重新添加站点，无法恢复。

**Comment by ted423** [comment]
@Xm798 装下最新的action版本或者刷新下数据
