### ISSUE TITLE
有什么办法可以一键认领种子吗？

### ISSUE THREAD

**Issue by snfcx** [pt-plugins/PT-Plugin-Plus#1283]
## 您的功能请求是否与问题有关？ 请描述一下。

批量选中正在做种的种子并且认领

**Comment by ted423** [comment]
个人感觉是非必要功能

**Comment by snfcx** [comment]
> 个人感觉是非必要功能

是的，这个功能很少用。
所以问下有没有现成的脚本之类的。搜到一个油猴脚本但是不是我想要的站点我更改了脚本中的运行网站和下面的拼接网址也发现不适用（其他的代码看不懂不会改），就来问问有没有人解决过类似的问题。
https://greasyfork.org/zh-CN/scripts/441395

**Comment by ted423** [comment]
这个可以去相关站的讨论群求助。因为每个站实现可能不太一样。
可能这种用控制台会更好

**Comment by snfcx** [comment]
> 这个可以去相关站的讨论群求助。因为每个站实现可能不太一样。 可能这种用控制台会更好

好的，谢谢！
