### ISSUE TITLE
Mozilla 不再允许复用从市场中删除的扩展所用的 ID

### ISSUE THREAD

**Issue by davidxuang** [pt-plugins/PT-Plugin-Plus#1285]
- PT 助手版本：1.6.0.2120
- PT 助手安装方式：Mozilla 开发者自托管
- 浏览器名称及版本：Firefox
- 浏览器是否安装了其他插件：N/A
- 停用其他插件后是否正常工作：N/A
- 问题描述：由于 Mozilla 引入的新政策，旧 ID 不再能被上传 mozilla/addons-server#18253 mozilla/addons-server#19501

- 相关截图：
![图片](https://user-images.githubusercontent.com/24728204/210242933-42cc463a-fdd8-4d28-8be0-50dcbf203bca.png)

- 重现步骤：
按 [wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki/install-from-amo) 也即 #491 的方法

**Comment by Rhilip** [comment]
你上传xpi干嘛？xpi是我们从ff那边签好你可以直接用的。
你要自己签的话可以用zip或者crx。
