### ISSUE TITLE
HDsky未知错误，其他站点正常

### ISSUE THREAD

**Issue by Tinkle-dong** [pt-plugins/PT-Plugin-Plus#1286]
- PT 助手版本:版本: 1 . 6 . 0 . b a 3 d 8 7 e
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Edge 版本 108.0.1462.54 (正式版本) (64 位)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
HDsky未知错误，其他站点正常

- 相关截图：

![image](https://user-images.githubusercontent.com/13516632/210518265-9ed1212f-1776-4f67-a5bb-f2251095ccc1.png)

- 重现步骤：

**Comment by ted423** [comment]
dupe https://github.com/pt-plugins/PT-Plugin-Plus/issues/1212
