### ISSUE TITLE
多个WEBDAV备份，修改其中一个，另外一个也会自动修改成新设置的配置。

### ISSUE THREAD

**Issue by Bender1337** [pt-plugins/PT-Plugin-Plus#1297]
- PT 助手版本:© 栽培者 2023, 版本 v1.6.0.ba3d87e
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge版本 108.0.1462.76 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
备份WEBDAV服务器，设置了两个，但是修改后其中一个后，另外一个也会修改成新设置的配置。
- 相关截图：

- 重现步骤：每次

**Comment by ted423** [comment]
试了下，没再现。
能否确认下你的服务名称分别是什么

**Comment by Bender1337** [comment]
名称一个是本地。另一个是123盘。
刚才删除插件又装了一次。
添加了两个随便填写的 服务器。
然后都修改了一次，再修改，就出现莫名的问题。
出现的问题不一定是两个配置变成一样。
总之就是多次修改以后，就会出现问题。
![微信图片_20230131154513](https://user-images.githubusercontent.com/54093431/215698258-2eb667ed-5fc9-4e1f-b63d-09be44104ff3.png)
![微信图片_20230131154521](https://user-images.githubusercontent.com/54093431/215698290-2d89b92a-ad8e-410d-84ec-9480a0289ae3.png)

**Comment by ted423** [comment]
两个服务器地址呢
因为我这边一直是有两个，没试出问题

**Comment by ted423** [comment]
哦，改第二个会出问题

**Comment by ted423** [comment]
改第二个的时候会覆盖掉第一个，改第一个似乎没事

**Comment by Rhilip** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/releases/tag/v1.6.1.1994
