### ISSUE TITLE
「我的数据」没有显示任何数据

### ISSUE THREAD

**Issue by Showfom** [pt-plugins/PT-Plugin-Plus#1298]
- PT 助手版本: v1.6.0.ba3d87e
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge Version 110.0.1587.6 (Official build) Dev (arm64)
- 浏览器是否安装了其他插件：CrxMouse Chrome™ Gestures，1Password 和 Adblock Plus
- 停用其他插件后是否正常工作：否
- 问题描述：我的数据页面中不显示任何数据

- 相关截图：

![image.png](https://arina.loli.net/2023/01/11/odrEUpMknQFXAsc.png)

- 重现步骤：

已经添加所有站点，并且获取的数据截图都是正常的

**Comment by Showfom** [comment]
在 Search 的框框里随便输入个内容并且删除以后，就显示数据了，应该是个前端的 bug

**Comment by ted423** [comment]
@Showfom 这个问题在最新action版本里已被修复

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1281
