### ISSUE TITLE
天空数据刷新提示错误！！！！

### ISSUE THREAD

**Issue by SeanSuny** [pt-plugins/PT-Plugin-Plus#1304]
- PT 助手版本:1.6.1.1966
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome 108.0.5359.125
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
天空数据加载提示发生错误

- 相关截图：
![image](https://user-images.githubusercontent.com/20199755/212585782-c6e7ce49-58a8-4aaf-b385-a882c32f02b5.png)

- 重现步骤：

**Comment by mitlearn** [comment]
日经问题 先搜再问https://github.com/pt-plugins/PT-Plugin-Plus/issues/1286
