### ISSUE TITLE
nginx反代后远程下载不稳定

### ISSUE THREAD

**Issue by luckiestone** [pt-plugins/PT-Plugin-Plus#1305]
- PT 助手版本: v1.6.1.1966
- PT 助手安装方式：crx
- 浏览器名称及版本：edge 108.0.1462.76
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
为解决transmission被暴力攻击导致无法登录的问题，采用了白名单加反代的方式访问。
但是工作不稳定，有时能正常工作，但是近一段时间不太正常。
已经尝试：
1. 全局代理
2. 重启反代服务
3. 加长全局timeout时长
4. nginx单独添加```^~ /transmission/```的location
均无效。背景页为rpc无响应数据。但是web访问/transmission/rpc是正常的。很奇怪
nginx配置如下：
```
    server {
    listen 80;
    server_name 域名;
    root html;
    index index.html index.htm;

    location / {
        proxy_pass http://ddns:9090;
        root   /www/wwwroot/域名;
        index  index.html index.htm;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }
}
```

- 相关截图：
不需要

- 重现步骤：
不清楚问题出在哪，不确定能否重现

**Comment by Rhilip** [comment]
很难说问题出在插件这边，有试过其他transmission rpc的客户端吗？比如 [Transdroid](https://www.transdroid.org/) 或者 https://github.com/bogenpirat/remote-torrent-adder

**Comment by luckiestone** [comment]
> 很难说问题出在插件这边，有试过其他transmission rpc的客户端吗？比如 [Transdroid](https://www.transdroid.org/) 或者 https://github.com/bogenpirat/remote-torrent-adder

我用的是 https://github.com/y-polek/TransmissionRemote 和 https://github.com/transmission-remote-gui/transgui 这两个都没问题。不过加入反代后，确实访问变慢，可能是网络导致的响应慢。我换个网络更好的机器来做反代机试试。

**Comment by ted423** [comment]
扩展debug看下推送重试次数，不行多试几次
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1046
不过每次重试都会下遍种子，部分站点有种子下载次数限制

**Comment by luckiestone** [comment]
> 扩展debug看下推送重试次数，不行多试几次 #1046 不过每次重试都会下遍种子，部分站点有种子下载次数限制

应该是网络相关的奇怪问题，我把tr的反代迁移到本地后正常。之前尝试的把反代机迁移到网络质量好的也不行，感觉和本地网络有某种奇怪的关系。当该问题发生时，PLEX的刮削服务连接困难、本地smokeping服务经过境外反代机访问也很缓慢。感觉是本地访问外网的某种奇怪限制，实际上其他访问境外的速度是很快的。
