### ISSUE TITLE
下载整页种子时触发流控

### ISSUE THREAD

**Issue by lyj0309** [pt-plugins/PT-Plugin-Plus#1307]
- PT 助手版本: 1.60
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件： no
- 停用其他插件后是否正常工作：no
- 问题描述：
当下载整页种子时，会触发流控，导致种子下载不了

- 相关截图：

柠檬
`一分钟内请求次数过多，请过一分钟再下载。`

- 重现步骤：

到柠檬随便找一页，下载整页

**Comment by ted423** [comment]
这不算issue
