### ISSUE TITLE
天空一直不正常

### ISSUE THREAD

**Issue by weicjang** [pt-plugins/PT-Plugin-Plus#1314]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by cnsunyour** [comment]
@weicjang 这都啥人啊，提 issue 之前不会先搜索么？
