### ISSUE TITLE
体积 上传等数据转换问题 十进制 二进制混淆

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#1317]
- PT 助手版本: all
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
https://github.com/pt-plugins/PT-Plugin-Plus/blob/8c40f6020118f7b2f00a75a8bd1eae35b7674107/src/interface/types.expand.js#L14-L38
https://zh.wikipedia.org/zh-tw/Gibibyte
- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
一些站点标注是GB,pt助手使用的是GiB(虽然对方sysop可能也会弄错)
总之可能存在问题

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/215254469-180a8f64-d7d5-4346-8f4d-ad35fea14861.png)

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/215254999-12f3d82f-c7af-44e1-9135-a9f8acaa1001.png)
看了下，大部分都是站点本身就弄错了
故这个issue就当是标注好了

**Comment by Rhilip** [comment]
NPHP实现就是用1024的
https://github.com/xiaomlove/nexusphp/blob/fb803d198997cf886ab29d5a0e31191c3a9e5d58/include/functions.php#L2098-L2156

**Comment by ted423** [comment]
@Rhilip 按我理解应该都写GiB啥的🤣

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/215924332-acbdb6be-0d4f-4c35-9a7f-f87a32aa78f7.png)
![image](https://user-images.githubusercontent.com/7042766/215924344-5d21ca53-dc44-4550-bd75-b45b2d4eacdc.png)
才发现升级这块全写错了
