### ISSUE TITLE
大哥，您好，请求加入下载以中文目录为

### ISSUE THREAD

**Issue by s3000sss** [pt-plugins/PT-Plugin-Plus#1319]
## 您的功能请求是否与问题有关？ 请描述一下。

我在馒头下载的目录全是英文的，有时候不好查询，可否加入变成列表中的中文目录
项目列表中，第一行为英文，第二行是中文，谢谢
## 描述你想要的解决方案

我在馒头下载的目录全是英文的，有时候不好查询，可否加入变成列表中的中文目录
项目列表中，第一行为英文，第二行是中文，谢谢
## 描述您考虑过的替代方案

我在馒头下载的目录全是英文的，有时候不好查询，可否加入变成列表中的中文目录
项目列表中，第一行为英文，第二行是中文，谢谢

**Comment by ted423** [comment]
感觉那样会很难看，要不这样，你多加几个同样的下载服务器，然后每个指定固定目录，然后通过下载服务器的名字来区分

**Comment by s3000sss** [comment]
大哥，就是以副标题，为目录名称

**Comment by s3000sss** [comment]
比如这种，
![QQ图片20230129221525](https://user-images.githubusercontent.com/123881851/215332384-d133c1d9-def2-4ee9-8c88-17dbd8665553.png)

**Comment by ted423** [comment]
我不记得有类似功能，你确认下是不是种子里自带的文件夹名

**Comment by fzlins** [comment]
这是种子创建时的信息决定的无法修改
