### ISSUE TITLE
ExoticaZ成人站点

### ISSUE THREAD

**Issue by Jerry-Roxe** [pt-plugins/PT-Plugin-Plus#1324]
- 站点名称：ExoticaZ
- 站点地址：https://exoticaz.to/
- 站点描述：18+的英文站，我也不知道啥描述

- 资源类型：成人
- 开放注册：否
- 是否连坐：是
- 站点规则：

Banned
Description: Users banned from the site for violation of site rules.
Limits: Cannot access the site.

Deleted
Description: Users deleted, pending purge.
Limits: Cannot access the site.

Leech
Description:  Members who haven't seeded (shared) back what they have downloaded are demoted to Leech class. Can become members in good standing (Member status) again when ratio reaches 1.0 or above.)
Limits: Can download 1 torrent a day. Limited to download torrents uploaded 1 week ago. Cannot upload.

Newbie
Description: Newly registered users. Limited to download torrents uploaded 1 week ago.
Limits: Can download 5 torrents a day. Cannot upload.

Member
Description: Registered users with 5GB upload and ratio above 1.0. (Newbies are automatically promoted to member status when they have been newbies for 7 or more days and have achieved a ratio of 1.0 or higher with at least a 5GB upload.)
Limits: Can download 100 torrents a day. Can upload.

V.I.P.
Description: Donator / Distinguished member / Retired Staff.
Limits: Can download 200 torrents a day. Can upload.

Uploader
Description: These users are promoted by site management to Uploader class on the basis of the quantity and quality of their uploads. (Uploaders will be returned to Member class if they stop uploading on a regular basis.).
Limits:  Secret. Can upload.

Editor
Description: These users are promoted by site management to assist editing site contents.
Limits: Secret. Can upload.

Staff
Description: Site assistant.
Limits: Secret.

Moderator
Description: Moderates the site.
Limits: Secret.

Admin
Description: Administers/Moderates the site.
Limits: Secret.

Super Admin
Description: The big boss.
Limits: Secret.

 

Additional information
Download limit resets in 24 hours from your earliest download.
The torrent download limit is in place to keep users from downloading too much without realizing they fall into Leech user group.

**Comment by dysf888** [comment]
@Jerry-Roxe 身体吃不消。

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/996
