### ISSUE TITLE
大哥，可否根据下载目录自己分类

### ISSUE THREAD

**Issue by s3000sss** [pt-plugins/PT-Plugin-Plus#1326]
大哥，可否根据下载目录自己分类

如 PT助手 下载目录 为  d:\软件

则 在QBITTORRENT 分类中 也为 软件

现在下载 目录 ，会被分到未分类

**Comment by s3000sss** [comment]
> _
![无标题](https://user-images.githubusercontent.com/123881851/215997274-92a136e7-c45a-4a76-8a44-2655d5d3bfeb.jpg)
_

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1030
