### ISSUE TITLE
增加深色/暗黑/黑色模式

### ISSUE THREAD

**Issue by leic4u** [pt-plugins/PT-Plugin-Plus#1330]
## 您的功能请求是否与问题有关？ 请描述一下。

晚上关灯后打开 PTPP ，有点刺眼，关键 Dark Reader 还不能对 PTPP 生效。所以请求一个 深色/暗黑/黑色模式。

## 描述你想要的解决方案

提供浅色/深色模式切换。

## 描述您考虑过的替代方案

Dark Reader 强制转换页面，但是对浏览器插件的页面没法生效。

**Comment by ted423** [comment]
dupe了

**Comment by leic4u** [comment]
@ted423 你是说跟 #928 吗？我看 #928 并没有解决呢

**Comment by ted423** [comment]
issue里面有解释

**Comment by leic4u** [comment]
好的，那只能等v2了吧。。。

**Comment by Rhilip** [comment]
请使用action版或者pre release。深色模式已经实装了。

**Comment by leic4u** [comment]
@Rhilip 已使用 pre-release 1.6.1.1994，已实现深色模式功能，谢谢！
