### ISSUE TITLE
chrome安装插件之后使用不正常

### ISSUE THREAD

**Issue by EvanZhangJ** [pt-plugins/PT-Plugin-Plus#1331]
- PT 助手版本:v1.6.1.1994
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 109.0.5414.120
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：仍不能正常工作
- 问题描述：
配置好网站之后，刷新数据显示发生错误，到后台发现很多错误信息，具体如截图

- 相关截图：
![image](https://user-images.githubusercontent.com/124326662/216498939-06d9a1bc-df12-4f76-ae68-8c529aef072d.png)

- 重现步骤：
安装后配置任意一个PT站，刷新即出现此问题

**Comment by ted423** [comment]
这个不会影响到发生错误

**Comment by ted423** [comment]
一般来说发生错误都是网络问题导致的，你看下你直接打开网页会不会很难加载

**Comment by EvanZhangJ** [comment]
网络挂了代理，应该不是网络问题

**Comment by ted423** [comment]
那就不要用zip,用crx,zip不作为标准模式

**Comment by EvanZhangJ** [comment]
又增加了一些站点 发现只有HDSky站显示错误 其他站点正常

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1093
