### ISSUE TITLE
希望增加夜间模式主题

### ISSUE THREAD

**Issue by xunun** [pt-plugins/PT-Plugin-Plus#1333]
## 您的功能请求是否与问题有关？ 请描述一下。

晚上使用的时候，白色背景还是挺扎眼的。而其他的夜间模式插件又不能对此生效。
希望内置个深色背景的界面主题。

**Comment by mitlearn** [comment]
Dupe https://github.com/pt-plugins/PT-Plugin-Plus/issues/1330
