### ISSUE TITLE
yarn upgrade 出现问题

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#1349]
- PT 助手版本: dev最新
- PT 助手安装方式： crx
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64262
疑似

- 相关截图：
![image](https://user-images.githubusercontent.com/7042766/219551215-971977ad-fdc5-4432-bc37-894d49d1e924.png)

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/commit/cb0d1edd69514f47cc36f81738c93209a8375eec

**Comment by ted423** [comment]
TypeScript 3.9 which is no longer supported by DefinitelyTyped.

**Comment by Rhilip** [comment]
@ted423 @types/node 没必要拉那么高， 16.11.7 就可以了
