### ISSUE TITLE
站点SSD搜索结果页面不显示副标题

### ISSUE THREAD

**Issue by Taosky** [pt-plugins/PT-Plugin-Plus#1350]
- PT 助手版本: v1.6.0.ba3d87e 
- PT 助手安装方式：zip包
- 浏览器名称及版本：Firefox 109.01（Mac）
- 问题描述：SSD的搜索结果不显示副标题，以前是有的，不知道是不是站点改动了。检查了确实没有内容。

- 相关截图：
<img width="1022" alt="图片" src="https://user-images.githubusercontent.com/7688350/219870576-1129b1b6-0242-450b-a056-bfef305694d1.png">
<img width="678" alt="图片" src="https://user-images.githubusercontent.com/7688350/219870869-1ead8f45-8410-4644-a65d-3b2377902622.png">

**Comment by ted423** [comment]
包版本，安装方式都不对

**Comment by ted423** [comment]
请使用最新版本的crx
