### ISSUE TITLE
辅种 设置保存目录 显示为一个小框

### ISSUE THREAD

**Issue by vpioe** [pt-plugins/PT-Plugin-Plus#1355]
- PT 助手版本:dev-build-1.6.1.2037，旧版也有
- PT 助手安装方式：crx，zip均试过
- 浏览器名称及版本：Chrome 110.0.5481.104
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
辅种验证完后，设置保存目录，显示为一个小框，点击无反应

- 相关截图：
![image](https://user-images.githubusercontent.com/8914209/220356582-9d1d6f23-1c25-4c22-982e-1afe3e9f92cd.png)

- 重现步骤：

1.搜索种子
2.等待验证
3.点击设置保存目录
4.GG

**Comment by ted423** [comment]
@vpioe 你设了下载服务器了么

**Comment by ted423** [comment]
无法复现

**Comment by vpioe** [comment]
> @vpioe 你设了下载服务器了么

未设置

**Comment by vpioe** [comment]
qb客户端仅在本地主机如何设置？

**Comment by ted423** [comment]
@vpioe https://github.com/pt-plugins/PT-Plugin-Plus/wiki/config-download-client

**Comment by mitlearn** [comment]
> qb客户端仅在本地主机如何设置？

![image](https://user-images.githubusercontent.com/64004444/220362619-80a5a178-c503-4ea6-bb72-d76e3f998fb8.png)
请注意开启qb的webUI

**Comment by vpioe** [comment]
可以了，十分感谢两位！

**Comment by chenjingchun** [comment]
![image](https://user-images.githubusercontent.com/4917940/224874130-de3e8f7e-fbaf-4631-a43a-7d08374557f9.png)

我的怎么啥都没有，服务器设置了

**Comment by ted423** [comment]
@chenjingchun f5 刷新下试试呢

**Comment by chenjingchun** [comment]
> @chenjingchun f5 刷新下试试呢

没用，ctrl+f5也没有效果。
我是从Releases里下载的zip安装的，版本 v1.6.1.2019 zip

**Comment by ted423** [comment]
> > @chenjingchun f5 刷新下试试呢
> 
> 没用，ctrl+f5也没有效果。 我是从Releases里下载的zip安装的，版本 v1.6.1.2019 zip

设置下载服务器以及默认下载服务器。另外建议用crx
