### ISSUE TITLE
是否可以考虑提供一个右键菜单的开关

### ISSUE THREAD

**Issue by wxg1015** [pt-plugins/PT-Plugin-Plus#1357]
## 您的功能请求是否与问题有关？ 请描述一下。

安装ptpp后浏览器右键菜单会多出来一个发送到ptpp服务器的按钮，而这个按钮在有工具栏的情况下没什么意义，至少我几乎不用，我都是用工具栏的。而且最关键的是它不止在pt站点上右键时显示 也会在其他任意站点上出现在右键菜单里(上边还直接显示着我的域名+端口，且很长一段) 。感觉无用又不美观，最主要的是，bt站里即使我想用他来推送bt任务  也无法选择指定目录 点他只能发送到下载器默认目录
## 描述你想要的解决方案

我看了下ptpp设置里有工具栏的开关选项，所以能否给这个右键菜单按钮也增加一个开关按钮 ，或者可以让他不在ptpp添加的站点以外的网页上的右键菜单里显示

**Comment by fzlins** [comment]
无法重现，我这里并不会在ptpp添加的站点以外的网页的右键菜单里显示。插件按道理是绑定网站的，请提供版本号、浏览器、是否添加自定网站等更多信息，以便重现。

**Comment by wxg1015** [comment]
> 无法重现，我这里并不会在ptpp添加的站点以外的网页的右键菜单里显示。插件按道理是绑定网站的，请提供版本号、浏览器、是否添加自定网站等更多信息，以便重现。

ptpp版本:1.6.1:2041
浏览器:edge
添加了几个自定义的pt站 因为手头有几个pt站ptpp默认没有支持 所以自定义添加了  
然后我说的这种情况是出现在了自定义添加的站点和全部的普通站点上的![IMG_20230225_004345.jpg](https://user-images.githubusercontent.com/44153358/221236989-ca4eaf2a-80fa-4dd8-a481-29419d264efa.jpg)

![IMG_20230225_004333.jpg](https://user-images.githubusercontent.com/44153358/221236988-e1f47093-bddd-49f8-8761-eef6b71cede6.jpg)

**Comment by ted423** [comment]
@fzlins 指的是右键连接推送到服务器那个，我的观点是治下强迫症就好了

**Comment by wxg1015** [comment]
好吧 我好像报了个乌龙  之前一直用的用了很久的配置  刚才推倒重新配置  没有那种非pt站有右键按钮的情况了......

**Comment by ted423** [comment]
还是个人观点，这个功能在gz,以及其他页面列表页基本算是核心功能，不考虑加开关

**Comment by wxg1015** [comment]
> 还是个人观点，这个功能在gz,以及其他一些架构列表页基本算是核心功能，不考虑加开关

雀氏 目前来看 应该是因为我长久以来一直覆盖保存的老旧配置导致的  完全重新配置后 不存在这个问题了

**Comment by wxg1015** [comment]
不过我发现海棠这个站貌似工具栏是双份的 ，而且右键菜单里没有推送ptpp下载器的按钮。
实际上我完全重新配置后，  所有其他网站都是没ptpp右键推送按钮的，所有pt站都是有ptpp右键推送按钮的，这是正常的对吧。
 唯独海棠没有且右侧工具栏还是双份的，这个站点并非自定义添加的站点， 就很奇怪。
![IMG_20230225_011011.jpg](https://user-images.githubusercontent.com/44153358/221244990-c9c87f20-616b-4a53-bd4c-3a337c3f9c34.jpg)

![IMG_20230225_011030.jpg](https://user-images.githubusercontent.com/44153358/221245002-f92ba14f-96a9-4091-a081-93f06e87cba4.jpg)

**Comment by wxg1015** [comment]
> 无法重现，我这里并不会在ptpp添加的站点以外的网页的右键菜单里显示。插件按道理是绑定网站的，请提供版本号、浏览器、是否添加自定网站等更多信息，以便重现。

找到原因了  我之前是在 (常规设置-默认下载器)里 指定了我目前在用的下载器。
指定后就会在所有网站的右键菜单里添加ptpp的推送到默认下载器的按钮(除了我添加的pt站)。
