### ISSUE TITLE
BLU 搜索种子出错

### ISSUE THREAD

**Issue by Mark-Imaginist** [pt-plugins/PT-Plugin-Plus#1359]
- PT 助手版本: 1.6.1.2041
- PT 助手安装方式：zip
- 浏览器名称及版本：Edge 110.0.1587.56
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：BLU 搜索不到种子，提示脚本执行出错

- 相关截图：
<img width="520" alt="chrome-extension___objbnpefpielkdhpojnhomnegbebndip_index html" src="https://user-images.githubusercontent.com/38615702/221367233-2a9c97d6-870f-42b7-b8bb-f4ae4cc69799.png">

- 重现步骤：使用关键词或 IMDb 编号搜索

**Comment by ted423** [comment]
@Mark-Imaginist 试试用crx

**Comment by Mark-Imaginist** [comment]
> @Mark-Imaginist 试试用crx

测试过，一样出错

**Comment by ted423** [comment]
页面改版了

**Comment by ted423** [comment]
确认了下，他们自己页面乱了，理论他们自己代码出了bug,所以先等他们把页面调正常了再看看

**Comment by 1thereal** [comment]
唉，有半个月这样了，只能去他们站内搜索

**Comment by ted423** [comment]
fixed in dev
