### ISSUE TITLE
增强站点图标的模糊效果或者添加隐藏站点图标的选项

### ISSUE THREAD

**Issue by qinhuaihe** [pt-plugins/PT-Plugin-Plus#1362]
## 您的功能请求是否与问题有关？ 请描述一下。

现在很多网站不允许在公共场所出现，即使模糊了也不行，只要能认出来，就有可能导致账号封禁。

## 描述你想要的解决方案

希望能够加强模糊或者隐藏图标以实现匿名的效果。

**Comment by Rhilip** [comment]
对于不允许出现在公共场所出现的网站，建议直接在时间线内关闭
