### ISSUE TITLE
PTHOME无法一键下载 提示无效种子

### ISSUE THREAD

**Issue by Small-SaltedFish** [pt-plugins/PT-Plugin-Plus#1363]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

- PT 助手版本:v1.6.0.ba3d87e zip
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome 110.0.5481.178
- 浏览器是否安装了其他插件：有一个其他插件
- 停用其他插件后是否正常工作：否
- 问题描述：
一键下载提示无效种子

- 相关截图：
![image](https://user-images.githubusercontent.com/34180066/223028222-6aed4a94-3a9f-4913-b291-1117a0dd7770.png)

- 重现步骤：
直接一键下载种子

**Comment by ted423** [comment]
请确保你看了常见问题

**Comment by Small-SaltedFish** [comment]
你好 我已经查看过常见问题 但是我不是第一次下载种子  已经下载过数个种子 目前我尝试重新安装action编译的v1.6.1.2045 crx版本 目前的情况不知为何连边上的工具栏都找不到了 之前那个版本是有的 页面已经加载完毕 两个pt站都如此 很抱歉打扰你 但是我确实遇到了问题

**Comment by ted423** [comment]
不用抱歉，这里并不是不欢迎提issue
提issue需要尽可能详细的提供信息,并且我没有复现。

删掉站点重新加试试。另外提供下你使用的url。目测是老配置的问题

**Comment by Small-SaltedFish** [comment]
目前删除站点后重新添加站点 一开始仍不显示工具条 后来在ptpp中点击链接工具条正常显示
目前是pthome https://pthome.net/ 无法正常发送种子到服务器

**Comment by ted423** [comment]
工具条不会在所有页面出现，
详细使用按键的url

**Comment by Small-SaltedFish** [comment]
是的 我明白工具条不会全部显示 但是目前通过在ptpp中点击此处的链接目前已恢复正常
![image](https://user-images.githubusercontent.com/34180066/223039896-9ad796e2-e53d-4b71-b6d1-77c8ab82f456.png)
感谢您的秒回 现在就是无法推送种子了:)

**Comment by ted423** [comment]
详细的使用按钮的url 比如 种子列表，还是种子详情页
另外zip是有个控制台页面的
在扩展页面有一个
背景页
点进去看下log是怎么样的

**Comment by Small-SaltedFish** [comment]
种子详情页
![image](https://user-images.githubusercontent.com/34180066/223042383-5ccbea22-f765-40df-8ac8-e5d51b9be30e.png)

**Comment by Small-SaltedFish** [comment]
![image](https://user-images.githubusercontent.com/34180066/223042544-90d00454-d6e6-4990-ba3e-95f27023517d.png)
飚红的目测无关

**Comment by ted423** [comment]
你的配置里的passkey删了

**Comment by Small-SaltedFish** [comment]
感谢 确实解决了 这是什么原因呢 那我还可以查询我的用户数据吗

**Comment by Small-SaltedFish** [comment]
还是说我应该复制上去的是downhash

**Comment by ted423** [comment]
@Small-SaltedFish 我把常见问题更新了

**Comment by Small-SaltedFish** [comment]
好的 感谢您 那么所以不需要passkey只要有cookie在也能查阅用户数据 对吗

**Comment by ted423** [comment]
@Small-SaltedFish 是的

**Comment by Small-SaltedFish** [comment]
谢谢您的回复
