### ISSUE TITLE
三台设备的PTPP均不能识别BeyondHD的信息，显示“未登录”

### ISSUE THREAD

**Issue by WCH9527** [pt-plugins/PT-Plugin-Plus#1366]
- PT 助手版本:v1.6.0.ba3d87e
- PT 助手安装方式：Edge浏览器市场安装，自动更新
- 浏览器名称及版本：Microsoft Edge 版本 111.0.1661.41 (正式版本) (64 位)
- 浏览器是否安装了其他插件：一个去广告、一个油猴
- 停用其他插件后是否正常工作：没区别
- 问题描述：
三台win10系统电脑，ltsc、专业版、正版家庭版，用Edge浏览器在插件市场安装的插件，自动更新的1.6.0然后出现两个问题：（1）HDSky站点刷新失败，必须先进入站点再进入个人页面保持页面打开再刷新可以成功，每次都必须这样才能刷新；（2）BeyondHD站点，无论如何操作均无法识别到信息，提示“未登录”，实际已登录，点到各个子页面也是仍旧无法识别。

尝试：三台设备都完整删除插件重新安装再重新添加这两个站点，故障仍旧。停用别的插件，故障仍旧。

- 相关截图：
不好意思，我不知道这里怎么上传截图，不太会用。

- 重现步骤：

**Comment by mitlearn** [comment]
>  （1）HDSky站点刷新失败，必须先进入站点再进入个人页面保持页面打开再刷新可以成功，每次都必须这样才能刷新；
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1286
>  （2）BeyondHD站点，无论如何操作均无法识别到信息，提示“未登录”，实际已登录，点到各个子页面也是仍旧无法识别。
使用crx/zip方式更新PTPP

**Comment by ted423** [comment]
版本不正确，请更新action的或者pre-release的版本

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/discussions/1200#discussioncomment-4377703
