### ISSUE TITLE
可以提供API数据接口吗，比如将搜索结果能用API调用

### ISSUE THREAD

**Issue by JishuLiu6** [pt-plugins/PT-Plugin-Plus#1370]
## 您的功能请求是否与问题有关？ 请描述一下。

可以提供API数据接口吗，比如将搜索结果能用API调用

**Comment by ted423** [comment]
@JishuLiu6 虽然没太理解，但是我认为浏览器扩展不太适合做这个

**Comment by Rhilip** [comment]
插件无法作为浏览器容器向外提供API接口。如果要api可以尝试 Jackett

我们准备中的Next版本将站点解析的部分拆分成monorepo，但这不会是我们之后的开发重点，
希望后续能有其他人基于此开发对应api。
