### ISSUE TITLE
辅种验证可以忽略文件顺序错误

### ISSUE THREAD

**Issue by tedzhu** [pt-plugins/PT-Plugin-Plus#1373]
种子文件中文件顺序并不影响下载文件夹的目录结构。经测试，两个文件集合相同但顺序不同的种子文件，可以经过hash check后正常seed  (qBittorrent 4.5.2)

建议辅种时验证名称、长度、及文件列表内容是否相同，但忽略文件顺序不同:)

**Comment by ted423** [comment]
@tedzhu 这个验证与顺序无关，一般重新做种就过不了

**Comment by ted423** [comment]
这个验证只是基础的参考。

**Comment by fzlins** [comment]
文件顺序不同和缺少文件，都已经有提示了。你可以自行判断是否添加到辅种中。
