### ISSUE TITLE
MTV入站时间识别不准确

### ISSUE THREAD

**Issue by LoneFireBlossom** [pt-plugins/PT-Plugin-Plus#1377]
- PT 助手版本: © 栽培者 2023, 版本 v1.6.1.2056 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 版本 110.0.5481.177（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

如图所示 这个入站时间不对
（搞得我都不敢PTPP截图了 一截图显示P龄23年。。。）

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/50087596/226921975-5739c3f4-18af-4e21-b593-1c1e832e8a97.png">

- 相关截图：

- 重现步骤：

**Comment by fzlins** [comment]
我这里没有问题，你用界面是什么语言？

**Comment by LoneFireBlossom** [comment]
mtv的界面吗？就是英语

**Comment by fzlins** [comment]
> * 相关截图：
> * 重现步骤：

我这里无法重现，显示是正确的。试试清理一下缓存。
