### ISSUE TITLE
聆音做种体积和做种数无法正确显示

### ISSUE THREAD

**Issue by lemontree9223** [pt-plugins/PT-Plugin-Plus#1378]
- PT 助手版本: v1.6.1.2050
- PT 助手安装方式：crx
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：不能
- 问题描述：

聆音做种体积为4.490 TB，PTPP显示为0

- 相关截图：
https://i.328888.xyz/2023/03/23/qQCvN.jpeg
https://i.328888.xyz/2023/03/23/q1M8v.jpeg

- 重现步骤：

**Comment by ted423** [comment]
请问站名打对了么

**Comment by lemontree9223** [comment]
> 请问站名打对了么

soulvoice, 聆音。抱歉打错了。

**Comment by shinobualice** [comment]
这站应该也是之前炸过一次修好了之后就显示不了数据了

**Comment by Guanghan1010** [comment]
> 这站应该也是之前炸过一次修好了之后就显示不了数据了

有计划修复吗？
