### ISSUE TITLE
ptpp图表一栏安装以后没数据其他都正常

### ISSUE THREAD

**Issue by hanyingjie65656** [pt-plugins/PT-Plugin-Plus#1380]
[](url)
![iShot_2023-03-26_21 20 54](https://user-images.githubusercontent.com/109706159/227778458-0fed1637-c668-400e-af0a-5a93e7e02a8d.jpg)

**Comment by ted423** [comment]
用了几天？

**Comment by hanyingjie65656** [comment]
您好。非常感谢您的回复，昨天安装的 今天发现已经正常了  非常感谢！！ 只是以前的数据 都找不到嘞，我原来edge是旧版本，我为了支持朱雀，所以下载安装了新版本，结果发现以前的数据都丢失了。

**Comment by ted423** [comment]
@hanyingjie65656 这种扩展id不一样，可以之前的导出，然后在github的版本里导入
