### ISSUE TITLE
猫站游戏区搜索结果显示错误

### ISSUE THREAD

**Issue by Edelweissghr** [pt-plugins/PT-Plugin-Plus#1387]
- PT 助手版本:v1.6.0.ba3d87e
- PT 助手安装方式：（市场安装，或zip包安装）release
- 浏览器名称及版本：edge111.0.1661.62
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：未尝试
- 问题描述：搜索“渔帆暗涌”时，猫站的种子标题有误（与种子页面不符），为单个数字，且分区显示音乐区（应该为游戏区）

- 相关截图：https://imgbox.com/Bj00flKu

- 重现步骤：

**Comment by fzlins** [comment]
#1266
