### ISSUE TITLE
辅种过程无法下载种子验证

### ISSUE THREAD

**Issue by mr-roxe** [pt-plugins/PT-Plugin-Plus#1388]
- PT 助手版本:1.6.1.2061
- PT 助手安装方式：crx下载安装
- 浏览器名称及版本：360极速X，版本21.0.1200.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：
RT，辅种过程无法下载种子验证，不管是基准文件还是辅种文件，都是下载失败；单独推送种子到下载器，提示无效种子文件。

- 相关截图：
<img src="https://www.hualigs.cn/image/642e43d15ef2a.jpg"/>
<img src="https://www.hualigs.cn/image/642e45902befb.jpg"/>

- 重现步骤：
正常搜索出结果，打开多选，多选中自认为相同的资源，点击操作栏的辅种按钮，出现截图样子

**Comment by ted423** [comment]
建议先看常见问题
基准种下不下来肯定会报错
