### ISSUE TITLE
在搜索结果中中不能正常显示Pttime的做种，但是其他的几个站点可以

### ISSUE THREAD

**Issue by Randolph87cb** [pt-plugins/PT-Plugin-Plus#1404]
- PT 助手版本: v1.6.1.2063
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 版本 111.0.5563.146（正式版本） (x86_64)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
在搜索结果中中不能正常显示Pttime的做种，但是其他的几个站点可以

- 相关截图：
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/20552978/234474361-a6ce9767-607d-4d7b-ba44-cb36501c3dbc.png">

- 重现步骤：

**Comment by ted423** [comment]
并不是所有站都能显示做种状态，取决于网站是否提供
