### ISSUE TITLE
btschool无法拖拽添加或一键添加种子

### ISSUE THREAD

**Issue by colincat2018** [pt-plugins/PT-Plugin-Plus#1410]
- PT 助手版本:版本 v1.6.0.ba3d87e
- PT 助手安装方式：市场安装
- 浏览器名称及版本：edge 112.0.1722.64 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：无法拖拽或一键添加种子

- 相关截图：
![image](https://user-images.githubusercontent.com/35521556/235823138-639d6685-f2a8-40c6-888e-174909c7986c.png)

- 重现步骤：
从种子列表随意拖拽一个到工具栏中第一个按钮上，或者第三个（下载到）按钮上，要么是不显示发送成功（我查过了，的确没有发送），要么是红色消息提示种子无效。

**Comment by ted423** [comment]
看常见问题，测试没有问题
