### ISSUE TITLE
软件搜索后推送链接可以默认不加https=1吗

### ISSUE THREAD

**Issue by cng10001** [pt-plugins/PT-Plugin-Plus#1411]
## 您的功能请求是否与问题有关？ 请描述一下。
现在推送到下载器的链接默认是加https=1的参数的，但是有的站点tracker只支持http
我找了一圈目前软件好像没有这个设置，请大佬们考虑下

**Comment by ted423** [comment]
@cng10001 你要提供站点名，个人认为，现在不提供https不太正规

**Comment by cng10001** [comment]
> @cng10001 你要提供站点名，个人认为，现在不提供https不太正规

我手头上有2个，一个是springsunday，一个是lemonhd，下载网页上提供的torrent，添加到下载器看tracker是http，拜托大佬也看看

**Comment by ted423** [comment]
NP本身支持选择tracker是否带https。
柠檬支持tracker https
