### ISSUE TITLE
请求修复hdviedo升级公式

### ISSUE THREAD

**Issue by coracoo** [pt-plugins/PT-Plugin-Plus#1412]
- PT 助手版本:v1.6.1.2063
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述： hdvideo更改了用户升级公式，一直未更新，请求对该站点升级公式进行更新，具体升级内容详见
<html>
<body>

Peasant |   | 当以下情况时将被自动降至本级：1.如果你已经下载了超过50GB，你应该有大于0.4的分享率。2.如果你已经下载了超过100GB，你应该有大于0.5的分享率。3.如果你已经下载了超过200GB，你应该有大于0.6的分享率。4.如果你已经下载了超过400GB，你应该有大于0.7的分享率。5.如果你已经下载了超过800GB，你应该有大于0.8的分享率。Peasant如果在30天内仍未改善分享率，将被禁用。
-- | -- | --
Power User |   | 必须注册至少4周，并且下载至少128G，分享率大于2.0，做种积分大于60480积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于1.9，你将自动降级。
Elite User |   | 必须注册至少8周，并且下载至少256G，分享率大于2.5，做种积分大于137088积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.4，你将自动降级。
Crazy User |   | 必须注册至少12周，并且下载至少512G，分享率大于3.0，做种积分大于262080积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.9，你将自动降级。
Insane User |   | 必须注册至少18周，并且下载至少1TB，分享率大于3.5，做种积分大于453600积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.4，你将自动降级。
Veteran User |   | 必须注册至少24周，并且下载至少2TB，分享率大于4.0，做种积分大于604800积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.9，你将自动降级。
Extreme User |   | 必须注册至少32周，并且下载至少4TB，分享率大于4.5，做种积分大于806400积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于4.4，你将自动降级。
Ultimate User |   | 必须注册至少40周，并且下载至少6TB，分享率大于5.0，做种积分大于1008000积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于4.9，你将自动降级。
Nexus Master |   | 必须注册至少52周，并且下载至少8TB，分享率大于5.5，做种积分大于1310400积分。当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于5.4，你将自动降级

</body>
</html>

- 相关截图：
![image](https://user-images.githubusercontent.com/120569020/236103977-f707a0b4-6ef0-4875-93e4-b5e7a243ca5b.png)

- 重现步骤：

**Comment by ted423** [comment]
区别是在哪？可以参照别人写的改一下
