### ISSUE TITLE
新站点请求：打胶

### ISSUE THREAD

**Issue by coracoo** [pt-plugins/PT-Plugin-Plus#1413]
- 站点名称：打胶
- 站点地址：https://dajiao.cyou/
- 站点描述：一个包含影视、动漫、电子书、音乐、有声书的综合性站点。

- 资源类型：影视、电子书、有声书、音乐、动漫
- 开放注册：否
- 是否连坐：否
- 站点规则：无

**Comment by ted423** [comment]
请提供更详细的信息

**Comment by ted423** [comment]
不接受开站6个月以内的站点请求
