### ISSUE TITLE
北邮人搜索结果获取不到种子大小等信息

### ISSUE THREAD

**Issue by Mark-Imaginist** [pt-plugins/PT-Plugin-Plus#1417]
- PT 助手版本: v1.6.1.2081
- PT 助手安装方式：crx
- 浏览器名称及版本：Edge 113.0.1774.35
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：北邮人搜索结果获取不到种子大小、上传、下载、完成数和发布时间

- 相关截图：
![chrome-extension___dmmjlmbkigbgpnjfiimhlnbnmppjhpea_index html](https://user-images.githubusercontent.com/38615702/236603291-a5af297e-6b56-4848-99e0-102a2b47ff82.png)
- 重现步骤：使用关键词或 IMDb 编号搜索

**Comment by Ownsky** [comment]
问下是怎么解决的呢？

**Comment by Mark-Imaginist** [comment]
> 问下是怎么解决的呢？

最新版已经修复了，在 Actions 下载

**Comment by ted423** [comment]
@Mark-Imaginist 目前还是建议用pre-release的
