### ISSUE TITLE
关于搜索种子frds站点部分信息无法更新的反馈

### ISSUE THREAD

**Issue by fqh1995** [pt-plugins/PT-Plugin-Plus#1419]
- PT 助手版本: 栽培者 2023, 版本 v1.5.2.f2e4f20 zip
- PT 助手安装方式：zip安装（含毕业信息等）
- 浏览器名称及版本：Microsoft Edge版本 112.0.1722.68 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：搜索种子，Frds pt朋友站点没有具体发布日期，种子大小及做种人数

- 相关截图：
![Snipaste_2023-05-08_15-03-21](https://user-images.githubusercontent.com/31031100/236758873-01dee3fa-ad3b-4128-b294-7b4e35c52de0.jpg)

- 重现步骤：

**Comment by ted423** [comment]
更新版本。。。。。。。。。。。。。。
