### ISSUE TITLE
插件侧边栏按钮文字无法正常显示

### ISSUE THREAD

**Issue by zololucky** [pt-plugins/PT-Plugin-Plus#1420]
- PT 助手版本: v1.6.0.ba3d87e
- PT 助手安装方式：zip
- 浏览器名称及版本：Chrome 112.0.5615.137
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
插件侧边栏按钮文字无法正常显示

- 相关截图：
<img width="199" alt="CleanShot 2023-05-08 at 17 57 50" src="https://user-images.githubusercontent.com/8132278/236782822-22dda6b3-29f4-4d9c-98d1-0fad0758e336.png">

**Comment by ted423** [comment]
先更新到最新版本，建议用crx

**Comment by zololucky** [comment]
> 先更新到最新版本，建议用crx

我在Edge 浏览器用 MS Edge Addons 方式安装，但是侧边栏依然无法显示正常的文字。

**Comment by ted423** [comment]
@zololucky 用最新的action版本

**Comment by zololucky** [comment]
@ted423 
你好，我试了最新的action版本，但问题依旧存在。
我还尝试了 Chromium 安装v1.6.0和最新action版本，结果也是一样。

另外，我在使用zip安装时，Extensions会出现一些错误，不知是否与此问题相关。
谢谢你的帮助，抱歉给你们添麻烦了。

<img width="697" alt="CleanShot 2023-05-09 at 02 38 38" src="https://user-images.githubusercontent.com/8132278/236894023-17f19e9b-ffd2-4bd9-970b-b67cf4ff265c.png">
