### ISSUE TITLE
杏林能获取到站点，但是一直要登录获取不到上传下载信息

### ISSUE THREAD

**Issue by submarine111** [pt-plugins/PT-Plugin-Plus#1424]
；
- PT 助手版本: © 栽培者 2023, 版本 v1.6.0.ba3d87e 
- PT 助手安装方式：市场安装
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
杏林能获取到站点，但是一直要登录获取不到上传下载信息，一直提示要登录。
估计是默认的地址为xinglin，但是五一后重新变成了xingtan，但是没有换过来。

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/62420502/a20d3694-f3c9-4eff-bb70-3633a792cbf2)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/62420502/146fc1b4-a7f2-404a-b0ec-a04d60d133b3)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/62420502/fd133932-94c4-4105-bf20-668f685e6cc0)

- 重现步骤：

**Comment by ted423** [comment]
版本不对，请更action版本
