### ISSUE TITLE
能否变为IOS的app使用

### ISSUE THREAD

**Issue by Whichbfj28** [pt-plugins/PT-Plugin-Plus#1431]
## 您的功能请求是否与问题有关？ 请描述一下。
能否变为IOS的app使用

## 描述你想要的解决方案
能否变为IOS的app使用

## 描述您考虑过的替代方案
能否变为IOS的app使用

## 其他附加信息
能否变为IOS的app使用

**Comment by ted423** [comment]
@Whichbfj28 不能，代码完全不一样
