### ISSUE TITLE
坚果云备份失败

### ISSUE THREAD

**Issue by Mr-Roxe** [pt-plugins/PT-Plugin-Plus#1440]
- PT 助手版本: v1.6.1.2085
- PT 助手安装方式：github下载crx拖拽安装
- 浏览器名称及版本：360极速X Ver.21.0.1200.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
参数备份与恢复，无法使用坚果云备份，暂不知其它webdav服务器是否可用

- 相关截图：
![](https://www.hualigs.cn/image/646f3defeeb29.jpg)
![](https://s2.xptou.com/2023/05/25/646f3e6f138a7.png)

- 重现步骤：
首先添加备份服务器，选择wevdav，填写好认证参数，点击测试服务器是否可连接，提示服务器可连接，下图：
![](https://www.hualigs.cn/image/646f3defeeb29.jpg)

然后点击备份到服务器按钮，提示备份参数错误，下图：
![](https://s2.xptou.com/2023/05/25/646f3e6f138a7.png)

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/976
