### ISSUE TITLE
HUNO入站时间或许应该显示为N/A

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#1442]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 搜素过Issue，确认没有相关问题。
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by fzlins** [comment]
f0880ee
