### ISSUE TITLE
对搜索字符串进行一次trim()？

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#1444]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 搜素过Issue，确认没有相关问题。
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

对搜索字符串进行一次trim()？
```	Pontypool 2008```
有时候复制时会带进一些特殊的字符，例如朱雀不能正确返回结果

**Comment by Rhilip** [comment]
用 `v-model.trim` 来处理会不会好些？
