### ISSUE TITLE
希望增加不同站点手动设置限速功能

### ISSUE THREAD

**Issue by mylovesaber** [pt-plugins/PT-Plugin-Plus#145]
一直用flexget，比如馒头非vip在flexget里面设置上传速度限制11.5m/s，每次flexget传给deluge的时候会自动 给种子添加这个上传速度限制，但有些时期有的站rss被管理禁用或者有的机器并没有装flexget，使用ptpp时必须每次添加种子后立马去给对应种子设置上传最高速度，实在是有些麻烦，不知道老哥是否有可能在未来添加该功能？

比如在ptpp的站点设置里面每个站点信息里面添加一个上传限速的手动填写功能？

**Comment by Rhilip** [comment]
各个客户端对限速功能的支持不一致，我翻了下flexget的代码实现
https://github.com/Flexget/Flexget/tree/develop/flexget/plugins/clients

deluge、transmission 他的动作其实是在种子添加后对种子属性进行设置。
rtorrent 不支持具体数值限速，仅支持分组（在分组内设置限速等信息）
utorrent flexget不支持，也没看到官方文档在添加种子时有限速说明，估摸着也要添加后编辑。

该功能可能不会实现，或者可能会延后实现。毕竟不算是很急迫的功能。也可以采用软件设置默认限速的形式，flexget添加时候覆盖的形式绕过；或者添加时就设置种子为暂停状态。

**Comment by mylovesaber** [comment]
一般都是deluge，qbittorrent和transmission这三个配合flexget使用的，支持都良好；

rtorrent有自带的抓种工具一般不用flexget无需对它支持；

utorrent这个用linux的基本没见过使用的，除了少数盒子商家做了单独优化私家使用，一般也用不上flexget；

flexget用于rss，在rss不能使用的情况下手动下载上传设置种子信息方面比ptpp麻烦了很多。

还是感谢老哥写了这么个好插件哈
