### ISSUE TITLE
更新edge官方商店扩展

### ISSUE THREAD

**Issue by HaibaraMegumi** [pt-plugins/PT-Plugin-Plus#1452]
## 您的功能请求是否与问题有关？ 请描述一下。

edge商店的版本还是去年的，请更新edge官方商店扩展

**Comment by Rhilip** [comment]
- 维护组目前不持有原edge商店发布账号（原发布账号为ronggang个人号）
- 同时由于商店不再允许上传manifest v2的插件，我们也不可能以新账号发布插件
- 维护组接手后的说明中就说了，不再尝试向chrome商店、edge商店提交插件
