### ISSUE TITLE
[M-Team]没有定位到种子列表，或没有相关的种子

### ISSUE THREAD

**Issue by prajna0** [pt-plugins/PT-Plugin-Plus#1457]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 搜素过Issue，确认没有相关问题。
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2105
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome 114.0.5735.134 (正式版本) (64 位)
- 浏览器是否安装了其他插件：Proxy SwitchyOmega、uBlock Origin、TamperMonkey
- 停用其他插件后是否正常工作：否
- 问题描述：**[M-Team]没有定位到种子列表，或没有相关的种子** 偶尔一直点刷新按钮可以搜索到馒头的资源，但大部分时候会搜不到

- 相关截图：

- 重现步骤：**正常在豆瓣电影页面点击用 PT 助手搜索或者手动输入 IMDb 号**

Log File: 
[PT-Plugin-Plus-System-Logs.zip](https://github.com/pt-plugins/PT-Plugin-Plus/files/11741978/PT-Plugin-Plus-System-Logs.zip)

**Comment by ted423** [comment]
这种基本是网络问题

**Comment by ted423** [comment]
这种基本是网络问题

**Comment by ted423** [comment]
刷不出来的时候点下连接打开看看，显示是什么。

**Comment by prajna0** [comment]
> 这种基本是网络问题

https://kp.m-team.cc 站点以及 Cloudflare CDN 我都设置了Proxy 规则，走的香港 IEPL 节点

**Comment by ted423** [comment]
确定点链接能正常打开，并且没有cookies或者重定向的问题

**Comment by hurui79** [comment]
> 确定点链接能正常打开，并且没有cookies或者重定向的问题

我也出现了一样的问题，网站可以正常打开。。

**Comment by ted423** [comment]
部分情况下，导入设置导入cookies可能会导致扩展里出现重定向，有时候清下cookies就可以了
