### ISSUE TITLE
能否给下载服务器增加一个开关功能

### ISSUE THREAD

**Issue by dfbb9216** [pt-plugins/PT-Plugin-Plus#1458]
目前有三个客户端，1个UT 2个QB。UT的功能逐渐满足不了，需要改用3QB。
希望可以在下载服务器页面里增加一个每个服务器开关功能，常用的开启，不常用的需要时候开启，避免多客户端产生误操作.
感谢
附效果图
![QQ截图20230615162345](https://github.com/pt-plugins/PT-Plugin-Plus/assets/64184911/4b57a56d-736d-48d2-a4b4-3ffa865900ae)

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/974

**Comment by ted423** [comment]
@dfbb9216 难度可能没有，可能都在等next。还有摸鱼
