### ISSUE TITLE
右键磁力链接添加到DownloadStation的时候提示undefined错误

### ISSUE THREAD

**Issue by ss1969** [pt-plugins/PT-Plugin-Plus#1478]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 搜素过Issue，确认没有相关问题。
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:  栽培者 2023, 版本 v1.6.0.ba3d87e
- PT 助手安装方式：市场安装、
- 浏览器名称及版本：Edge 版本 114.0.1823.58 (正式版本) (64 位)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：MioBt的磁力链接，右键点击添加到DownloadStation的时候，右下角出现红色“undefined”标签后失败
DS服务器确定可用，种子页面添加下载正常

- 相关截图：无

- 重现步骤：见问题描述

**Comment by ted423** [comment]
你的版本不对，先更新
