### ISSUE TITLE
https://www.hdarea.co/ 高清世界已于7月16日更改域名  https://hdarea.club/

### ISSUE THREAD

**Issue by submarine111** [pt-plugins/PT-Plugin-Plus#1490]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:栽培者 2023, 版本 v1.6.1.2266
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
https://www.hdarea.co/ 高清世界已于7月16日更改域名  https://hdarea.club/

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
我才发现搜索的索写错了，那我提示一下，那个词是搜索。能仔细读下那行是啥🐴
