### ISSUE TITLE
byr新版本适配

### ISSUE THREAD

**Issue by RUANRUI1995** [pt-plugins/PT-Plugin-Plus#1502]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2298
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Edge 115
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
byr后端升级，变化较大，无法获取个人数据

- 相关截图：

- 重现步骤：

**Comment by hirrao** [comment]
chrome v1.6.1.2276 ZIP安装，仍旧正常可以获取数据

**Comment by RUANRUI1995** [comment]
v1.6.1.2298又可以了，没有升级版本

**Comment by ted423** [comment]
那有可能是网络问题
