### ISSUE TITLE
地址栏搜索不起作用

### ISSUE THREAD

**Issue by HaodongZou** [pt-plugins/PT-Plugin-Plus#1505]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2295
- PT 助手安装方式：（市场安装，或zip包安装） GitHub action 下载crx 安装
- 浏览器名称及版本：Chrome 115.0.5790.102（正式版本） (arm64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

**chrome 地址栏输入 pt + 空格/TAB 可以进入PTPP 搜索栏。但是输入任何除空格外字符都会变成普通搜索，并不能调用 PTPP 进行搜索。**

- 相关截图：

https://github.com/pt-plugins/PT-Plugin-Plus/assets/38043100/7af928d4-24a8-4658-bddd-07bd7331feea

- 重现步骤：

1. 在 chrome 地址栏输入“pt”
2. 输入空格或按下 Tab
3. 输入查询词
4. PTPP 搜索引擎消失，变成默认的搜索引擎

**Comment by IITII** [comment]
* 最新版未复现该问题。请升级后禁用所有除了PTPP以外的插件和任何输入增强工具再次重试。如 罗技的Ghub，Karabiner 等

**Comment by ted423** [comment]
有可能是mac或者chrome的锅
