### ISSUE TITLE
永v好像没法正确显示升级条件的状态

### ISSUE THREAD

**Issue by zhuerhao** [pt-plugins/PT-Plugin-Plus#1506]
馒头永v好像没法正确显示升级条件的状态，不过倒也不影响使用，只是看着难受
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/127954109/3ea09df5-6ede-4f23-a231-3c4a4ec365f0)

**Comment by IITII** [comment]
管理和永V应该不需要升级。可以过滤一下.
像那种管理手动改的用户等级，应该保持现有计算方式就行。

**Comment by IITII** [comment]
1. 将 VIP 等级下面的升级条件去掉了。
2. hover 框保持不变，因为更多的是体现一个 “是否满足该等级要求” 的概念
