### ISSUE TITLE
qbittorrent 4.1.9.1 下载服务器导入下载默认暂停

### ISSUE THREAD

**Issue by aiyce** [pt-plugins/PT-Plugin-Plus#1507]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.0
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome最新版
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：
使用下载到服务器功能导入qbittorrent，qbittorrent中种子默认是暂停状态

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/19799164/563aa087-d16b-465c-a998-b263b4c22cde)

- 重现步骤：
[{"event":"init","id":"","module":"background","time":1690591433929},{"data":{"code":403,"msg":"未知错误","status":"error"},"event":"service.controller.doDownload.error","id":"","module":"background","msg":"下载服务器qBittorrent处理[addTorrentFromURL]命令失败！","time":1690592164872},{"event":"Options.readConfig","id":"","module":"options","msg":"开始加载配置信息","time":1690592183242},{"event":"Options.readConfig.Finished","id":"0c89d6b2dbdb2133eaefe2d01cac9e0d","module":"options","msg":"配置加载完成","time":1690592183292},{"data":{"data":{"code":403,"status":"error"},"success":false,"type":"error"},"event":"testClientConnectivity","id":"","module":"background","msg":"测试客户连接失败[http:&#x2F;&#x2F;192.168.&#x2F;]","time":1690592259529},{"data":{"0":"O","1":"k","2":".","msg":"URL已添加至 qBittorrent 。","status":"success"},"event":"service.controller.doDownload.finished","id":"","module":"background","msg":"下载服务器qBittorrent处理[addTorrentFromURL]命令完成","time":1690592362109},{"event":"Options.readConfig","id":"","module":"options","msg":"开始加载配置信息","time":1690592592417},{"event":"Options.readConfig.Finished","id":"","module":"options","msg":"配置加载完成","time":1690592592467},{"data":{"0":"O","1":"k","2":".","msg":"URL已添加至 qBittorrent 。","status":"success"},"event":"service.controller.doDownload.finished","id":"","module":"background","msg":"下载服务器qBittorrent处理[addTorrentFromURL]命令完成","time":1690592666567},{"data":{"0":"O","1":"k","2":".","msg":"URL已添加至 qBittorrent 。","status":"success"},"event":"service.controller.doDownload.finished","id":"","module":"background","msg":"下载服务器qBittorrent处理[addTorrentFromURL]命令完成","time":1690592672260},{"event":"Options.readConfig","id":"","module":"options","msg":"开始加载配置信息","time":1690592681404},{"event":"Options.readConfig.Finished","id":"","module":"options","msg":"配置加载完成","time":1690592681441}]

**Comment by ted423** [comment]
请好好看下ptpp里下载器的设置项
