### ISSUE TITLE
根据下载目录在下载器（例如qb）内自动添加分类

### ISSUE THREAD

**Issue by verity886** [pt-plugins/PT-Plugin-Plus#1518]
## 您的功能请求是否与问题有关？ 请描述一下。

在站点种子详情页选择下载目录一键下载时，自动为下载的种子任务添加分类

## 描述你想要的解决方案

在站点种子详情页选择下载目录一键下载时，自动为下载的种子任务添加分类

## 描述您考虑过的替代方案

在站点种子详情页选择下载目录一键下载时，自动为下载的种子任务添加分类

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/77
