### ISSUE TITLE
憨憨HHanClub站点UI整改后，PTPP不能搜索

### ISSUE THREAD

**Issue by zhangfan1231** [pt-plugins/PT-Plugin-Plus#1529]
## 您的功能请求是否与问题有关？ 请描述一下。

HHanClub站点UI整改，PTPP无法搜索种子。（新UI貌似还是NP的架构）

## 描述你想要的解决方案

适配HHanClub新站点。

**Comment by ted423** [comment]
@zhangfan1231 理论来说UI和架构算两个概念.

**Comment by IITII** [comment]
@zhangfan1231 建议把不能用的地方, 都截图发出来

**Comment by ngtrio** [comment]
+1，个人数据也为空
<img width="1584" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/26735402/5e5c6c64-e71b-41b5-92eb-6e15aa6a6ef7">

**Comment by submarine111** [comment]
对的，只有种子数。

**Comment by vampirefu** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/28091936/40b1309f-e380-4683-af47-493347503cf9)
目前做种体积数据还是不能显示

**Comment by t282502324** [comment]
再次反馈一下，做种体积和搜索都可以正常显示了。但是做种积分好像还不能显示，这导致用户等级进度部分有问题
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/143067998/ace6677a-054e-498e-baf3-cc7b1b584e2f)

**Comment by zhangqingxi** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/23466699/824a11d5-630a-49d5-a6b7-8b8577195b31)

{
    "id": "15599",
    "name": "xxxx",
    "isLogged": true,
    "messageCount": 0,
    "uploaded": 0,
    "downloaded": 0,
    "bonus": null,
    "joinTime": "",
    "lastUpdateStatus": "success",
    "lastUpdateTime": 1693289614250,
    "seeding": "223",
    "seedingSize": 0,
    "uploads": null
}
修复了，是需要怎么操作吗，我这个憨憨 只能获取做种数

**Comment by dfrthrtyere** [comment]
<img width="1606" alt="捕获" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/131387597/b7032685-a3cd-473c-867c-af5a433b01fd">

显示不出来啊

**Comment by zhangqingxi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
