### ISSUE TITLE
搜索方案 猪猪大量重复 searchEntry

### ISSUE THREAD

**Issue by IITII** [pt-plugins/PT-Plugin-Plus#1535]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2316
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
编辑搜索方案的时候 大量重复 searchEntry

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/bc9d3f14-9db2-473d-ba61-5f667c3f75a8)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/e27544ab-6d93-4e16-b115-6807b79ee06e)

- 重现步骤：

**Comment by IITII** [comment]
解决方案： 删除重新添加猪猪.

**Comment by zpy0577** [comment]
我也是这个问题，目前版本是1.6.1.2436，其实往前好多版本就开始有这个问题，目前是每打开一次浏览器，这个“全站搜索”就会多出来一个，然后慢慢累积，越来越多，当累积过多时（最多时几十个），导致猪猪搜索时会卡很长时间，甚至内存占用飙升，可能重复搜索了很多次。删除站点重新添加过，清除过cookies，还是会出现，目前只能全站搜索的时候排除猪猪，希望大佬们帮忙解决下
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/114006452/94bfcbf5-1d03-4a71-b581-a9f56c59846f)

**Comment by IITII** [comment]
`每打开一次浏览器`: 你这是是指每次重新启动浏览器?/冷启动浏览器? 我浏览器从来不关, 问题没那么明显
搜索方案里面勾一个试试, 多勾了会重复搜索 (虽然结果一样, 但是时间变长了

**Comment by zpy0577** [comment]
> `每打开一次浏览器`: 你这是是指每次重新启动浏览器?/冷启动浏览器? 我浏览器从来不关, 问题没那么明显 搜索方案里面勾一个试试, 多勾了会重复搜索 (虽然结果一样, 但是时间变长了

是指右上角整个关掉浏览器后再打开，因为我笔记本每天都会关，现在是每打开一次浏览器，这个“全站搜索”就会多一个出来，这是今天的，你看又多了一个，而且就算之前的取消了勾选，新的也会自动勾选
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/114006452/c24bbd59-4c59-44f1-966a-fd804d7cfc18)
等累计到几十个的时候，搜索就会变得非常慢，每次都要去掉勾选太麻烦了，而且还会不断增加新的，麻烦帮忙看看这是什么BUG，能修正不？

**Comment by ted423** [comment]
那个 iscustom和 valid是个啥..

**Comment by ted423** [comment]
我拿掉了试试，不过目测可能还是得删了重加。猜测可能每次读到'isCustom'都去添加了一次自定义，但这种模板肯定不能算自定义

**Comment by IITII** [comment]
我发现 2xfree 里面也有 isCustom, 不过只在 plugins 里面有, searchEntry 里面没有. 且并没有出现pig 的这种情况. 所以是 searchEntry 里面的 isCustom 字段的原因?...

**Comment by ted423** [comment]
可能是哪个弄错了加的吧，说不定是同一个人pr的，这俩站我都没，不太好验证

**Comment by IITII** [comment]
2xfree 是我加的...可能是看着 pig 改的. 不过 2xfree 没有这个问题. 可能只是因为 searchEntry 里面没有  isCustom 字段?
