### ISSUE TITLE
能不能添加设置UI背景为暗黑 或者黑色主题。OLED显示器 翻看这纯白的UI界面 都想带墨镜了。

### ISSUE THREAD

**Issue by voodooTTC** [pt-plugins/PT-Plugin-Plus#1540]

**Comment by liustatail** [comment]
反转颜色试试 
<img width="606" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/142783146/7b77ec77-d9b5-44c5-9f7c-b1143cf25205">

**Comment by voodooTTC** [comment]
> 反转颜色试试 <img alt="image" width="606" src="https://user-images.githubusercontent.com/142783146/261956055-7b77ec77-d9b5-44c5-9f7c-b1143cf25205.png">

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/126654837/f86e8d3c-d473-491e-bb32-5a947383411e)
为啥我没有这个选项？

**Comment by voodooTTC** [comment]
好吧~才想起 原版已经停止更新。用了其他161的版本有反转颜色了。基本上解决了白色太亮。要是有优化的暗黑主题更美观就更好了。谢谢你的回答。
