### ISSUE TITLE
功能刷新我的数据添加重试失败数据功能

### ISSUE THREAD

**Issue by imdong** [pt-plugins/PT-Plugin-Plus#1541]
## 您的功能请求是否与问题有关？ 请描述一下。

为「刷新我的数据」失败的记录在 N 分钟内 重试或只更新失败的数据等操作。

## 描述你想要的解决方案

在「常规设置」页面添加开关“10分钟内只刷新失败数据”选项（或“10分钟内站点数据不重复更新”）
开启后，如果点击「我的数据」页面的「刷新我的数据」时，只对列表中“数据更新于”10分钟以上的，“状态”为“失败”等状态的，进行更新操作。

## 描述您考虑过的替代方案

按钮“刷新我的数据”旁边添加“批量重试”按钮。

**Comment by imdong** [comment]
谢谢，我是知道点击左侧列表是可以针对某个站点单独手动刷新的。

但是对于站点多的收割机来说，每次刷新的时候都会有多个站点失败。

挨个手动点不如批量重试来的方便些。

**Comment by imdong** [comment]
这个失败重试不是自动刷新的重试嘛？

🤫难道手动刷新数据失败时也会重试？

我去试试哈。

**Comment by ted423** [comment]
我觉得加个类似搜索中重试失败站点类似的按钮就好，点一下批量刷新。有些需要登陆的登陆过后批量刷一次

**Comment by IITII** [comment]
~~按钮页面挤不下了~~ 你用分组功能, 分组里面可以选择异常分组

<img width="486" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/bfe11f4f-8f7f-4073-81f8-bd04fa1d7487">
