### ISSUE TITLE
希望下载路径中 imdbid 可以作为一个变量

### ISSUE THREAD

**Issue by link2fun** [pt-plugins/PT-Plugin-Plus#1547]
## 您的功能请求是否与问题有关？ 请描述一下。

自动化工具可以读取 路径中的 imdbid 来达到精准搜刮的效果
现在只能将 imdbid 放到tag中, 想能把 imdbid 放到保存路径模板中
现有的通过文件名识别 可能造成误识别

**Comment by IITII** [comment]
* **感觉没必要**

> 一般文件命名规范的话, nastool 都能正常刮削. 而且 nastool 不读最外层的 tmdb 目录吧?  

```
❯ tree tmdb_id
tmdb_id
└── movie_1
    └── movie.mkv
```

补充下相关截图, 以及 `自动化工具` 的名称

**Comment by yanxiehui5692dkp** [comment]
> * **感觉没必要**
> 
> > 一般文件命名规范的话, nastool 都能正常刮削. 而且 nastool 不读最外层的 tmdb 目录吧?
> 
> ```
> ❯ tree tmdb_id
> tmdb_id
> └── movie_1
>     └── movie.mkv
> ```
> 
> 补充下相关截图, 以及 `自动化工具` 的名称

不读是因为历史没有, 如果有的话不就可以读么
我自己魔改了 nastool 可以读路径中的 tmdbid 
现在用的是 国外的 filebot 有 imdbid 的情况下 识别飞快

btw, imdb 可以通过 tmdb api 转成 tmdbid 的, 如果设为上级目录名的话, emby plex 可以直接识别 甚至不用二次搜刮

**Comment by yanxiehui5692dkp** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/141860095/3bd04b5b-2fd4-4649-8a61-dbc5f455858d)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/141860095/e6ce32c4-343c-4944-b940-63ee7a963e74)

会优先使用路径中的 tmdbid 
如上图 tmdbid 是 闪电侠 文件名是 复仇者联盟

**Comment by yanxiehui5692dkp** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/141860095/dba456ab-ea1a-4813-9343-910e9b64b5e3)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/141860095/bf377d29-db23-4708-aeb9-9c0318344031)

**Comment by Rhilip** [comment]
从我的角度，PTPP已经将imdb信息传递给了下载器（虽然是以tag的形式）。至于用户后续如何使用该信息是用户自己的事情，你可以通过qbt的运行外部程序或者定时脚本的方式进一步对tag信息进行处理。
另外，从emby等软件的角度，正确文件夹的命名形式也应该是 `moive (xxxx) [tmdbid=xxxx]` ，多套一层目录并没有任何意义。

**Comment by IITII** [comment]
@yanxiehui5692dkp 换个方向，你可以拓展下现有的 保存路径的 `变量/关键字`。

* 虽然保存路径 变量 很早就有了，但是实际上体验并不太好。我一般还是写死，然后用 qb 的分类。nastool 自动下载也支持 qb 自动分类。
* PTPP 的 tmdb id 来源是站点，并不是所有站都有这个信息。
* 其次一般文件名比较规范的 nastool 之类的都可以正常刮削。 如果文件名都不规范，大概率 tmdb信息也是没有的。
* 因为部分命名不规范，导致刮削失败。所以想使用额外的手段，比如文件夹名称去储存额外的元数据信息。都可以，但是因为 tmdb 不一定存在，如果作为变量需要保证 fallback 的值。你可以自己做个外部缓存，扫描qb的tag，刮削时优先走自己缓存。
