### ISSUE TITLE
希望种子推送下载可以添加站点的分类和标签推送到下载器

### ISSUE THREAD

**Issue by yangdong123** [pt-plugins/PT-Plugin-Plus#1564]

**Comment by IITII** [comment]
请详细说明, 同时类比相似软件并附上截图. @yangdong123

**Comment by yangdong123** [comment]
**我的功能请求是与问题有关。**

**描述我想要的解决方案**
功能需求如下:
1. 分类功能 : 分类需求设置与下载器绑定,建立不同的下载器时设置不同的分类,如(刷流分类,保种分类,电影分类,电视剧分类),
    这样就可以达到不同的分类在下载器中统一管理,并且是不同的分类种子下载到不同的路劲

2. 标签功能: 站点设置时添加自定义标签,这样推送到下载器时不同的站点有不同的标签标识,便于在下载器中管理不同站点的种子
