### ISSUE TITLE
猫站无法获取发布数

### ISSUE THREAD

**Issue by UrsaBear** [pt-plugins/PT-Plugin-Plus#1567]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2372
- PT 助手安装方式：crx和zip (下载自Action)
- 浏览器名称及版本：Microsoft Edge 116.0.1938.76
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：无法获取在猫站发布的种子数量，其他网站没有问题

- 相关截图：

![屏幕截图 2023-09-08 122049](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29115485/fffa9683-fb8f-4035-961c-2a52ab5c5692)
![屏幕截图 2023-09-08 122030](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29115485/e156cd57-280c-4b54-a6a2-9c90b8e88a17)

- 重现步骤：
开启一个没有安装任何除了ptpp以外插件的浏览器
打开猫站并成功登录
在ptpp中增加猫站
刷新个人数据
成功获取到除发布种子数之外的数据

**Comment by fzlins** [comment]
只有审核过的活种才会计算。

**Comment by UrsaBear** [comment]
> 只有审核过的活种才会计算。

理解了，谢谢解答
