### ISSUE TITLE
希望增加消息通知推送

### ISSUE THREAD

**Issue by junbluedd** [pt-plugins/PT-Plugin-Plus#1571]
## 您的功能请求是否与问题有关？ 请描述一下。

如果出现pt站点出现消息提醒、cookie失效等信息，通过推送向用户传达信息

## 描述你想要的解决方案

比如企业微信应用消息（普通微信就能用）、tg机器人（接受消息要梯子）、钉钉、飞书等方式推送
参考[https://github.com/lkeme/BiliHelper-personal/blob/master/src/Notice/Notice.php](url)

**Comment by IITII** [comment]
nastools 或者同类产品即可
