### ISSUE TITLE
搜索框选择搜索方案的站点bug,当多条超屏时无法滑动选择

### ISSUE THREAD

**Issue by yangdong123** [pt-plugins/PT-Plugin-Plus#1572]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by IITII** [comment]
相关截图：

重现步骤：

**Comment by yangdong123** [comment]
1，搜索方案里面添加很多搜索方案条目 

2，搜索框选择搜索方案 

<img width="208" alt="截屏2023-09-12 10 15 56" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/13993776/1b73c87c-06c7-425c-b402-e6066975b631">
