### ISSUE TITLE
HaresClub白兔俱乐部的发布数为账号昵称

### ISSUE THREAD

**Issue by AdiEcho** [pt-plugins/PT-Plugin-Plus#1579]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x ] 搜素过Issue，确认没有相关问题
- [ x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2353
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Edge  116.0.1938.76
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：
- 问题描述：
HaresClub白兔俱乐部站点的发布数为账号昵称

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/30563671/5d40e9ac-15b2-4f3b-9f9a-3dca14907c01)

- 重现步骤：
我只有数字昵称的账号，不太确定非数字的会不会也显示为昵称，有需要的话可以提供账号

**Comment by ted423** [comment]
Sorry, you have been blocked
You are unable to access hares.top
