### ISSUE TITLE
出现截图重复显示数据的情况

### ISSUE THREAD

**Issue by zgk1989** [pt-plugins/PT-Plugin-Plus#1582]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2353
- PT 助手安装方式：本站下载按装
- 浏览器名称及版本：360安全浏览器15，版本号:15.1.1230.64内核:114.0.5735.289
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：
- 问题描述：
一开始装的v1.5.2的就是不会显示做种总量，到本站下载最新版本升级后，出现截图重复显示数据的情况。

- 相关截图：
![PT-Plugin-Plus-UserData (1)](https://github.com/pt-plugins/PT-Plugin-Plus/assets/145040838/368f2845-faa1-41e5-82ce-2750e2efc2cd)

**Comment by IITII** [comment]
哪个重复了? 前面是总量, 后面是 TopN
