### ISSUE TITLE
发送种子下载路径无法更改

### ISSUE THREAD

**Issue by shanshangshi** [pt-plugins/PT-Plugin-Plus#1599]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

我不会搜索啊。。。

- PT 助手版本:1.6.1.2400
- PT 助手安装方式：crx安装
- 浏览器名称及版本：360csex_21.0.1216.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：NAS有6块硬盘，下载器指定的默认路径/downloads在第一块硬盘，但是PTPP里有些路径是指向其他硬盘的。在站点详情页发送下载后，只能下载到/downloads里。最后一个没有此BUG的版本，2388。之后的版本都是这样。

- 相关截图：
https://pic.ziyuan.wang/2023/09/24/shanshangshi_0d808b0a26328.png
https://pic.ziyuan.wang/2023/09/24/shanshangshi_e3bf622064f11.png
https://pic.ziyuan.wang/2023/09/24/shanshangshi_b352466135fda.png

- 重现步骤：

**Comment by zpy0577** [comment]
出现同样问题，1.6.1.2397版ptpp内下载目录设置失效
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/114006452/77e7ac40-e207-4c12-a796-d7d8942f7de1)
点击如下任何路径下载，只能下载到下载器默认路径
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/114006452/77939d2c-67cc-45f8-a37b-5d67f0aad74a)
默认路径为
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/114006452/6482e9eb-a876-4c0a-83b7-a250893b80b5)
换回1.6.1.2368（也就是最新的release版）就恢复正常，麻烦排查下

**Comment by shanshangshi** [comment]
> 出现同样问题，1.6.1.2397版ptpp内下载目录设置失效 ![image](https://user-images.githubusercontent.com/114006452/270164241-77e7ac40-e207-4c12-a796-d7d8942f7de1.png) 点击如下任何路径下载，只能下载到下载器默认路径 ![image](https://user-images.githubusercontent.com/114006452/270164332-77939d2c-67cc-45f8-a37b-5d67f0aad74a.png) 默认路径为 ![image](https://user-images.githubusercontent.com/114006452/270164452-6482e9eb-a876-4c0a-83b7-a250893b80b5.png) 换回1.6.1.2368（也就是最新的release版）就恢复正常，麻烦排查下



> 出现同样问题，1.6.1.2397版ptpp内下载目录设置失效 ![image](https://user-images.githubusercontent.com/114006452/270164241-77e7ac40-e207-4c12-a796-d7d8942f7de1.png) 点击如下任何路径下载，只能下载到下载器默认路径 ![image](https://user-images.githubusercontent.com/114006452/270164332-77939d2c-67cc-45f8-a37b-5d67f0aad74a.png) 默认路径为 ![image](https://user-images.githubusercontent.com/114006452/270164452-6482e9eb-a876-4c0a-83b7-a250893b80b5.png) 换回1.6.1.2368（也就是最新的release版）就恢复正常，麻烦排查下

如果你只有一块硬盘的话，最新版的得在“编辑下载服务器”那地方重新添加下载目录。但是我是多块硬盘就没办法。之前的版本都可以，最后一个好用的版本是2388。

**Comment by IITII** [comment]
#1588 

* qb 4.5.2 实测 autoTMM 为 true 的情况下, 如果指定分类, 存储路径以分类为准.
* 分类不存在时, 会自动创建分类, 路径为 `默认下载路径/分类名称`.


你分类路径不对吧? 或者名称有重复. 不想用自动分类关了就行

**Comment by zpy0577** [comment]
> #1588
> 
> > autoTMM: 自动种子管理
> 
> * qb 4.5.2 实测 autoTMM 为 true 的情况下, 如果指定分类, 存储路径以分类为准.
> * 分类不存在时, 会自动创建分类, 路径为 默认 `下载路径/分类名称`
> * PTPP 里面配置的路径不匹配的情况下, 会自动禁用 autoTMM
> * PTPP 分类路径和名称需要和 QB 一直
> 
> 配置的有问题吧,. 不想用自动分类关了就行

大佬好，我目前使用的是nev版的qb，版本为4.3.9，github地址是https://github.com/devome/dockerfiles/tree/master/qbittorrent
这个版本其中一个功能是下载完成后本地脚本会根据tracker自动分类，如下所示
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/114006452/fe6576c4-638c-4ba6-ae25-9ce406e43d8f)
所以其实我只需要ptpp能根据我设置的下载路径正确发送到qb，保持未分类的状态就行，autoTMM之前没有接触过，是不是4.5以上才有的功能，以前的版本我直接设置好下载目录推送过去就行
请问新版的要怎么设置才能实现无须分类下推送到对应路径的功能，版本为4.3.9，谢谢

**Comment by shanshangshi** [comment]
说错了，我用的版本是4.5.5




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月24日(星期天) 晚上9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pt-plugins/PT-Plugin-Plus] 发送种子下载路径无法更改 (Issue #1599)





  
#1588
  
autoTMM: 自动种子管理
   
qb 4.5.2 实测 autoTMM 为 true 的情况下, 如果指定分类, 存储路径以分类为准.
 
分类不存在时, 会自动创建分类, 路径为 默认 下载路径/分类名称
 
PTPP 里面配置的路径不匹配的情况下, 会自动禁用 autoTMM
 
PTPP 分类路径和名称需要和 QB 一直
  
配置的有问题吧,. 不想用自动分类关了就行
  
大佬好，我目前使用的是nev版的qb，版本为4.3.9，github地址是https://github.com/devome/dockerfiles/tree/master/qbittorrent
 这个版本其中一个功能是下载完成后本地脚本会根据tracker自动分类，如下所示
 
 所以其实我只需要ptpp能根据我设置的下载路径正确发送到qb，保持未分类的状态就行，autoTMM之前没有接触过，是不是4.5以上才有的功能，以前的版本我直接设置好下载目录推送过去就行
 请问新版的要怎么设置才能实现无须分类下推送到对应路径的功能，版本为4.3.9，谢谢

**Comment by dapege** [comment]
> #1588
> 
> > autoTMM: 自动种子管理
> 
> * qb 4.5.2 实测 autoTMM 为 true 的情况下, 如果指定分类, 存储路径以分类为准.
> * 分类不存在时, 会自动创建分类, 路径为 默认 `下载路径/分类名称`
> * PTPP 里面配置的路径不匹配的情况下, 会自动禁用 autoTMM
> * PTPP 分类路径和名称需要和 QB 一直
> 
> 配置的有问题吧,. 不想用自动分类关了就行

https://github.com/pt-plugins/PT-Plugin-Plus/blob/aed0ae5fd480857e0257da7cb99b5acce97e4532/resource/clients/qbittorrent/init.js#L172-L190
这块逻辑有问题吧，开了自动分类 autoTMM 才有可能变为 false，不开就直接 true 了

**Comment by IITII** [comment]
fixed: 3331700839dce6f0c249de4dfb7209a2f926a21f
