### ISSUE TITLE
关于“发送种子下载路径无法更改”的问题再问。

### ISSUE THREAD

**Issue by shanshangshi** [pt-plugins/PT-Plugin-Plus#1600]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2400
- PT 助手安装方式：crx安装
- 浏览器名称及版本：360csex_21.0.1216.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：NAS有6块硬盘，下载器指定的默认路径/downloads在第一块硬盘，但是PTPP里有些路径是指向其他硬盘的。在站点详情页发送下载后，只能下载到/downloads里。最后一个没有此BUG的版本，2388。之后的版本都是这样。

- 相关截图：

<img src="https://pic.ziyuan.wang/2023/09/24/shanshangshi_066f6570d2643.png" alt="001.png" title="001.png" />
<img src="https://pic.ziyuan.wang/2023/09/24/shanshangshi_af39730686340.png" alt="002.png" title="002.png" />
<img src="https://pic.ziyuan.wang/2023/09/24/shanshangshi_f4b28401e206a.png" alt="003.png" title="003.png" />
<img src="https://pic.ziyuan.wang/2023/09/24/shanshangshi_de5b6610ebfd8.png" alt="004.png" title="004.png" />

- 重现步骤：

**Comment by shanshangshi** [comment]
1.6.1.2388和之前的版本都没问题。之后的版本就不行了。

**Comment by flashlab** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/commit/3331700839dce6f0c249de4dfb7209a2f926a21f 之后问题依然存在

**Comment by shanshangshi** [comment]
> [3331700](https://github.com/pt-plugins/PT-Plugin-Plus/commit/3331700839dce6f0c249de4dfb7209a2f926a21f) 之后问题依然存在

1.6.1.2401好像可以了。

**Comment by IITII** [comment]
更新后需要重启浏览器
