### ISSUE TITLE
我的数据里，按入站时间排序不准确

### ISSUE THREAD

**Issue by tanghulu0608** [pt-plugins/PT-Plugin-Plus#1602]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2386
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Microsoft Edge 版本 117.0.2045.36 (正式版本) (64 位)
- 浏览器是否安装了其他插件：AdGuard 广告拦截器 4.2.168
- 停用其他插件后是否正常工作：否
- 问题描述：
我的数据里，按入站时间排序不准确

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/5561864/40fdf2bc-c6e2-4825-a146-28904e1639ca)

- 重现步骤：
我的数据功能，刷新我的数据，然后点入站时间这个列标题排序

**Comment by IITII** [comment]
你这也没点? 灰色是没选中, 黑色才是选中
<img width="286" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/a6e2e6c8-6dab-4194-aa1b-b16e4444ec71">

**Comment by tanghulu0608** [comment]
哦，我大概明白了：灰色的向上箭头的时候，其实不是按这个入站时间排序的。只有黑色箭头的时候，才是排序的。

建议这排序的时候，不要显示这个灰色的向上箭头吧？感觉有点误解的。

**Comment by IITII** [comment]
不考虑修改, 点几下试试就知道问题在哪了. 而且那个箭头移上去才会显示...
