### ISSUE TITLE
无法导出我的数据图片

### ISSUE THREAD

**Issue by tanghulu0608** [pt-plugins/PT-Plugin-Plus#1603]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2386
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Microsoft Edge 版本 117.0.2045.36 (正式版本) (64 位)
- 浏览器是否安装了其他插件：AdGuard 广告拦截器 4.2.168
- 停用其他插件后是否正常工作：否
- 问题描述：
无法导出我的数据图片，一直转圈。贴吧也有人反应这个情况。

- 相关截图：
![微信截图_20230928151132](https://github.com/pt-plugins/PT-Plugin-Plus/assets/5561864/98a584ea-2dc0-4746-ac9d-c1da68fe2739)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/5561864/6522dba4-1e53-4799-b0a8-852c5ca94203)

- 重现步骤：
我的数据功能，刷新我的数据，然后导出图片

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/956

**Comment by tanghulu0608** [comment]
谢谢 我更新了站点图标后，确实可以导出了
