### ISSUE TITLE
BLU开启二步验证后个人信息抓取异常

### ISSUE THREAD

**Issue by G1t-hub** [pt-plugins/PT-Plugin-Plus#1605]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2408
- PT 助手安装方式：zip
- 浏览器名称及版本：Edge
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：否
- 问题描述：
BLU在开启二步验证后，如果刷新个人数据时尚未通过验证，抓取到的用户等级和等级要求字段有误，会导致整个我的数据页面卡死，且强制刷新扩展页面后无法加载，关闭相关字段可以恢复。

- 相关截图：
![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/56796909/1d394fce-9368-4976-bf60-e276e89dcbf1)
![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/56796909/13ba3653-78d4-49e0-b708-71c6e25b2c90)

- 重现步骤：
在BLU添加二步验证，待二步验证过期后刷新个人数据

**Comment by ted423** [comment]
@G1t-hub 这个站的二次验证………感觉最好不要开

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/commit/08277680e716bd69e8f788d54628df8d5b3c9434

等发布了再看看
