### ISSUE TITLE
希望增加一个开关，下载的时候可以选择使用站点名(小写)作为 qb 的标签，类似 IMDB-ID 一样，方便归类

### ISSUE THREAD

**Issue by zhi1ong** [pt-plugins/PT-Plugin-Plus#1621]
## 您的功能请求是否与问题有关？ 请描述一下。

现在只能设置增加 imdb 标签，希望能增加站点名的小写作为标签，方便归类

## 描述你想要的解决方案

设置里增加一个选项，是否增加站点名作为标签

**Comment by IITII** [comment]
可以自己先按 traker url 排序.

**Comment by aiden0w0** [comment]
写了个脚本处理
https://gist.github.com/aiden0w0/34db565ffc85493ea49670dabd97cbb8

**Comment by zhi1ong** [comment]
@IITII 感恩，IYUU 辅种的时候确实也不会自动打 Tag，自己改了一个版本支持。。。
