### ISSUE TITLE
安装action的dev-build-1.6.1.2433-crx的时候遇到 Duplicate keys are not allowed in JSON files.  错误: Duplicate key: selectors found in JSON resource/sites/pt.0ff.cc/config.json 第 108 行

### ISSUE THREAD

**Issue by yanwen** [pt-plugins/PT-Plugin-Plus#1625]
- PT 助手版本:1.6.1.2433
- PT 助手安装方式：crx上传到amo平台转成xpi的时候遇到的问题
- 问题描述：
 Duplicate keys are not allowed in JSON files.  错误: Duplicate key: selectors found in JSON resource/sites/pt.0ff.cc/config.json 第 108 行

- 相关截图：
![iShot_2023-10-13_03 23 33](https://github.com/pt-plugins/PT-Plugin-Plus/assets/1297576/1157d003-db73-4ffa-8fc7-70b606cf7376)

- 重现步骤：

crx上传到amo平台转成xpi的时候遇到报错。

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/releases
https://github.com/pt-plugins/PT-Plugin-Plus/wiki

* 暂不支持任何第三方转换工具的问题

**Comment by yanwen** [comment]
@IITII  我看了一下代码，的确是重复了。  我下载zip包解压之后 找到对应的代码 并且删除掉就可以解决这个问题。

大佬方便的话去看看？？应该是真的有问题。

https://github.com/pt-plugins/PT-Plugin-Plus/blob/dev/resource/sites/pt.0ff.cc/config.json

![iShot_2023-10-13_11 29 55](https://github.com/pt-plugins/PT-Plugin-Plus/assets/1297576/61dabb91-5ab5-4934-99b2-3470f868bd75)
