### ISSUE TITLE
猫站游戏类种子详情页获取下载链接失败

### ISSUE THREAD

**Issue by KempLeung** [pt-plugins/PT-Plugin-Plus#1629]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2436
- PT 助手安装方式：crx
- 浏览器名称及版本：chrome 118.0.5993.71（正式版本） （64 位）
- 浏览器是否安装了其他插件：ADBlock 5.1.1，Tampermonkey 4.16.1（无脚本加载），Google翻译，EditThisCookies 1.6.3，IDM Integration Module 5.1.1，购物党自动比价工具 5.11.61，IE Tab 15.8.13.1，EverSync 19.1.5，
- 停用其他插件后是否正常工作：否
- 问题描述：猫站游戏类种子详情页获取下载链接失败
相关:https://github.com/pt-plugins/PT-Plugin-Plus/issues/1133 去年提出猫站种子详情页不显示插件的BUG被修复后，发现下载按钮无法获取下载链接，当时忙忘了再次提交反馈

- 相关截图：

- 重现步骤：打开猫站游戏区任意种子详情页，点击插件侧栏“一键下载”或“下载到“按钮，右下出现红色提示”获取下载链接失败“

**Comment by IITII** [comment]
4660e25e27f91d8b745474fc54bc948b8684dd2b
