### ISSUE TITLE
海胆 haidan 保存种子文件错误

### ISSUE THREAD

**Issue by aiden0w0** [pt-plugins/PT-Plugin-Plus#1630]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [ x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2436
- PT 助手安装方式：（市场安装，或zip包安装） 市场安装
- 浏览器名称及版本：Chrome 118.0.5993.72
- 浏览器是否安装了其他插件：Y
- 停用其他插件后是否正常工作：N
- 问题描述：海胆下载种子文件错误

- 相关截图：

- 重现步骤：搜索 - 下载

**Comment by IITII** [comment]
文件内容是什么? 如果是 downloadnotice.html 是话, 手动下一次种子. wiki 常见问题有写

**Comment by aiden0w0** [comment]
> 文件内容是什么? 如果是 downloadnotice.html 是话, 手动下一次种子. wiki 常见问题有写

没说清楚，是种子文件保存功能。直接跳到```https://www.haidan.video/undefined```

**Comment by IITII** [comment]
听起来是 下载链接获取问题. 你可以看看下载链接的拼接方式. 试试站点设置添加 passkey 之后, 能否正常

**Comment by aiden0w0** [comment]
> 听起来是 下载链接获取问题. 你可以看看下载链接的拼接方式. 试试站点设置添加 passkey 之后, 能否正常

添加passkey之后url还是undefined

**Comment by ted423** [comment]
@aiden0w0 不要加passkey

**Comment by ted423** [comment]
@aiden0w0 弄错，我没看上面的🌚

**Comment by aiden0w0** [comment]
好像没问题了。我先关了
