### ISSUE TITLE
豆瓣 top 页面搜索功能报错

### ISSUE THREAD

**Issue by jheroy** [pt-plugins/PT-Plugin-Plus#1631]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题

- PT 助手版本: 1.6.1 2436
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：firefox 118.0.2
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：在https://movie.douban.com/top250 页面点击搜索会弹出错误
` { "readyState": 0, "status": 0, "statusText": "error" } `

- 相关截图：

<img width="729" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/504766/35e07a7c-4c58-4751-951d-cc78e416c9a3">

**Comment by SHL-COOL** [comment]
接口出问题了，这里使用的接口是https://omit.mkrobot.org/movie/1292052/douban/imdb

不知道这个接口还维护吗
