### ISSUE TITLE
无法获取葡萄putao的做种数和做种体积

### ISSUE THREAD

**Issue by LoneFireBlossom** [pt-plugins/PT-Plugin-Plus#1635]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: © 栽培者 2023, 版本 v1.6.1.2440 zip
- PT 助手安装方式：zip安装
- 浏览器名称及版本：Chrome 版本 118.0.5993.96（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

如标题所说，葡萄站的做种数和做种体积不显示

- 相关截图：
<img width="429" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/50087596/9f3083c8-23bb-41aa-802d-ab4b095c28b2">

- 重现步骤：

**Comment by pxwang85** [comment]
因为NexusPHP当中 getMoreInfos 获取信息时候
userUploadedTorrents 的地址不存在，导致catch

修改葡萄站点配置中
"selectors": {
    "userSeedingTorrents": {
      "page": "/viewusertorrents.php?id=$user.id$&show=seeding",
      "fields": {
        "seeding": {
          "selector": ["tr:not(:eq(0))"],
          "filters": ["query.find('td.rowfollow:eq(1)').length"]
        },
        "seedingSize": {
          "selector": ["tr:not(:eq(0))"],
          "filters": ["jQuery.map(query.find('td.rowfollow:eq(1)'), (item)=>{return $(item).text();})", "_self.getTotalSize(query)"]
        }
      }
    },
    "userUploadedTorrents": {      
      "prerequisites": "!user.uploads",
      "page": "/viewusertorrents.php?userid=$user.id$&type=uploaded",
      "fields": {
        "uploads": {
          "selector": ["b:first"],
          "filters": ["query ? parseInt(query.text().trim().replace(/,/g,'')) : 0"]
        }
      }
    }
  }

**Comment by IITII** [comment]
有空的话, 可以提个 PR @pxwang85
