### ISSUE TITLE
mtv无法批量下载种子

### ISSUE THREAD

**Issue by Marblebishop** [pt-plugins/PT-Plugin-Plus#1639]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2436

- PT 助手安装方式：zip
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：否
- 问题描述：
mtv无法使用ui按钮批量下载种子，getDownloadURLsFailed

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/22914422/a9cf2bc3-e0c8-4564-8f66-2db0f3e92285)

- 重现步骤：
mtv无法使用ui按钮批量下载种子，getDownloadURLsFailed

**Comment by ted423** [comment]
看了一下，应该是没对种子列表页做适配

**Comment by Marblebishop** [comment]
还没修好怎么就close了...
