### ISSUE TITLE
能否显示时魔上限？

### ISSUE THREAD

**Issue by elderren** [pt-plugins/PT-Plugin-Plus#1641]
## 您的功能请求是否与问题有关？ 请描述一下。

能否在显示时魔的位置加一个时魔上限的数据，显示成类似95/100的格式。

**Comment by ted423** [comment]
@elderren 我个人反对，我认为ptpp的作用不是让人不打开网站本身。这种信息如果不清楚，打开相应站点看就好了。现有的信息维护起来已经够繁杂了。

**Comment by elderren** [comment]
> @elderren 我个人反对，我认为ptpp的作用不是让人不打开网站本身。这种信息如果不清楚，打开相应站点看就好了。现有的信息维护起来已经够繁杂了。

并不是为了不打开网站，只是为了聚合显示站点信息，提升效率。如果从技术角度获取这类信息不方便，能否在站点数据页面加一个备注栏，用户可以自行填写各种信息。

**Comment by IITII** [comment]
...不如你把魔力页面和站点规则放站点快捷链接里面, 名字就写时魔上限, 有空多看看站点规则

**Comment by ted423** [comment]
> > @elderren 我个人反对，我认为ptpp的作用不是让人不打开网站本身。这种信息如果不清楚，打开相应站点看就好了。现有的信息维护起来已经够繁杂了。
> 
> 并不是为了不打开网站，只是为了聚合显示站点信息，提升效率。如果从技术角度获取这类信息不方便，能否在站点数据页面加一个备注栏，用户可以自行填写各种信息。

投入过多，产出一个基本不怎么用的信息，个人觉得没必要。如果一个站点，你连时魔上限都弄不清楚，那就说明你平时根本不关注这个站点。那么你需要判断一下你是否还需要这个站。
另外我个人认为ptpp不需要在聚合站点信息这块继续投入了。
一方面维护者的精力肯定不够，另一方面，全而杂会导致界面和功能混乱。现有的信息很多都还没维护完。

**Comment by ted423** [comment]
还有一个方面就是制式不统一的问题，比如有的站无上限，有的站vip双倍。
整体来说，加入上限确实是显示会更直观。但是显示不统一，还有一个就是 时魔/上限 这种数字表现形式很丑。

或许可以弄成进度条的形式（但除非跳出一个大佬出来说，这功能我来搞。）
所以暂时先不考虑吧

**Comment by ted423** [comment]
想了一下，之前用词不太好，编辑掉了。

**Comment by elderren** [comment]
想了想觉得你们说的有道理，单独加一个石墨上限确实不太有必要，但是感觉备忘功能还是可以考虑一下？可以由用户自己填写例如契约内容、魔力借贷、考核内容、HR规则等等，我站点比较多，主要把ptpp作为导航页+聚合管理工具，能在“我的数据”界面看到备忘还是很方便的，其他用户如果对于站点信息有不同需求也可以自行填写，也省了给维护者增加负担。当然我不是程序员，不确定这个功能的开发难度，如果大佬们觉得优先级不高我也理解，向为爱发电的人们致敬~

**Comment by IITII** [comment]
那你用快捷链接就好了. 比如魔力借贷一般是短讯的方式进行的, 添加链接的时候, 内容填写借贷详情, 链接放短讯地址即可.

elderren ***@***.***> 于2023年11月6日周一 18:01写道：
