### ISSUE TITLE
打胶时魔显示异常

### ISSUE THREAD

**Issue by qq2368627164** [pt-plugins/PT-Plugin-Plus#1642]
- PT 助手版本:1.6.1.2446
- PT 助手安装方式：zip
- 浏览器名称及版本：edge
- 问题描述：打胶时魔1000多显示为1.00

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/97807568/13dbdc13-f0bc-4e77-809f-ae7383d0a0c1)

- 重现步骤：

**Comment by IITII** [comment]
https://dajiao.cyou/mybonus.php 这个界面石墨图截图看看, 看看是不是因为有个逗号导致的 `1,100.11` 这种

**Comment by qq2368627164** [comment]
是的，有一个逗号












キサラ
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月6日(周一) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pt-plugins/PT-Plugin-Plus] 打胶时魔显示异常 (Issue #1642)




 
https://dajiao.cyou/mybonus.php 这个界面石墨图截图看看, 看看是不是因为有个逗号导致的 1,100.11 这种

**Comment by IITII** [comment]
@qq2368627164 你回头去 action 里面下载更新下试试. 或者这个频道会推送 https://t.me/PTPPAction
