### ISSUE TITLE
qb下载器默认打开了自动种子管理，即使没设置

### ISSUE THREAD

**Issue by RUANRUI1995** [pt-plugins/PT-Plugin-Plus#1643]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2446
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
qb下载器设置里面并没有开启自动种子管理，但是通过助手下载的种子都默认开了自动种子管理，导致下载完之后种子位置变动。以前的版本不会这样子的

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/18418418/7f098cfc-d340-46f0-b5ab-bcb8ff784d25)

- 重现步骤：

**Comment by RUANRUI1995** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/18418418/f1fb4f18-f38a-4068-b724-632e05660240)
我用的qb版本有自动分类功能的，如果都是未分类可能就没发现这个问题

**Comment by ted423** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/7042766/760c7509-6c37-4c8f-9bdd-77de66ee3e24)
检查你的qb设置

**Comment by mitlearn** [comment]
PTPP提供了分类+路径的保存形式 参照https://github.com/pt-plugins/PT-Plugin-Plus/pull/1588#issuecomment-1722486437
同时请阅读https://github.com/pt-plugins/PT-Plugin-Plus/issues/1599#issuecomment-1732567060

**Comment by ted423** [comment]
@IITII  试了下，确实自动开了自动种子管理。
qb这个自动种子管理有时候容易误操作导致问题，所以感觉如果没用那两个beta功能的话，默认不开自动种子管理？

**Comment by IITII** [comment]
之前的逻辑是不指定 savePath, 默认开启 autoTMM, 指定路径关闭
现在的逻辑是不指定 savePath, 默认开启 autoTMM. 指定路径 `已配置且开启自动添加分类` 会添加对应分类并开启 autoTMM.

不想使用 autoTMM 就把 `自动添加分类` 关掉, 下载的时候手动指定下载路径.

**Comment by ted423** [comment]
@IITII 我这是2446版本，跟提问题的一致，没指定路径也没开启自动添加分类也会。

**Comment by ted423** [comment]
@IITII 我看后续的commit似乎没对相关事项更改，2446版本应该就是目前最终的逻辑吧？

**Comment by IITII** [comment]
这个好早之前就改了。在默认下载目录，手动选择下载目录，qb自动分类都没有设置的情况下, 无论ptpp的版本，就是走 qb 的默认路径并启用 autoTMM.

**Comment by ted423** [comment]
@IITII 我用tr有段时间了，这个修改的原因是啥？因为我记得qb自身可以设置是否添加的种子开启自动种子管理。这种情况下，我感觉给用户选择权会比较好。

**Comment by IITII** [comment]
之前一直是这样. 没变化

**Comment by ted423** [comment]
我试了一下 2372 9月份的版本还不会这样

**Comment by IITII** [comment]
@ted423 @RUANRUI1995 那么在不设置下载路径的情况下, 开启 autoTMM 有什么影响吗? 这种情况下我认为种子路径不会发生变化, 还是 qb 默认的下载路径.

<img width="447" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/090cfebe-732e-476c-b580-45e31b3398eb">
<img width="492" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/57f0be3b-4bf5-4d39-8a50-572baa3e40bd">

**Comment by ted423** [comment]
我默认弄得是手动，有次改分类没注意，自动就给我往系统盘挪，然后还没法取消。主要是一个使用习惯的问题（之前用的时候，默认都不开自动，有需要的种子手动开，设分类）
这块我的想法是，默认的话，如果没有需要，就不用在发送的时候设置，遵循qb设置就好。qb里设自动就自动，手动就手动，如果分类那块有需求，开启的情况下就设自动。
或者就给个开关，用户可以选择自动手动或者置空（应该置空就是遵循QB自身设置吧）

**Comment by ted423** [comment]
忘了说，之前这么用是跟qb行为有关，辅种任务tr 可以批量直接移，qb的重复任务会校验，但是自动管理的设置下，批量移动不会校验。（理论上我认为两种行为其中一个算是bug.应该统一一下
