### ISSUE TITLE
byrpt无法正常显示种子数据（大小，上传，下载等）

### ISSUE THREAD

**Issue by RnLuck** [pt-plugins/PT-Plugin-Plus#1649]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: © 栽培者 2023, 版本 v1.6.0.ba3d87e
- PT 助手安装方式：（市场安装，或zip包安装） 市场安装
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作： 否
- 问题描述：
byrpt（北邮人的新网站，byr.pt）无法正常显示种子数据（大小，上传，下载等）

- 相关截图：
ptpp中搜索结果：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/58815759/315b812e-08cf-4a10-9360-8493c871624b)
ptpp中其他种子站搜索结果：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/58815759/61846cf1-211c-4ef7-ba93-01d9bf36fd63)
byrpt中搜索结果：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/58815759/c7fa768d-a313-4a13-b39f-3cb906210a23)

- 重现步骤：
1.添加北邮人pt站点，byr.pt
2.在插件中搜索任意种子（例：奥本海默）

**Comment by fzlins** [comment]
下載新版本。

**Comment by huxuan** [comment]
用了最新的 pre-release 依然有这个问题

**Comment by RnLuck** [comment]
> 用了最新的 pre-release 依然有这个问题

我用的v1.6.1.2463版本，这个问题已经解决了

**Comment by huxuan** [comment]
> > 用了最新的 pre-release 依然有这个问题
> 
> 我用的v1.6.1.2463版本，这个问题已经解决了

感谢回复！我用的 v1.6.1.2492，貌似还是没有耶，是需要怎么设置或者清空一下缓存啥的吗？

**Comment by huxuan** [comment]
啊，不对，我又仔细看了一眼，种子的数据是没有问题的，但是下载中，已下载的状态不显示。比如下图，这些种子我确认已经下载做种中了。

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/726061/2f70284d-6522-45b2-a059-8b167cce47bc)
