### ISSUE TITLE
魔力值改为电力值

### ISSUE THREAD

**Issue by CwPlace** [pt-plugins/PT-Plugin-Plus#1663]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:2482
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome119
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
我的数据中 zmpt魔力值改为电力值
现在不显示了

- 相关截图：

- 重现步骤：

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1690
