### ISSUE TITLE
FSM升级页面烦请大佬适配支持

### ISSUE THREAD

**Issue by lemon99ee** [pt-plugins/PT-Plugin-Plus#1678]
FSM于11.21日升级页面 数据已经十几天没同步了 请求大佬看看
上一个issue可能标签选错了   重开一个 烦请大佬适配   非常感谢

**Comment by mitlearn** [comment]
存在技术问题未解决 无法适配https://github.com/pt-plugins/PT-Plugin-Plus/issues/1684#issue-2030036747

**Comment by Qm-jmz** [comment]
数据同步这块不知道，关于种子下载我目前的替代方案是用rss
