### ISSUE TITLE
猫站升级条件错误以及梓喵时魔显示错误

### ISSUE THREAD

**Issue by scottymax** [pt-plugins/PT-Plugin-Plus#1681]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2492
- PT 助手安装方式：git下载zip安装
- 浏览器名称及版本：google chrome 115.0.5790.170
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
猫站我的账号已经升级至最高等级NM，后来猫站升级条件发生变更，我的账号还是最高等级，不用增加新的升级条件，但是目前在等级一栏下多出来两个升级条件，且没有已经升至满级的绿色√，希望大佬更新这个BUG。另外梓喵的时魔目前显示为1，但是我的基础时魔已经有1000+，希望能够显示正确的时魔值。

- 相关截图：
![003](https://github.com/pt-plugins/PT-Plugin-Plus/assets/44422324/80d30860-5800-4032-a81e-48b3dbd67ac8)
![002](https://github.com/pt-plugins/PT-Plugin-Plus/assets/44422324/9942fda8-09d6-40ce-92b8-25838c12ad31)
![001](https://github.com/pt-plugins/PT-Plugin-Plus/assets/44422324/1f77606a-32b7-45ca-adff-efdcba4c64f9)

- 重现步骤：
无，具体表现见上图。

**Comment by IITII** [comment]
这个不是 bug, 你要觉得是的话, 我可以帮你 PM 管理降下级 /doge. `猫站升级条件发生变更，我的账号还是最高等级，不用增加新的升级条件，但是目前在等级一栏下多出来两个升级条件，且没有已经升至满级的绿色√，希望大佬更新这个BUG`
