### ISSUE TITLE
site schema 中headers支持脚本或selector

### ISSUE THREAD

**Issue by llemllen** [pt-plugins/PT-Plugin-Plus#1684]
## 您的功能请求是否与问题有关？ 请描述一下。

在一些站点,如fsm,采用了前后端分离的形式,鉴权通过jwt完成的,在headers中携带存储在对应域名下的LocalStorage,
目前的schema中headers好像是采用写死的形式,或者由其他接口响应后存储起来的自定义变量,尝试用selector及scripts:,在结合源码,发现headers这块不太支持动态自定义

## 描述你想要的解决方案

schema可以支持执行脚本,例如获取对应站点下的storage

## 其他附加信息

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/35473748/b50c4160-32b0-4c91-bcd5-f43c52931336)

**Comment by llemllen** [comment]
可以提供类似qinglong工具,可以自己填写变量,然后在site对应config中读取么

**Comment by IITII** [comment]
因为 `webextension 没提供相关api来访问特定 host LocalStorage`

比较一般的做法可能是这样, 通过 login 接口拿数据. 不过用户名密码 甚至验证码应该怎么处理又是一个问题...

如果登陆没有验证码的话, 可以考虑在 getInfo 的时候, 将站点设置 merge 进来. 因为站点设置可以修改一些设置.

```
至于设置变量, 不太现实. 别的不说, 这个 token 有效期可能很短, 能设置 token 的地方同理也可以设置用户名和密码.
而且获取  headers 里面的 token 这个操作对于一些人来说本身也是一个问题.
如果说能用 passkey 调通接口的话, 操作性应该会高点. 需要站点支持...
```

<img width="721" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/6a15e1e8-8757-478a-af9a-a65ba2ac1d15">

https://github.com/pt-plugins/PT-Plugin-Plus/blob/136d7294f0e4e6036b50cfe9e8e31cf85d7faf58/src/background/user.ts#L280-L324

**Comment by llemllen** [comment]
1. 关于变量这块fsm站点有推出apiToken,有效期为30天,调用接口时候在headers中传递apiToken及passkey调用,
但也像 @IITII 提的,获取apiToken及设置变量对大部分用户来说有难度
2. 验证码这块一些开源项目,如 [qd](https://github.com/qd-today/qd/) 中有提供ocr接口处理验证码,但没研究过qd源码

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/35473748/4920d5f2-d571-41c8-8f02-3a44e9231d16)

**Comment by IITII** [comment]
想起一个事, 登陆这条路应该是不行的. 
https://github.com/pt-plugins/PT-Plugin-Plus/issues/44
https://github.com/pt-plugins/PT-Plugin-Plus/issues/13

**Comment by ted423** [comment]
@IITII 所以要不把fsm 删了吧

**Comment by IITII** [comment]
> 你是隔壁站派来的吧  

等一手 mt 升级再看看吧. 或者站点也可以支持 cookie 验证作为一个过渡性的验证方式(~~这样就不需要改了~~).

> 大佬的话也可以自己改改看看, 关键代码如下  


https://github.com/pt-plugins/PT-Plugin-Plus/blob/136d7294f0e4e6036b50cfe9e8e31cf85d7faf58/src/background/user.ts#L280-L324

**Comment by ted423** [comment]
@IITII 我猜是不想支持，我号可能已经没了。

**Comment by IITII** [comment]
其实我比较好奇，token有效期多久😂😂

**Comment by llemllen** [comment]
> 其实我比较好奇，token有效期多久😂😂 有效期不到一天的话，开tab这种方案感觉也不行

不止1天,感觉有个7天以上

**Comment by fzlins** [comment]
@IITII https://github.com/Jackett/Jackett/pull/14907 能参考Jackett吗？

**Comment by IITII** [comment]
这个是让用户自己填 token, 之前讨论过. 你可以试试 @fzlins 

https://github.com/pt-plugins/PT-Plugin-Plus/issues/1684#issuecomment-1857535176

**Comment by IITII** [comment]
> 1. 关于变量这块fsm站点有推出apiToken,有效期为30天,调用接口时候在headers中传递apiToken及passkey调用,
>    但也像 @IITII 提的,获取apiToken及设置变量对大部分用户来说有难度
> 2. 验证码这块一些开源项目,如 [qd](https://github.com/qd-today/qd/) 中有提供ocr接口处理验证码,但没研究过qd源码
> 
> ![image](https://private-user-images.githubusercontent.com/35473748/290775664-4920d5f2-d571-41c8-8f02-3a44e9231d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzgxODMsIm5iZiI6MTcwNTA3Nzg4MywicGF0aCI6Ii8zNTQ3Mzc0OC8yOTA3NzU2NjQtNDkyMGQ1ZjItZDU3MS00MWM4LThmMDItM2E0NGU5MjMxZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMDQwYTE2MDgyYjBiODQ3ZDA1MDU0ZWYzODk1NzQ3YzM4N2NkMGJlZjMyMmE0MTNlMjkwZTk4OWI2MzA3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFu7A1KZo2D5AEoBdPUKnKgzQ4jZLBVRgIUJmBQbDa0)

"关于变量这块fsm站点有推出apiToken": 具体位置在哪, 网址操作截图看下

**Comment by imtipi** [comment]
> > 1. 关于变量这块fsm站点有推出apiToken,有效期为30天,调用接口时候在headers中传递apiToken及passkey调用,
> >    但也像 @IITII 提的,获取apiToken及设置变量对大部分用户来说有难度
> > 2. 验证码这块一些开源项目,如 [qd](https://github.com/qd-today/qd/) 中有提供ocr接口处理验证码,但没研究过qd源码
> > 
> > ![image](https://private-user-images.githubusercontent.com/35473748/290775664-4920d5f2-d571-41c8-8f02-3a44e9231d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzgxODMsIm5iZiI6MTcwNTA3Nzg4MywicGF0aCI6Ii8zNTQ3Mzc0OC8yOTA3NzU2NjQtNDkyMGQ1ZjItZDU3MS00MWM4LThmMDItM2E0NGU5MjMxZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMDQwYTE2MDgyYjBiODQ3ZDA1MDU0ZWYzODk1NzQ3YzM4N2NkMGJlZjMyMmE0MTNlMjkwZTk4OWI2MzA3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFu7A1KZo2D5AEoBdPUKnKgzQ4jZLBVRgIUJmBQbDa0)
> 
> "关于变量这块fsm站点有推出apiToken": 具体位置在哪, 网址操作截图看下

https://fsm.name/API
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/27230181/3173bb5b-5586-47d3-8552-9625361c0eb7)
如推
