### ISSUE TITLE
憨憨音乐/MV列表页面不显示小助手悬浮框

### ISSUE THREAD

**Issue by ydddj** [pt-plugins/PT-Plugin-Plus#1686]
- 憨憨音乐/MV列表页面不显示小助手悬浮框，请大佬更正~

**Comment by IITII** [comment]
未复现, 请先自行更新

**Comment by ydddj** [comment]
已经是最新版本了，页面为/special.php?cat[]=410,目前憨憨的 种子列表为 /torrents.php/music.php/movie.php 
烦请检查一下，音乐憨憨改了，现在网站标题栏为音乐beta,谢谢

**Comment by IITII** [comment]
<img width="1033" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/c2f7ca2c-dc46-4a53-82e3-73cd1b2db57e">
