### ISSUE TITLE
FSM飞天拉面神教站无法刷新数据

### ISSUE THREAD

**Issue by chn-zhong** [pt-plugins/PT-Plugin-Plus#1689]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x ] 搜素过Issue，确认没有相关问题
- [ x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2492
- PT 助手安装方式: zip包安装
- 浏览器名称及版本：chrome 120.0.6099.71（正式版本） （64 位）
- 浏览器是否安装了其他插件：篡改猴，zotero，editgpt
- 停用其他插件后是否正常工作：无法工作
- 问题描述：
FSM飞天拉面神教站（fsm.name）2.0版本更新后无法获取信息，正常添加站点，设置了获取个人信息的权限，刷新数据后状态栏显示“未登录”的蓝色链接，点击链接后跳转到FSM，我的站点是已经正常登录的，如此重复多次均无法刷新

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/148938474/9044f602-4532-4a79-bc6b-ba0254bef708)
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/148938474/a8c8352c-bf27-4756-b2c3-4ace21ba85b5)

- 重现步骤：
添加站点-设置获取个人信息权限-刷新我的数据-显示未登录-点击链接跳转-站点已登录-返回PTPP-数据未更新-重复刷新显示未登录

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1684
