### ISSUE TITLE
在浏览器打开的情况下自动上传用户数据 功能添加数量限制

### ISSUE THREAD

**Issue by KeepNaivety3** [pt-plugins/PT-Plugin-Plus#1692]
## 您的功能请求是否与问题有关？ 请描述一下。

在浏览器打开的情况下自动上传用户数据（Beta）功能能否添加一个备份服务器的备份数量限制，比如说仅保留最近5个备份 / 最新备份 / 最近一周备份，如果自动上传多了会堆积占用空间。

**Comment by IITII** [comment]
暂不考虑, 如果你用的镜像是 ronggang/owss 的话, 可以通过设置 maxResource 来达到这个目的
