### ISSUE TITLE
不显示数据

### ISSUE THREAD

**Issue by specked2527** [pt-plugins/PT-Plugin-Plus#1698]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.0.ba3d87e zip
- PT 助手安装方式：  zip（市场安装，或zip包安装）
- 浏览器名称及版本：Chrome 已是最新版本
版本 120.0.6099.130（正式版本） （64 位）
- 浏览器是否安装了其他插件：yes
- 停用其他插件后是否正常工作：no
- 问题描述： 显示用户名 不显示数据

- 相关截图：
![无标题](https://github.com/pt-plugins/PT-Plugin-Plus/assets/124735279/49874afe-cf8f-4aaf-8232-77cf359ca01e)

- 重现步骤：[PT-Plugin-Plus-System-Logs.json](https://github.com/pt-plugins/PT-Plugin-Plus/files/13771679/PT-Plugin-Plus-System-Logs.json)

**Comment by mitlearn** [comment]
https://t.me/ptpluginplus/190

**Comment by specked2527** [comment]
新进站点数据统计错误
使用通用模板添加的站点会因站点的修改无法正确统计数据

解决方法：
更新至最新Pre-release/Action版，而后站点设置中删除该站点数据，并使用一键导入站点
若导入后数据无该站点，则站点尚未适配，欢迎提交PR适配站点或耐心等待他人支持
