### ISSUE TITLE
功能请求：参数备份与恢复 备份服务器增加备份周期

### ISSUE THREAD

**Issue by thsrite** [pt-plugins/PT-Plugin-Plus#1699]
## 您的功能请求是否与问题有关？ 请描述一下。

参数备份与恢复能否增加定时备份功能，或者增加每天首次打开备份到备份服务器呢

## 描述你想要的解决方案

增加每天首次打开备份到备份服务器

## 描述您考虑过的替代方案

无

## 其他附加信息

无

**Comment by IITII** [comment]
<img width="860" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/b885dbee-350a-471d-8b1b-459825f4019c">

升级 https://t.me/PTPPAction/1481
