### ISSUE TITLE
请求适配飞天拉面PT站

### ISSUE THREAD

**Issue by kuanzai123** [pt-plugins/PT-Plugin-Plus#1701]
- 站点名称：飞天拉面
- 站点地址：https://fsm.name/
- 站点描述：本站是一个从零开始的新架构（虽然界面上还挺复古），也因此，本站必然存在非常多的BUG和功能缺失，在此，我先向各位会员们道个歉，希望你们后续使用过程中能少骂两句（毕竟我已经先道过歉了）。本站取名FSM，是“飞天拉面神教”的英文缩写，我们认为该教的口头禅“主不在乎”（也称“煮不再糊”）非常符合我们的思想。FSM具体的规则在 [规则页](https://fsm.name/Rules)，本帖主要讲讲规则以外的一些东西。各位阅读完规则之后，应该是可以发现FSM没有常规的用户等级。因为我们希望各位能在这里，专注分享资源、专注下载资源，只要保持分享率1.0以上，其他情况想怎么玩都可以。

- 资源类型：xxx
- 开放注册：否
- 是否连坐：否
- 站点规则：
1. 本站禁止中国IP登录，但允许中国IP使用（注册必须梯子，后面登录可以免梯）！！！！
2. 仅支持qq.com与gmail.com
3. 站点有且仅有以下的Ban号机制
 - 账户信誉度过低
 - 注册15天无流量（2022-10-21更新：7天->15天）
 - 长时间处于 Limit 状态（“限制用户”，无法连接Tracker）
 - 购买邀请码却不举报发邀人（被连坐）
 - 在任何公开渠道公布本站网址的用户（除其他PT站点的TG群）
4. 由于本站Ban号条件宽松，Ban号永不解封且没有申诉渠道
5. 60天未完整下载1个种子会导致账号被锁定，可通过邮件自助解锁、

**Comment by luxy25** [comment]
希望适配

**Comment by fzlins** [comment]
#1684
