### ISSUE TITLE
希望能在收藏中增加种子免费时自动下载的功能

### ISSUE THREAD

**Issue by LegendAdmin** [pt-plugins/PT-Plugin-Plus#1702]
## 您的功能请求是否与问题有关？ 请描述一下。

是

## 描述你想要的解决方案

添加一个自带的分组叫“免费时自动下载”，凡是添加了这个分组的种子都会在自动刷新后检测到种子免费时自动发送下载（并且即使设置中的“发送种子时自动开始下载”选项关闭也依然会自动开始下载而不是先暂停）

## 描述您考虑过的替代方案

无

## 其他附加信息

![Snipaste_2024-01-07_03-49-30](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29401874/09a4686c-9e91-4265-9512-e3ac176a6ad1)

**Comment by ted423** [comment]
实现难度较大，请求比较多，需求比较小众，暂不考量
