### ISSUE TITLE
chrome加载扩展程序错误页出很多错误提示

### ISSUE THREAD

**Issue by ma7x** [pt-plugins/PT-Plugin-Plus#1713]
- PT 助手版本:v1.6.1.2522和v1.6.1.2463都存在 2463以前没注意是否存在
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：版本 120.0.6099.225（正式版本） （64 位）

- 问题描述：
扩展程序页报很多错误

- 相关截图：

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/1686980/8cffe7b0-2d07-4523-b2b3-75f0501766f7)

- 重现步骤：
加载文件夹

**Comment by SKzxsk** [comment]
我也是，刚刚重装完系统，唉～

**Comment by fzlins** [comment]
不影响使用
