### ISSUE TITLE
pig站搜索选项有N个，容易造成PTPP崩溃

### ISSUE THREAD

**Issue by submarine111** [pt-plugins/PT-Plugin-Plus#1714]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2501
- PT 助手安装方式：（市场安装，或zip包安装）crx
- 浏览器名称及版本：ie11
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：是
- 问题描述：
ptpp首页搜索，卡或者插件页崩溃自动关闭，再点击不能打开，要关闭IE后才能重新打开。有一定可能是PIG开了二次验证造成的。

- 相关截图：

![微信截图_20240123174319](https://github.com/pt-plugins/PT-Plugin-Plus/assets/62420502/6fc55ee5-9abb-487e-a678-2213bb7d179d)

- 重现步骤：是

**Comment by fzlins** [comment]
无法重现。是不是自定过？删除站点后重现添加。还不行的话，重装插件。

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1535
