### ISSUE TITLE
搜索结果按站点二次排序

### ISSUE THREAD

**Issue by jiezi506** [pt-plugins/PT-Plugin-Plus#1718]
## 您的功能请求是否与问题有关？ 请描述一下。

搜索结果一次排序，可以在最顶上点击大小，上传，下载。。等实现。
但是在一次排序（比如按大小排序）后，原来站点里设置的优先级并不生效，就是同一大小的结果并不能按照优先级排序

## 描述你想要的解决方案

有没有可能增加这个按站点优先级二次排序功能，比如喜欢的站点结果排在前

**Comment by IITII** [comment]
组件不支持
