### ISSUE TITLE
AGSV 同步信息异常

### ISSUE THREAD

**Issue by liuze132** [pt-plugins/PT-Plugin-Plus#1721]
- PT 助手版本:版本 v1.6.1.2535
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Chrome  版本 121.0.6167.160（正式版本） （64 位）
- 浏览器是否安装了其他插件：篡改猴
- 停用其他插件后是否正常工作：否
- 问题描述：
AGSV站点 同步信息异常，明明登录了，点击去登录，跳转后也是显示已登录。

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/15208635/78ab785a-08b6-4937-a46e-98eb13fa9357)

- 重现步骤：
必然出现

**Comment by zyouheng** [comment]
删除CDN列表所有内容即可

**Comment by IITII** [comment]
#1747
