### ISSUE TITLE
v1.6.1.2522可以读取葡萄的做种体积，但是v1.6.1.2545不行

### ISSUE THREAD

**Issue by wind306** [pt-plugins/PT-Plugin-Plus#1733]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2545
- PT 助手安装方式：xpi文件安装
- 浏览器名称及版本：Firefox v123.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：v1.6.1.2522可以读取葡萄的做种体积，但是v1.6.1.2545不行
- 相关截图：无
- 重现步骤：刷新分组数据后必现

**Comment by wind306** [comment]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions



- PT 助手版本:v1.6.1.2545
- PT 助手安装方式：xpi文件安装
- 浏览器名称及版本：Firefox v123.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：v1.6.1.2522可以读取葡萄的做种体积，但是v1.6.1.2545不行

**Comment by SayItDitto** [comment]
有同样的问题，版本v1.6.1.2545，【葡萄】的发种数、做种数、做种体积、时魔信息均无法读取

**Comment by hui-shao** [comment]
经测试，2552 版本的确没问题，此 issue 可以关闭~

**Comment by Mor5oN** [comment]
v1.6.1.2552做种数量显示出错。
