### ISSUE TITLE
搜索框中包含空格时，删除字符的一些奇怪行为

### ISSUE THREAD

**Issue by happyTonakai** [pt-plugins/PT-Plugin-Plus#1734]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: : 1.6.1.2545
- PT 助手安装方式：pre-release crx
- 浏览器名称及版本：Edge Version 122.0.2365.59 (Official build) (64-bit)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
当搜索框中含有空格时，例如`a b`
此时删除空格前面的`a`，会连同空格一起删除，光标会移动到末端；
如果删除空格后面的`b`，也会连同空格一起删除

- 相关截图：
![1](https://github.com/pt-plugins/PT-Plugin-Plus/assets/21305646/e9126041-47d3-4f8b-8449-acec5d0a357b)
![2](https://github.com/pt-plugins/PT-Plugin-Plus/assets/21305646/e164cccb-5594-4e13-a0f1-27dd75311f40)

- 重现步骤：

**Comment by IITII** [comment]
嗯, 默认去除前后空格

**Comment by happyTonakai** [comment]
我觉得提交搜索请求的时候可以去除前后的空格，但是在编辑搜索框的时候没必要去除吧

**Comment by ted423** [comment]
我是觉得这块有问题，删完空格还会自动把光标移到最后，一个没反应过来，搜索词已经全没了
