### ISSUE TITLE
建议：备份增加定时备份功能

### ISSUE THREAD

**Issue by miatry** [pt-plugins/PT-Plugin-Plus#1738]
- 备份服务器需要手动备份，能否加一个定时器定时备份？

**Comment by IITII** [comment]
请自行更新 https://t.me/PTPPAction/1641

<img width="734" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/87a7b355-bd4b-4396-9cf4-93e06306fe2c">
