### ISSUE TITLE
坚果云服务器可连接，但备份参数失败

### ISSUE THREAD

**Issue by Ganya-A** [pt-plugins/PT-Plugin-Plus#1740]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2552zip
- PT 助手安装方式：（市场安装，或zip包安装）zip包
- 浏览器名称及版本：EDGE
- 浏览器是否安装了其他插件：关闭其他插件依然不行
- 停用其他插件后是否正常工作：关闭其他插件依然不行
- 问题描述：
坚果云服务器可连接，但无法备份，显示备份参数失败

- 相关截图：

- 重现步骤：

**Comment by happyTonakai** [comment]
+1

**Comment by QYG2297248353** [comment]
+1

**Comment by wliustc** [comment]
坚果云内手动新建ptpp目录即可

**Comment by QYG2297248353** [comment]
1. Web客户端 创建文件夹
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/56836951/c8547756-b9e9-484c-b550-12d79198cefb)
2. ptpp修改配置
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/56836951/fdcd2522-76ed-486b-b2c4-2c99302d4f37)
完成，即可正常备份
