### ISSUE TITLE
TorrentLeech: 2024年1月1日起做种数和做种体积变为0

### ISSUE THREAD

**Issue by tainewoo** [pt-plugins/PT-Plugin-Plus#1741]
- PT 助手版本: v1.6.1.2552
- PT 助手安装方式：（市场安装）
- 浏览器名称及版本：Microsoft New Edge
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：否
- 问题描述：
TorrentLeech: 2024年1月1日起做种数和做种体积变为0，问题持续至今。
其他数据，如级别，上传，下载，发种数，魔力值等，均正常。
手动浏览页面可以正常打开。

- 相关截图：
![tl_seeding](https://github.com/pt-plugins/PT-Plugin-Plus/assets/13391232/7729158b-e2f2-4f1e-90c4-591ad6b70455)

- 重现步骤：
刷新TorrentLeech数据，查看做种数和做种体积。

**Comment by i990049** [comment]
我这边上不了org都域名，连这个站点的RSS都不能正常接收，下面两个域名我这边可以正常使用，但是ptpp不支持搜索这两个站点
https://www.torrentleech.cc/
https://www.torrentleech.me/

**Comment by tainewoo** [comment]
> 我这边上不了org的域名，连这个站点的RSS都不能正常接收，下面两个域名我这边可以正常使用，但是ptpp不支持搜索这两个站点 https://www.torrentleech.cc/ https://www.torrentleech.me/

在站点设置里将域名添加到该站点的CND列表就可以搜索。
不过2024年1月1日开始，不知道站点页面是不是做过修改，获取不到做种数据了，所以做种数量和大小会是0。之前一直是好的。看了代码好像没啥问题，比较奇怪。

**Comment by tainewoo** [comment]
奇怪，是只有我遇到这个问题么？还是TL太冷门了？

**Comment by tainewoo** [comment]
找到原因了，已提交修复。
