### ISSUE TITLE
"用 PT 助手搜索" 功能能代替站点登录签到吗？

### ISSUE THREAD

**Issue by zizhengwu** [pt-plugins/PT-Plugin-Plus#1746]
- 使用 "用 PT 助手搜索" 功能能代替站点登录签到，不被删除账号吗？

比如如果打开了下面这个界面，能算是登录了 m-team，所以就不用手动再去 m-team 站点登录了吗？

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/2246655/d2a8077f-bb61-43ef-8624-6087ec3f6df5)

**Comment by pwbty** [comment]
成功刷新站点数据，就相当于完成了登录操作。

**Comment by zizhengwu** [comment]
> 成功刷新站点数据，就相当于完成了登录操作。

@pwbty “刷新站点数据”好像是另一个功能吧？我只是"用 PT 助手搜索"，能算登录吗？

**Comment by IITII** [comment]
#27 #13
