### ISSUE TITLE
自動刷新用戶數據功能失效 已經15天未自動刷新數據

### ISSUE THREAD

**Issue by ChenBill900703** [pt-plugins/PT-Plugin-Plus#1750]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:[v1.6.1.2557]
- PT 助手安装方式：xpi/crx安裝
- 浏览器名称及版本：Firefox 123.0.1/Chrome 122
- 浏览器是否安装了其他插件：ublock origin
- 停用其他插件后是否正常工作：否
- 问题描述：
自動刷新用戶數據功能失效 已經10天未自動刷新數據

- 相关截图：
![photo_2024-03-12_14-21-18](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/5bb2d476-b2cb-4d52-90c8-46fc71e9a3f2)

![photo_2024-03-13_12-01-33](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/6f5b7442-8dd6-4363-80d7-5498428e2d1d)

- 重现步骤：
- 設定好之後依然未更新

**Comment by RtYkk** [comment]
@IITII #1722

**Comment by ljcbaby** [comment]
不知道是不是同一个pr导致的，这个pr合并后的pre-release版本自动上传用户数据也不生效

**Comment by IITII** [comment]
1. 『如果浏览器在这个时间之后打开，则打开时自动刷新』 这个功能之前也有问题
2. 自动上传用户数据 只有所有站点都正常刷新了, 才会上传
3. 更新最新版 PTPP, 需要重新安装. 记得备份

**Comment by ChenBill900703** [comment]
> 1. 『如果浏览器在这个时间之后打开，则打开时自动刷新』 这个功能之前也有问题
> 2. 自动上传用户数据 只有所有站点都正常刷新了, 才会上传
> 3. 更新最新版 PTPP, 需要重新安装. 记得备份

不好意思我重裝了8次 了 重灌一次電腦 都無法解決這個問題 我該怎麼樣設定 因為不只有我有這個問題

**Comment by ChenBill900703** [comment]
![擷取](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/398a685b-ee66-4f93-9715-9207ed5e0972)
![擷取1](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/7b00fa1c-b953-4264-a541-84d3652449a9)
重新安裝了整個瀏覽器也是一樣的結果 有誰能夠幫幫我

**Comment by ljcbaby** [comment]
> 1. 『如果浏览器在这个时间之后打开，则打开时自动刷新』 这个功能之前也有问题
> 2. 自动上传用户数据 只有所有站点都正常刷新了, 才会上传
> 3. 更新最新版 PTPP, 需要重新安装. 记得备份

是btschool会被cf盾导致没法触发上传。但确实更新前是能触发上传的，可能是我调过重试时间的关系，后续我再观察一下。

**Comment by ChenBill900703** [comment]
我換到2559之後就正常了 只有Chrome能用 Firefox不能用自動刷新

**Comment by IITII** [comment]
我当时实现和测试的时候, 只参考了 Chrome. 可能是两个支持不一样吧...
你试试不使用 "新版刷新方式" 能不能定时更新 @ChenBill900703

**Comment by ChenBill900703** [comment]
> 我当时实现和测试的时候, 只参考了 Chrome. 可能是两个支持不一样吧... 你试试不使用 "新版刷新方式" 能不能定时更新 @ChenBill900703

我測試過關閉了新版刷新方式在Firefox上依然是沒辦法正常定時更新 確定是Firefox插件的問題 

![擷取2](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/dde27784-e41f-4ae1-a6c8-9ed83b2e355c)

**Comment by IITII** [comment]
@ChenBill900703 更新下, 再试试 https://t.me/PTPPAction/1671

**Comment by ChenBill900703** [comment]
> @ChenBill900703 更新下, 再试试 https://t.me/PTPPAction/1671

謝天謝地 功能已經正常了
![擷取1](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/7d65eaae-176f-453e-b75e-71a20bb44024)

**Comment by ChenBill900703** [comment]
@IITII 

這是1.6.1.2611最新編譯的版本 剛剛測試一下刷新
![擷取1](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/94afeb7f-9363-4939-8b50-f2969ecf661a)

![擷取2](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/615a7cc1-f3d9-4614-8875-977f31a3a520)
設定8:25分更新 只在第二張圖的地方顯示有更新 但是在首頁上並沒有顯示更新

這是1.6.1.2604看起來是正常的
![擷取3](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/b43b70d2-a248-4604-8350-92ef5c52ccb3)
![擷取4](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/67965a0a-4fba-4a6c-81af-d44b82035b45)

我都是乾淨全新安裝的 不是直接更新版本 請幫忙查看一下問題在哪邊謝謝

**Comment by IITII** [comment]
这个定时刷新本来就偶尔不会刷新, 所以才会有新版刷新方式.
新版刷新保证了会定时刷新, 不保证刷新成功
