### ISSUE TITLE
FSM已支持自助申请API，希望能适配

### ISSUE THREAD

**Issue by little6neko** [pt-plugins/PT-Plugin-Plus#1757]
## 描述你想要的解决方案

FSM可以一键申请API了，有效期一个月，大佬有空可以适配一下不
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/34598766/b80d1eba-7abb-4aac-a865-991dee520a59)

**Comment by little6neko** [comment]
调用https://api.fsm.name//Users/infos可以获取到用户数据
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/34598766/10fa720d-4e83-4c40-8b9a-8cfd32700172)

**Comment by little6neko** [comment]
https://api.fsm.name/Torrents/details?tid=种子ID，可以获取到种子信息

**Comment by QYG2297248353** [comment]
支持支持

**Comment by little6neko** [comment]
https://api.fsm.name/Torrents/listTorrents?type=0&systematics=0&tags=[]&keyword=搜索关键字&page=1
种子搜索列表

**Comment by 1299897460** [comment]
支持支持

**Comment by werran2** [comment]
支持支持

**Comment by lk-timeout** [comment]
支持

**Comment by 568145697** [comment]
支持

**Comment by 1299897460** [comment]
> 调用https://api.fsm.name/Users/infos可以获取到用户数据 ![图像](https://private-user-images.githubusercontent.com/34598766/314383705-10fa720d-4e83-4c40-8b9a-8cfd32700172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODU2NDcsIm5iZiI6MTcxMjA4NTM0NywicGF0aCI6Ii8zNDU5ODc2Ni8zMTQzODM3MDUtMTBmYTcyMGQtNGU4My00YzQwLThiOWEtOGNmZDMyNzAwMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE5MTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTkzNTlkODkxNTBmN2YwYzM2ZDZiNDJjNGFiNmY0YmJjM2NmZWI3ODNlYTQwZDYxY2MwNjk1ZGRiYThmZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K8TjaCJqsZ9YBFz_YqYAOscMsieJHWAin6gcwdkceag)

已完成

**Comment by fzlins** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1786
