### ISSUE TITLE
添加蚂蚁pt站点

### ISSUE THREAD

**Issue by xiaocainiao2020** [pt-plugins/PT-Plugin-Plus#1759]
- 站点名称：蚂蚁
- 站点地址：https://hdmayi.com/
- 站点描述：

- 资源类型：
- 开放注册：是/否
- 是否连坐：是/否
- 站点规则：

**Comment by i990049** [comment]
跟帖

https://gamerapt.link/

开放注册，目前无考核

**Comment by lk-timeout** [comment]
蚂蚁好像支持啊

**Comment by fzlins** [comment]
蚂蚁已支持列表中了
