### ISSUE TITLE
适配一下m-team

### ISSUE THREAD

**Issue by nxuu** [pt-plugins/PT-Plugin-Plus#1762]
m-team网站升级改版了 
插件可以升级适配一下么?

**Comment by Rainsheep** [comment]
+1

**Comment by 1299897460** [comment]
+1

**Comment by BuWH** [comment]
+1

**Comment by brotherjie-win** [comment]
我这边提示未登录，不知道其他人是什么情况，kp和xp两个子域名都登录了。点击错误提示的感叹号按钮也能够正确地进入自己的个人页面。

**Comment by paul0261** [comment]
+1

**Comment by chung1912** [comment]
+1

**Comment by Zeal-katou** [comment]
+1

**Comment by Qwerty4401** [comment]
+1

**Comment by feiyu7126** [comment]
> m-team网站升级改版了 插件可以升级适配一下么?

支持下，等待更新支持馒头

**Comment by pikachullk** [comment]
+1

**Comment by zhangchengtnt** [comment]
+1

**Comment by tyejuan** [comment]
M-team改版后，添加种子，提示无效的种子文件。![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/38803512/86fb72e9-3978-4d8d-88ce-1227119b07ff)

**Comment by Dean-Ye** [comment]
+1 辛苦大佬们啦~

**Comment by hualahuala2000** [comment]
支持

**Comment by lingxuejun** [comment]
+1辛苦大佬了

**Comment by lk-timeout** [comment]
辛苦大佬们

**Comment by dongfangshu** [comment]
+1幸苦大佬

**Comment by 1299897460** [comment]
1幸苦大佬

**Comment by RnLuck** [comment]
+1幸苦大佬

**Comment by lsy174915864** [comment]
1幸苦大佬

**Comment by hnotcold** [comment]
+1辛苦大佬们

**Comment by cuimo4183** [comment]
+1幸苦大佬

**Comment by guozhi2005** [comment]
+1幸苦大佬

**Comment by nxuu** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1762
大家用更新的好了么？为什么我还是出不来 快捷下载的菜单呢。。。

**Comment by Focusure** [comment]
> #1762 大家用更新的好了么？为什么我还是出不来 快捷下载的菜单呢。。。 © 栽培者 2024, 版本 v1.6.1.2569

哥们你2569在哪下的啊？我看Releases只到2552

**Comment by tyejuan** [comment]
> #1762 大家用更新的好了么？为什么我还是出不来 快捷下载的菜单呢。。。 © 栽培者 2024, 版本 v1.6.1.2569

还不行，一样的问题，还没有适配好

**Comment by Focusure** [comment]
> > #1762 大家用更新的好了么？为什么我还是出不来 快捷下载的菜单呢。。。 © 栽培者 2024, 版本 v1.6.1.2569
> 
> 还不行，一样的问题，还没有适配好

同没有

**Comment by elefaint** [comment]
+1幸苦大佬

**Comment by voidAspire** [comment]
还有MT站点的图标也加载不出来，去站点设置多次点击重置图标也不行，辛苦大佬
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/16025869/d260db06-4f95-4128-97fc-de539d5d09b4)

**Comment by nxuu** [comment]
© 栽培者 2024, 版本 v1.6.1.2570  m-team的下载菜单还是没有出来 
兄弟们都好了么？这个版本我能看到网站列表里面的m-team的网站图标了

**Comment by hnotcold** [comment]
> © 栽培者 2024, 版本 v1.6.1.2570 m-team的下载菜单还是没有出来 兄弟们都好了么？这个版本我能看到网站列表里面的m-team的网站图标了 浏览器Microsoft Edge 版本 123.0.2420.53 (正式版本) (64 位)

麻烦问下你们是怎么更新的，我的还是1.6.1.2552这个版本呢

**Comment by elefaint** [comment]
> > © 栽培者 2024, 版本 v1.6.1.2570 m-team的下载菜单还是没有出来 兄弟们都好了么？这个版本我能看到网站列表里面的m-team的网站图标了 浏览器Microsoft Edge 版本 123.0.2420.53 (正式版本) (64 位)
> 
> 麻烦问下你们是怎么更新的，我的还是1.6.1.2552这个版本呢

大佬正在适配，action里面有最新提交的编译版本

**Comment by tainewoo** [comment]
MT适配需当心，要改用API token的方式访问。

以下为公告：

https://test2.m-team.cc/api/doc.html#/home
(文档有bug，请求数据格式json/form与实际可能不一致；必传参数可能不准确；建议辅以web调用情况使用)

第三方工具請使用 API Access Token 訪問資料介面：可通过【控制台->實驗室->存取令牌】自助获取
http請求頭中通過：x-api-key傳遞

**注意：自开放API KEY后，如发现第三方工具仍通过cookie访问接口不排除禁用账户的可能**

**Comment by nxuu** [comment]
> > © 栽培者 2024, 版本 v1.6.1.2570 m-team的下载菜单还是没有出来 兄弟们都好了么？这个版本我能看到网站列表里面的m-team的网站图标了 浏览器Microsoft Edge 版本 123.0.2420.53 (正式版本) (64 位)
> 
> 麻烦问下你们是怎么更新的，我的还是1.6.1.2552这个版本呢

最新版本以及功能请登录后从[Action](https://github.com/pt-plugins/PT-Plugin-Plus/actions)里获取。
如何安装和使用，请参考 [Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki) 的详细说明；

**Comment by hnotcold** [comment]
> > > © 栽培者 2024, 版本 v1.6.1.2570 m-team的下载菜单还是没有出来 兄弟们都好了么？这个版本我能看到网站列表里面的m-team的网站图标了 浏览器Microsoft Edge 版本 123.0.2420.53 (正式版本) (64 位)
> > 
> > 
> > 麻烦问下你们是怎么更新的，我的还是1.6.1.2552这个版本呢
> 
> 最新版本以及功能请登录后从[Action](https://github.com/pt-plugins/PT-Plugin-Plus/actions)里获取。 如何安装和使用，请参考 [Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki) 的详细说明；

看到了  感谢~

**Comment by sunxiang0918** [comment]
PT 助手版本: v1.6.1.2575

PT 助手安装方式：手动zip安装

浏览器名称及版本：Microsoft Edge 版本 124.0.2438.2 (正式版本) Dev(arm64)

浏览器是否安装了其他插件：是

停用其他插件后是否正常工作：否

问题描述：
安装了 1.6.1.2575 版本以后, 站点列表中,m-team 还是显示的未登录, 实际上 pt和xp两个都已经登录.

**Comment by mitlearn** [comment]
> PT 助手版本: v1.6.1.2575
> 
> PT 助手安装方式：手动zip安装
> 
> 浏览器名称及版本：Microsoft Edge 版本 124.0.2438.2 (正式版本) Dev(arm64)
> 
> 浏览器是否安装了其他插件：是
> 
> 停用其他插件后是否正常工作：否
> 
> 问题描述： 安装了 1.6.1.2575 版本以后, 站点列表中,m-team 还是显示的未登录, 实际上 pt和xp两个都已经登录.

请删除站点后手动添加 教程参考[这里](https://t.me/ptpluginplus/198)

**Comment by elefaint** [comment]
> PT 助手版本: v1.6.1.2575
> 
> PT 助手安装方式：手动zip安装
> 
> 浏览器名称及版本：Microsoft Edge 版本 124.0.2438.2 (正式版本) Dev(arm64)
> 
> 浏览器是否安装了其他插件：是
> 
> 停用其他插件后是否正常工作：否
> 
> 问题描述： 安装了 1.6.1.2575 版本以后, 站点列表中,m-team 还是显示的未登录, 实际上 pt和xp两个都已经登录.

最新版本已经改用API token，需要在mt的实验室中申请token，并填写到站点参数中。

**Comment by sunxiang0918** [comment]
> > PT 助手版本: v1.6.1.2575
> > PT 助手安装方式：手动zip安装
> > 浏览器名称及版本：Microsoft Edge 版本 124.0.2438.2 (正式版本) Dev(arm64)
> > 浏览器是否安装了其他插件：是
> > 停用其他插件后是否正常工作：否
> > 问题描述： 安装了 1.6.1.2575 版本以后, 站点列表中,m-team 还是显示的未登录, 实际上 pt和xp两个都已经登录.
> 
> 最新版本已经改用API token，需要在mt的实验室中申请token，并填写到站点参数中。

已按教程操作~ 确实能登录,看的到个人信息了~谢谢~~

不过搜索的时候还是返回 "[[M-Team]没有返回预期的数据。](https://xp.m-team.io/)"

**Comment by molichen00** [comment]
PT 助手版本: v1.6.1.2580
PT 助手安装方式：手动crx安装
浏览器名称及版本：Google Chrome 版本 123.0.6312.58（正式版本） （64 位）
浏览器是否安装了其他插件：是
停用其他插件后是否正常工作：否
问题描述：搜索数据M-TEAM生成辅种任务时，M-TEAM的种子都是下载失败。

**Comment by Lloydqiu** [comment]
PT 助手版本: v1.6.1.2580
PT 助手安装方式：手动crx安装

推送到下载服务器提示无效的种子文件，已经去新站点下载过种子

**Comment by ghzh26252** [comment]
+1

**Comment by zhangchengtnt** [comment]
PT 助手版本: v1.6.1.2583
问题已经解决，群晖下载及Qbit均可使用
感谢大佬

**Comment by Rainsheep** [comment]
v1.6.1.2583 封面模式，无法使用

**Comment by FORNOBODYS** [comment]
v1.6.1.2583 馒头配置完，种子页面右边只有打开配置页和封面模式，且封面模式无法打开。同时不像别的站点，缺失了“下载到”和“复制连接”

**Comment by mitlearn** [comment]
> v1.6.1.2583 馒头配置完，种子页面右边只有打开配置页和封面模式，且封面模式无法打开。同时不像别的站点，缺失了“下载到”和“复制连接”

当前2583未支持到Browse界面的一键下载功能 Detail界面的下载到是可用的

**Comment by FORNOBODYS** [comment]
> > v1.6.1.2583 馒头配置完，种子页面右边只有打开配置页和封面模式，且封面模式无法打开。同时不像别的站点，缺失了“下载到”和“复制连接”
> 
> 当前2583未支持到Browse界面的一键下载功能 Detail界面的下载到是可用的

确实，我测试了下每个选项的种子界面都是只有两个选项，但是具体点开任一种子就是标准4选项正常使用的，感谢适配哈，那我等待更多更新，谢谢！

**Comment by Qwerty4401** [comment]
额，怎么更新到v1.6.1.2583，进Action不知道怎么用= =

**Comment by hnotcold** [comment]
> 额，怎么更新到v1.6.1.2583，进Action不知道怎么用= =

进入到action，往下滑，有对应的crx包，下载下来解压以后打开扩展程序页，然后把crx文件拖到扩展程序页面就更新了

**Comment by Dean-Ye** [comment]
PT 助手版本: v1.6.1.2590
PT 助手安装方式：手动zip安装
浏览器名称及版本：Google Chrome 版本 123.0.6312.59（正式版本） （64 位）
浏览器是否安装了其他插件：是
停用其他插件后是否正常工作：否
问题描述：1.搜索界面下载MT种子文件到本地时提示{"message":"Request method 'GET' not supported","data":null,"code":"1"}
                  2.推送MT种子到下载服务器时出现“无效种子文件”提示

**Comment by Qwerty4401** [comment]
> > 额，怎么更新到v1.6.1.2583，进Action不知道怎么用= =
> 
> 进入到action，往下滑，有对应的crx包，下载下来解压以后打开扩展程序页，然后把crx文件拖到扩展程序页面就更新了

我还是等pre-release吧。。看了半天还是不知道怎么搞。。

**Comment by Qwerty4401** [comment]
> > 额，怎么更新到v1.6.1.2583，进Action不知道怎么用= =
> 
> 进入到action，往下滑，有对应的crx包，下载下来解压以后打开扩展程序页，然后把crx文件拖到扩展程序页面就更新了

感谢，好像是找到了，安装试试。。

**Comment by 1299897460** [comment]
PT 助手版本:  v1.6.1.2593
PT 助手安装方式：crx安装
浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
浏览器是否安装了其他插件：是
停用其他插件后是否正常工作：否
问题描述：使用批量下载 100个 成功80个 20个失败疑似api限制 可以调整下下载逻辑么

**Comment by 1299897460** [comment]
PT 助手版本: v1.6.1.2593
PT 助手安装方式：crx安装
浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
浏览器是否安装了其他插件：是
停用其他插件后是否正常工作：否
问题描述：使用批量下载或者批量保存种子后 翻页再次运行 将只会转圈 无反应 需要ctrl+f5 重新刷新网页后才可以再次运行

**Comment by Johnsnow-s** [comment]
其实不要太着急，mt换架构也才几天的事情，慢慢来，给大佬们一下时间

**Comment by QYG2297248353** [comment]
请问：距离发布到 Pre-release 还需要多久

**Comment by IITII** [comment]
> 请问：距离发布到 Pre-release 还需要多久

https://t.me/PTPPAction

**Comment by fangdawei** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/25701701/4176e2e3-0c57-4eb8-9548-84669bc465d3)
种子列表右键发送到下载器好像还没适配，麻烦大佬得空适配下

**Comment by tangguoba** [comment]
+1. Thanks so much in advance!

**Comment by sakth1a** [comment]
bug汇报：使用搜索框搜索时，依然显示[M-Team]没有搜索到相关的种子

**Comment by sakth1a** [comment]
PT 助手版本: v1.6.1.2595
PT 助手安装方式：zip安装
浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
浏览器是否安装了其他插件：是
停用其他插件后是否正常工作：否

bug汇报：使用搜索框搜索时，依然显示[M-Team]没有搜索到相关的种子

**Comment by mitlearn** [comment]
> PT 助手版本: v1.6.1.2595 PT 助手安装方式：zip安装 浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0 浏览器是否安装了其他插件：是 停用其他插件后是否正常工作：否
> 
> bug汇报：使用搜索框搜索时，依然显示[M-Team]没有搜索到相关的种子

请检查鉴权token是否填写 若无该选项请删除站点后手动添加 教程参考[这里](https://t.me/ptpluginplus/198)

**Comment by sakth1a** [comment]
> > PT 助手版本: v1.6.1.2595 PT 助手安装方式：zip安装 浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0 浏览器是否安装了其他插件：是 停用其他插件后是否正常工作：否
> > bug汇报：使用搜索框搜索时，依然显示[M-Team]没有搜索到相关的种子
> 
> 请检查鉴权token是否填写 若无该选项请删除站点后手动添加 教程参考[这里](https://t.me/ptpluginplus/198)

综合页面可以正常搜索，但是9kg页面不行。我仔细看了看，是添加站点的时候，允许搜索选项可选的只有综合，没有其他选项的原因

**Comment by fzlins** [comment]
> > > PT 助手版本: v1.6.1.2595 PT 助手安装方式：zip安装 浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0 浏览器是否安装了其他插件：是 停用其他插件后是否正常工作：否
> > > bug汇报：使用搜索框搜索时，依然显示[M-Team]没有搜索到相关的种子
> > 
> > 
> > 请检查鉴权token是否填写 若无该选项请删除站点后手动添加 教程参考[这里](https://t.me/ptpluginplus/198)
> 
> 综合页面可以正常搜索，但是9kg页面不行。我仔细看了看，是添加站点的时候，允许搜索选项可选的只有综合，没有其他选项的原因

@IITII 有空看看😀

**Comment by IITII** [comment]
1. mt 的分模块搜索参数不一样

**Comment by fzlins** [comment]
还有问题单独开issue吧
