### ISSUE TITLE
已有站点但数据不全 请求修复 rousi rousi.zip

### ISSUE THREAD

**Issue by 1299897460** [pt-plugins/PT-Plugin-Plus#1763]
- 站点名称：肉丝
- 站点地址：https://rousi.zip/index.php
- 站点描述： 影视, 综合, 9KG

- 资源类型：影视, 综合, 9KG
- 开放注册：否

![{317A5D12-029F-4d3f-A03F-CB4A8A91801A}](https://github.com/pt-plugins/PT-Plugin-Plus/assets/35516655/c2ee0343-2d9d-4254-aa70-145fae7bb877)
实际上是支持的但是部分数据不显示

**Comment by guanmengxu** [comment]
保留账号等级和站点也不匹配了。希望更新

**Comment by IITII** [comment]
#1755
