### ISSUE TITLE
馒头更新好无法获取数据，提示“未登录”

### ISSUE THREAD

**Issue by zlhdd108** [pt-plugins/PT-Plugin-Plus#1767]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.0.ba3d87e
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Opera One(版本： 108.0.5067.20)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：是
- 问题描述：
M-team更新后无法获取数据，提示“未登录”

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/16465666/4bb1d56f-06bf-4095-8407-2a0890c3be7f)

- 重现步骤：

**Comment by fzlins** [comment]
#1762
