### ISSUE TITLE
MT侧边栏下载推送问题

### ISSUE THREAD

**Issue by jzbqy** [pt-plugins/PT-Plugin-Plus#1774]
以下问题只针对mt，插件版本为v1.6.1.2591，在谷歌浏览器使用解压版插件和QQ浏览器上使用crx版插件均测试过，mt侧边栏推送下载整页时会丢失部分（大概20条或更多，一页总共100条），我知道侧边栏推送会先解析当页的所有种子id后，再一条一条的推送到qb，所以我都是在qb的任务数不再增加（3-5分钟左右）后再确定推送数量是否正确的；另外就是在种子条目页使用右键推送下载单种时，会提示无效的种子文件，在同一种子的详情页使用侧边栏推送单种则可以成功推送，以上操作均在正确填写密钥、鉴权token后进行。另外删除站点后重新添加也尝试过，同样的错误
大佬们有时间烦请看看能不能修复，当然也有可能是我哪里设置不正确，如果有哪位大佬知道怎么问题所在的话，也麻烦指教一下，感谢

**Comment by BlueSkyClouds** [comment]
@jzbqy 接口限制频繁访问

**Comment by IITII** [comment]
F12 控制台会告诉你一共解析了多条种子, 出错或者触发`频繁访问`后就不再解析.
至于通知, 因为解析后就是直接走的种子推送, 通知会重复, 所以`一共解析了多条种子`并没有单独做通知.

#1762

**Comment by jzbqy** [comment]
了解，感谢大佬们解答
