### ISSUE TITLE
[MT站点问题]火狐浏览器安装2593版本，种子详细页面，下载QB，提示 种子 XXXXXX 下载链接获取失败

### ISSUE THREAD

**Issue by frvery** [pt-plugins/PT-Plugin-Plus#1777]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:2593
- PT 助手安装方式：Actions里面下载crx，上传开发者中心审核后，下载xpi安装
- 浏览器名称及版本：火狐124.0.1 (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：火狐浏览器安装最新的2593版本后，进MT站点种子详细页面，点下载到QB，提示 种子 XXXXXX 下载链接获取失败，不能下载。用edge安装2593版本能正常推送种子。

- 相关截图：
![photo_2024-03-28_22-08-50](https://github.com/pt-plugins/PT-Plugin-Plus/assets/143735815/5a30761c-9560-493e-b170-966797024dd0)

- 重现步骤：

**Comment by IITII** [comment]
开 F12 看下 #1762

**Comment by frvery** [comment]
> 开 F12 看下 #1762



> 开 F12 看下 #1762

![Uploading 微信截图_20240329223914.png…]()

**Comment by frvery** [comment]
> 开 F12 看下 #1762

![微信截图_20240329223914](https://github.com/pt-plugins/PT-Plugin-Plus/assets/143735815/096d5f32-90bd-40cb-9157-b743448048a3)
