### ISSUE TITLE
请求添加DogPT支持

### ISSUE THREAD

**Issue by Rikkalxn** [pt-plugins/PT-Plugin-Plus#1779]
- 站点名称：DogPT
- 站点地址：https://dogpt.cc/
- 站点描述：一个新开的小站，NexusPHP架构，手动添加之后，可以获取部分数据，但是做种体积无法获取

- 资源类型：综合
- 开放注册：是
- 是否连坐：是/否
- 站点规则：

**Comment by fzlins** [comment]
不接受小于6个月站点
