### ISSUE TITLE
使用下载器自动添加分类，会自动生成一个设置分类的目录去下载

### ISSUE THREAD

**Issue by 240722795** [pt-plugins/PT-Plugin-Plus#1780]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2552
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：kiwi
- 浏览器是否安装了其他插件：no
- 停用其他插件后是否正常工作：no
- 问题描述：下载器设置了keep,/pt 下载目录里设置了下载目录/pt，点击下载到/pt后，可以自动添加keep分类，但是下载目录被修改为/pt/keep

- 相关截图：
![Screenshot_20240328_174429_com kiwibrowser browser_edit_439768465430618](https://github.com/pt-plugins/PT-Plugin-Plus/assets/31929493/6b6d19a5-04ff-49df-8a7f-c877e92ecca1)
![Screenshot_20240328_174439_com kiwibrowser browser_edit_439753629771457](https://github.com/pt-plugins/PT-Plugin-Plus/assets/31929493/6a787687-0a18-4865-8c1d-2a81cf98db65)

- 重现步骤：

**Comment by IITII** [comment]
因为你 qb 里面之前没有这个分类. https://github.com/pt-plugins/PT-Plugin-Plus/pull/1588
