### ISSUE TITLE
希望优化“等级”显示，可以显示当前下载 上传量已经达到那个等级或还差多少。

### ISSUE THREAD

**Issue by merlin0531** [pt-plugins/PT-Plugin-Plus#1781]
## 您的功能请求是否与问题有关？ 请描述一下。

希望优化“等级”显示，可以显示当前下载 上传量已经达到那个等级或还差多少。

## 描述你想要的解决方案

在每一个等级后面标注目前上下传流量，和当前等级需求差距，这样方便提前安排上下传量

## 其他附加信息

优化如图所示
![screenshot-1711806907998](https://github.com/pt-plugins/PT-Plugin-Plus/assets/77084268/a8af93aa-2d82-4ba1-bbb8-32a650b038ed)

**Comment by fzlins** [comment]
不会增加这方面的功能。也许next项目会考虑。
