### ISSUE TITLE
支持firefox的xpi是被放弃了么

### ISSUE THREAD

**Issue by jiezi506** [pt-plugins/PT-Plugin-Plus#1784]
## 您的功能请求是否与问题有关？ 请描述一下。
以前好像有过一段时间不支持firefox，后来releases里又有了xpi，这个版本还会有么

**Comment by jdjxk** [comment]
同问

**Comment by mitlearn** [comment]
[已修复](https://github.com/pt-plugins/PT-Plugin-Plus/commit/b13a533bfa2618c512a64ca6205f2b7702189f8e) 请等待下次自动构建
