### ISSUE TITLE
MT 改用 API 加载后历史记录丢失

### ISSUE THREAD

**Issue by bhiaibogf** [pt-plugins/PT-Plugin-Plus#1785]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2595
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chromium Version 121.0.6167.85
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
MT 改用 API 加载后历史记录丢失
- 相关截图：
填写鉴权 token 前
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17107229/45531af7-689b-4dc5-a76e-a03dd9203359)
填写鉴权 token 后
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17107229/f1e998e5-e7db-420a-996a-2626a19191dc)
- 重现步骤：
从旧版本 PPTP 导出配置，在新版本 PPTP 导入配置，此时查看我的数据 MT 历史记录正常，填写填写鉴权 token 后刷新数据，MT 历史记录只剩最新的一次记录。

**Comment by bhiaibogf** [comment]
似乎还有些问题，我从 1.6.1.2595 更换到 1.6.1.2609，同时导出导入数据，更早之前的记录成功载入了，但使用 1.6.1.2595 期间的数据没有载入。我去看了下导出的 userdatas.json，看起来是只载入了 kp.m-team.cc 域名下的记录，而没载入 xp.m-team.io 域名下的记录。

**Comment by IITII** [comment]
升级之后恢复一次数据就行，没有就备份再导入

Zihao Lin ***@***.***> 于 2024年4月9日周二 21:14写道：

**Comment by bhiaibogf** [comment]
我尝试在 1.6.1.2609 导出再导入了一次，还是一样的问题。

有问题的结果如下，mt 改版前（ptpp 2251 版）记录：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17107229/f705b8d6-d112-4837-895c-547128961260)
在此版本做备份得到的 userdatas.json 里 mt 记录在旧域名下。

2595 版记录：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17107229/411afcff-f38f-4b52-a6d4-ad3267fbc48a)
在此版本做备份得到的 userdatas.json 里 mt 记录分布在两个域名下，旧记录在旧域名下，新纪录在新域名下。

2609 版记录：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17107229/060a7e7c-1718-4ff5-9b06-42cda1ff2fde)
在此版本做备份得到的 userdatas.json 里 mt 记录在新域名下，但只有旧记录和当前版本的记录，缺少 2595 版本的记录。

**Comment by IITII** [comment]
升级后记得重启浏览器

Zihao Lin ***@***.***> 于2024年4月9日周二 22:44写道：
