### ISSUE TITLE
torrentleech域名变更

### ISSUE THREAD

**Issue by huchuhan** [pt-plugins/PT-Plugin-Plus#1787]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2595 
- PT 助手安装方式：（市场安装，或zip包安装）zip上传firefox个人插件库安装
- 浏览器名称及版本：firefox124.0.1 (64 位)
- 浏览器是否安装了其他插件：安装了很多其他插件，应该不影响
- 停用其他插件后是否正常工作：
- 问题描述：
torrentleech域名变更 torrentleech.org-->torrentleech.cc

- 相关截图：

- 重现步骤：

**Comment by fzlins** [comment]
提供一下更换域名的官方公告

**Comment by 630975** [comment]
多镜像而已
自己CDN列表加一条就是

**Comment by cng10001** [comment]
如果不影响什么的话 这样填一下就行了
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/115156545/4a982312-4d25-4597-a1af-a6b9f24663a1)

**Comment by huchuhan** [comment]
> 如果不影响什么的话 这样填一下就行了 ![image](https://private-user-images.githubusercontent.com/115156545/320527540-4a982312-4d25-4597-a1af-a6b9f24663a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzUyMjAsIm5iZiI6MTcxMjY3NDkyMCwicGF0aCI6Ii8xMTUxNTY1NDUvMzIwNTI3NTQwLTRhOTgyMzEyLTRkMjUtNDU5Ny1hMWFmLWE2YjlmMjQ2NjNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNTAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmViMTgxNWQ0OTRmYmRjMzc1ZjhlNDkxZDI5NGFiYzNmMjUxZjQyNWY1MDEzNDE2YmMwMzM4ODM1YzE4MjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fC5_RimJ2fkF8JKLtb_YLgLvko8HCaEy8WpkJw6acF4)

没用默认就有这三个
https://www.torrentleech.org/
https://tleechreload.org/
https://torrentleech.cc/
加上 https://www.torrentleech.me/ 也徒劳

**Comment by huchuhan** [comment]
> 如果不影响什么的话 这样填一下就行了 ![image](https://private-user-images.githubusercontent.com/115156545/320527540-4a982312-4d25-4597-a1af-a6b9f24663a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzUyMjAsIm5iZiI6MTcxMjY3NDkyMCwicGF0aCI6Ii8xMTUxNTY1NDUvMzIwNTI3NTQwLTRhOTgyMzEyLTRkMjUtNDU5Ny1hMWFmLWE2YjlmMjQ2NjNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNTAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmViMTgxNWQ0OTRmYmRjMzc1ZjhlNDkxZDI5NGFiYzNmMjUxZjQyNWY1MDEzNDE2YmMwMzM4ODM1YzE4MjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fC5_RimJ2fkF8JKLtb_YLgLvko8HCaEy8WpkJw6acF4)

[![pFON30f.png](https://s21.ax1x.com/2024/04/09/pFON30f.png)](https://imgse.com/i/pFON30f)

[![pFONJAS.png](https://s21.ax1x.com/2024/04/09/pFONJAS.png)](https://imgse.com/i/pFONJAS)

**Comment by huchuhan** [comment]
> 多镜像而已 自己CDN列表加一条就是

没用啊 大佬，轻继续指路。

**Comment by huchuhan** [comment]
现在就是https://www.torrentleech.org/ 访问不了，翻墙也不行，https://www.torrentleech.me/ 可以访问，结果是pt-plugin请求出错。

**Comment by fzlins** [comment]
> 现在就是https://www.torrentleech.org/ 访问不了，翻墙也不行，https://www.torrentleech.me/ 可以访问，结果是pt-plugin请求出错。

cdn放能访问的那个就行了

**Comment by huchuhan** [comment]
> > 现在就是https://www.torrentleech.org/ 访问不了，翻墙也不行，https://www.torrentleech.me/ 可以访问，结果是pt-plugin请求出错。
> 
> cdn放能访问的那个就行了

可以了 谢谢
