### ISSUE TITLE
mt的封面模式没有了

### ISSUE THREAD

**Issue by guohuning** [pt-plugins/PT-Plugin-Plus#1788]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本：v1.6.1.2595
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：360安全浏览器 版本号：15.1.2032.64（64位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否，停用其他所有插件后结果无变化
- 问题描述：
mt最近更新了站点，原版本插件失效，插件更新到最新release后发现封面模式没了

- 相关截图：
![01](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17807825/a94a1d49-dabf-433c-80bb-485b4eb26fbf)

- 重现步骤：
打开网站，在导航栏点击“综合”

**Comment by fzlins** [comment]
新版馒头本身就有瀑布流的功能了，不需要插件支持。

**Comment by guohuning** [comment]
> 新版馒头本身就有瀑布流的功能了，不需要插件支持。

入口在哪，控制台没有找到
