### ISSUE TITLE
Jpop搜索失败

### ISSUE THREAD

**Issue by wysBedoer** [pt-plugins/PT-Plugin-Plus#1789]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [ x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2606
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome123.0.6312.106
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

jpopsuki.eu 发生网络或其他错误。其他站点都可以使用，之前也能用，现在不行了。站点能正常打开。

- 相关截图：

- 重现步骤：

**Comment by IITII** [comment]
你网络问题吧, 先试试能不能正常打开站点

**Comment by wysBedoer** [comment]
已经收到您的邮件啦！辛苦了!祝您生活愉快，学习进步。

**Comment by wysBedoer** [comment]
已经收到您的邮件啦！辛苦了!祝您生活愉快，学习进步。
