### ISSUE TITLE
M-team 馒头显示未登录（实际已登录）

### ISSUE THREAD

**Issue by leic4u** [pt-plugins/PT-Plugin-Plus#1794]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x ] 搜素过Issue，确认没有相关问题
- [ x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 版本 v1.6.1.2608 zip
- PT 助手安装方式：ZIP 包
- 浏览器名称及版本：Chrome 版本 123.0.6312.106（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
M-team 馒头一直都是未登录，其他站点正常

- 相关截图：
![Clip_2024-04-08_23-34-44](https://github.com/pt-plugins/PT-Plugin-Plus/assets/32786903/1f4dfd08-410f-445a-a837-847fc342d486)
![Clip_2024-04-08_23-36-26](https://github.com/pt-plugins/PT-Plugin-Plus/assets/32786903/208e77d0-503e-42f9-8f1a-e81f51d6c924)

- 重现步骤：
馒头更新后就这样了，也不知道咋重现，安装最新 DEV 版本也没用。

**Comment by hui-shao** [comment]
插件的站点设置内的API TOKEN 填了吗？
