### ISSUE TITLE
AGSV不显示做种体积

### ISSUE THREAD

**Issue by ShrikeEIG** [pt-plugins/PT-Plugin-Plus#1795]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:© 栽培者 2024, 版本 v1.6.1.2608
- PT 助手安装方式：（市场安装，或zip包安装）crx安装
- 浏览器名称及版本：chrome，版本 123.0.6312.106（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
站点AGSV正常登录，其他数据包括做种数都能显示，就是缺少做种体积的显示。

- 相关截图：
<img width="869" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/166364339/2c56d8a5-7ddb-4e8b-b6e9-7fe09b560866">

- 重现步骤：刷新不解决问题

**Comment by 0X0000005** [comment]
删除站点设置，重新添加

**Comment by ShrikeEIG** [comment]
> 删除站点设置，重新添加

问题已解决，感谢大佬
