### ISSUE TITLE
建议ratioless站点的数据图表隐藏下载量

### ISSUE THREAD

**Issue by akhzz905** [pt-plugins/PT-Plugin-Plus#1797]
- 对于ratioless的站点，建议在数据图表里把下载量隐藏，然后把纵轴的范围设置成上传量的范围，因为下载量一直是0，会导致上传量的曲线看不出变化。
![图片](https://github.com/pt-plugins/PT-Plugin-Plus/assets/52377847/9f5885c5-2150-4bd0-9212-6b9bcac8163f)

**Comment by IITII** [comment]
指标是可以手动隐藏的, 点下试试?..

<img width="843" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/33705067/a65c3aab-b041-4715-b8c6-0e734dc874f6">
