### ISSUE TITLE
Oldtoons 设置为 unit3D 无效

### ISSUE THREAD

**Issue by marxhsu** [pt-plugins/PT-Plugin-Plus#1798]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

oldtoons.world 前阵子改了新架构，为 unit3D。站点格式选了 unit3D 却无法识别，其他站点类型选项也无效

**Comment by KyokoMiki** [comment]
这好像还真是个bug，oldtoons域名在ptpp中调用的始终是nexusphp的判断是否登录的格式，哪怕手动指定为unit3d的"i.fa-sign-out"，也依然无法把nexusphp的覆盖掉，另外手动指定三个插件也无法起到效果，np的插件依然存在，而且新指定的插件优先级比nexusphp的优先级低。

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/161209740/ebee9705-2791-45ff-872b-e876f00e4d91)

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/161209740/67ccf32c-fbf2-454e-ad7e-4bf20247a34f)

**Comment by i990049** [comment]
我建议PTPP可以自动搜索并且导入unit3D架构的站点，现在外国很多新站都采用这个价格，另外一个是XBTT架构

**Comment by ted423** [comment]
@i990049 基本没有可行性，正常你自定义站点都可以用，但实际上u3d站点就跟安卓样的

**Comment by ted423** [comment]
@i990049 碎片化

**Comment by i990049** [comment]
> XBTT架构



> @i990049 基本没有可行性，正常你自定义站点都可以用，但实际上u3d站点就跟安卓样的

这样吗？那我看最近开放注册的Unit3d架构站点PTPP都能支持，既然都能支持我还以为可以一键导入。那么另外一个很多站点采用的xbtit架构如何？
https://xbtit.eu/

**Comment by ted423** [comment]
@i990049 有人维护就行，没人维护会有很多问题

**Comment by i990049** [comment]
> 这好像还真是个bug，oldtoons域名在ptpp中调用的始终是nexusphp的判断是否登录的格式，哪怕手动指定为unit3d的"i.fa-sign-out"，也依然无法把nexusphp的覆盖掉，另外手动指定三个插件也无法起到效果，np的插件依然存在，而且新指定的插件优先级比nexusphp的优先级低。你可以试着拿这个去试一下，反正我这边是仅靠适配无法解决的。 [config.json](https://github.com/pt-plugins/PT-Plugin-Plus/files/15040899/config.json)
> 
> ![image](https://private-user-images.githubusercontent.com/161209740/323970878-ebee9705-2791-45ff-872b-e876f00e4d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI2MDAsIm5iZiI6MTcxODgwMjMwMCwicGF0aCI6Ii8xNjEyMDk3NDAvMzIzOTcwODc4LWViZWU5NzA1LTI3OTEtNDVmZi04NzJiLWU4NzZmMDBlNGQ5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMzA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGViOTkzZDllNGFlMjIyZmM0ZGJmNWFlNWQwMjMwZTU2ZDFiMDkwY2QyZmI1OWQzYWQ5NzRmNmMzNDJhNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RsztiMcqp6dZRKt_OpyD69Fxe37Bd7XNL6JX-hkZQzE)
> 
> ![image](https://private-user-images.githubusercontent.com/161209740/323971362-67ccf32c-fbf2-454e-ad7e-4bf20247a34f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI2MDAsIm5iZiI6MTcxODgwMjMwMCwicGF0aCI6Ii8xNjEyMDk3NDAvMzIzOTcxMzYyLTY3Y2NmMzJjLWZiZjItNDU0ZS1hZDdlLTRiZjIwMjQ3YTM0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMzA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGFhNWVkNTg0MjQ4YjViNmM1YjQ0MjgyNTAxYjNkZTI3NTAwZDc2N2Q4ZmZiMzg1OGQzYTgyMzdkYzFhODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8AZF2L4WB0SJWWMsGCx_2hFCA6upPCg_nuA93SxJbHw)

把这些跟oldtoons有关代码全部删了不行吗？现在2677版根本不显示搜索结果了，其他随便一个unit3d站点都没问题

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/blob/25458c94593ab404a2259794f822a7bea1caf630/resource/sites/oldtoons.world/config.json

**Comment by ted423** [comment]
最早有人用np添加过
