### ISSUE TITLE
1.6.1.2617版本 啟用自動更新數據 時間到了之後 數據不會自動更新 但會顯示上次更新時間 此問題在1.6.1.2604不存在

### ISSUE THREAD

**Issue by ChenBill900703** [pt-plugins/PT-Plugin-Plus#1802]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2617
- PT 助手安装方式：xpi自行編譯安裝
- 浏览器名称及版本：Firefox 124.0.2
- 浏览器是否安装了其他插件：ublock origin
- 停用其他插件后是否正常工作：不行

- 问题描述：
1.6.1.2617版本 啟用自動更新數據 時間到了之後 數據不會自動更新 但會顯示上次更新時間

![擷取1](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/57ab6df6-f938-412d-85ef-f87f65bec081)

![擷取2](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/04e18d01-2ddb-49a6-af47-a1961054519c)

- 相关截图：
1.6.1.2604此問題未發生 

![擷取1](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/4185823c-da9f-402c-b22a-06dba164d770)

![擷取2](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/1724c7d1-f156-42c8-9fa8-6f01f7fd9c08)

- 重现步骤：

上面已經寫好

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1750#issuecomment-1995106526
