### ISSUE TITLE
M-Team站点一直显示没有登录

### ISSUE THREAD

**Issue by zxf8665905** [pt-plugins/PT-Plugin-Plus#1809]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2614
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome 版本 123.0.6312.122（正式版本） (x86_64)
- 浏览器是否安装了其他插件：没有按照其他pt插件
- 停用其他插件后是否正常工作：
- 问题描述：M-Team站点一直显示没有登录，pt助手卸载重新安装，配置都清掉重新添加，mt退出重新登录都不行

- 相关截图：

- 重现步骤：

**Comment by wiiii** [comment]
我的数据一直显示未登录
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/16551444/58d69cd8-a500-4398-97db-6534c8771231)
下载的时候显示 未设置AuthToken，请先设置AuthToken 
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/16551444/f4f53ec3-96d4-480f-9b31-a7ea511cffcb)

**Comment by zackfill** [comment]
Mteam-控制台-实验室-建立存取令牌，复制令牌到站点设置-编辑站点-鉴权token-保存

**Comment by zxf8665905** [comment]
> Mteam-控制台-实验室-建立存取令牌，复制令牌到站点设置-编辑站点-鉴权token-保存

👍 多谢，搞定了

**Comment by tanghulu0608** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/5561864/132587bf-e693-4640-95e3-d95587d69279)

为什么我在填了令牌后，这确认按钮变灰了

**Comment by mitlearn** [comment]
> ![image](https://private-user-images.githubusercontent.com/5561864/327037137-132587bf-e693-4640-95e3-d95587d69279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MzI1MTEsIm5iZiI6MTcxNDUzMjIxMSwicGF0aCI6Ii81NTYxODY0LzMyNzAzNzEzNy0xMzI1ODdiZi1lNjkzLTQ2NDAtOTVlMy1kOTU1ODdkNjkyNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDI1NjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVkNzg5ZWM5OTJjMTI4ZGVmNWIzZThlZDE5OTdmZTI3YTA2YmE5MTk5MmQ0ZWRkYTA2MWQ3ZDRjNWRhNzdjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yEd03qfDaWK0aJ4Sex3acXO1x4jGSWifSLAlIFX1BQ4)
> 
> 为什么我在填了令牌后，这确认按钮变灰了

请参考[教程](https://t.me/ptpluginplus/198)

**Comment by tanghulu0608** [comment]
> > ![image](https://private-user-images.githubusercontent.com/5561864/327037137-132587bf-e693-4640-95e3-d95587d69279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MzI1MTEsIm5iZiI6MTcxNDUzMjIxMSwicGF0aCI6Ii81NTYxODY0LzMyNzAzNzEzNy0xMzI1ODdiZi1lNjkzLTQ2NDAtOTVlMy1kOTU1ODdkNjkyNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDI1NjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVkNzg5ZWM5OTJjMTI4ZGVmNWIzZThlZDE5OTdmZTI3YTA2YmE5MTk5MmQ0ZWRkYTA2MWQ3ZDRjNWRhNzdjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yEd03qfDaWK0aJ4Sex3acXO1x4jGSWifSLAlIFX1BQ4)
> > 为什么我在填了令牌后，这确认按钮变灰了
> 
> 请参考[教程](https://t.me/ptpluginplus/198)

搞定，谢谢

**Comment by tudan110** [comment]
为什么我的界面里没有“鉴权token”这一项

**Comment by mitlearn** [comment]
> 为什么我的界面里没有“鉴权token”这一项

请阅读[教程](https://t.me/ptpluginplus/198)
