### ISSUE TITLE
MT无法使用imdb的id来搜索

### ISSUE THREAD

**Issue by zxf8665905** [pt-plugins/PT-Plugin-Plus#1811]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: © 栽培者 2024, 版本 v1.6.1.2614 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 版本 123.0.6312.124（正式版本） (x86_64)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：-
- 问题描述：MT无法使用imdb的id来搜索

- 相关截图：
![iShot_2024-04-17_11 20 15](https://github.com/pt-plugins/PT-Plugin-Plus/assets/9147295/a0af44b0-633c-4730-9d80-d195271f9171)

- 重现步骤：使用imdb的id搜索即可复现

**Comment by Dean-Ye** [comment]
马克

**Comment by trim21** [comment]
> 马克

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/13553903/5b5e2574-6e27-43b8-8ceb-dc1e8b89ac84)

用这个
