### ISSUE TITLE
右键下载不显示下载目录

### ISSUE THREAD

**Issue by fangdawei** [pt-plugins/PT-Plugin-Plus#1817]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 2611
- PT 助手安装方式：crx
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：不行
- 问题描述：mteam下（目前只有mteam，其他站点无法验证），种子列表页，右键下载，不显示下载目录，只显示下载服务器

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/25701701/d0b5d5a3-b05b-4295-adf9-adbcbae31c7c)

- 重现步骤：种子列表，右键

**Comment by FORNOBODYS** [comment]
我有同样的问题，是最新版的chrome浏览器。PT助手版本是2614。与此同时，那个把种子拖动到右边菜单栏，然后触发“下载到” 这样的方式也不行，右下角没有那个发送种子的框。但是在单个种子的页面，右边侧栏是完全可用的。

**Comment by Pandaaaa906** [comment]
一样

**Comment by IITII** [comment]
更新 1023148ed4b3cb4d9d7dc0e7778a3efff45a7f9b

t.me/PTPPAction
