### ISSUE TITLE
My Data里refresh group data时M-Team总是显示“Not logged”

### ISSUE THREAD

**Issue by weikdg** [pt-plugins/PT-Plugin-Plus#1818]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2614
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Chrome 124.0.6367.61 (Official Build) (64-bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by weikdg** [comment]
![SharedScreenshot](https://github.com/pt-plugins/PT-Plugin-Plus/assets/7565240/18c2b363-42bb-4826-a846-5326e77f19cb)

**Comment by IITII** [comment]
删除后重新添加站点

**Comment by weikdg** [comment]
昨天试过您说的这个方法了，刚才又试了一遍还是不行。我也试过chrome里的“clear browsing data”。这些都不起作用。其他的站点就没有这个问题。我开始是在edge里遇到这个问题，看到你们的新版本解决了这个问题。我手工在chrome安装的最新版本的插件。但是还是不行。

**Comment by IITII** [comment]
https://t.me/ptpluginplus/198 检查下 token 有没有填写
