### ISSUE TITLE
搜索中的 `.`(dot) 被替换为了 ` `（空格）

### ISSUE THREAD

**Issue by trim21** [pt-plugins/PT-Plugin-Plus#1822]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [X] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [X] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [X] 搜素过Issue，确认没有相关问题

- PT 助手版本: dev
- PT 助手安装方式：自行编译
- 浏览器名称及版本：chrome 124
- 浏览器是否安装了其他插件：无关
- 停用其他插件后是否正常工作：无关
- 问题描述：

- 相关截图：

`Band Four 2023 Blu-ray 1080p AVC TrueHD 5.1` 搜索不到可用数据

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/13553903/ecf72a7b-fe6d-44e2-a011-2ebd3f876185)

在关键词里面，`.` 被替换为了 ` `

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/13553903/00b384fa-bc4c-40ee-99d8-b4bf96fb72dc) 

- 重现步骤：添加任意支持搜索的站点
- 搜索任意带 `.` 的搜索词
- 发现实际的搜索请求里面 `.` 被替换为了空格

https://github.com/pt-plugins/PT-Plugin-Plus/blob/ec3af00df1bbb9a920b0c0b860391a384f1b4685/src/background/searcher.ts#L150

**Comment by IITII** [comment]
// 2019.6.26 refactor: 调整搜索方式，”." 转为空格以获取更多搜索结果
      // 实际测试过程中, np 架构能正常返回, 但是 mt 架构无法返回结果. 从搜索关键词来说这里的替换没有必要
