### ISSUE TITLE
（馒头）使用搜索框搜索馒头的种子，实际存在的种子搜索不到。

### ISSUE THREAD

**Issue by FORNOBODYS** [pt-plugins/PT-Plugin-Plus#1829]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ √] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ √] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ √] 搜素过Issue，确认没有相关问题
- [ √] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1 2623
- PT 助手安装方式：（市场安装，或zip包安装）crx
- 浏览器名称及版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：使用搜索框搜索种子时，实际存在的种子搜索不到。但是实际上这个种子是存在的。当我把站点选中所有时，能看到同个种子在其他站被搜索到，但是唯独馒头这边的这个种子搜索不到。可能是因为馒头的搜索出了问题？

- 相关截图：
![WeChat截图_20240501115014](https://github.com/pt-plugins/PT-Plugin-Plus/assets/165010776/1a1ca9a8-50be-45c8-a3bb-b606c6404ecd)

![WeChat截图_20240501115037](https://github.com/pt-plugins/PT-Plugin-Plus/assets/165010776/6a9e74d4-c9f7-44eb-805c-acb89bb92f8a)

- 重现步骤：随便搜索一下对比下就会重现，重现概率很大。除了一些置顶的能搜索到以外，其他在PTPP搜索栏一概搜索不到。

**Comment by LLIce** [comment]
不知道为什么，我现在馒头点下载就提示AuthToken未设置，去我的数据里看状态显示未登录，登几次还是未登录。

**Comment by trim21** [comment]
原因： https://github.com/pt-plugins/PT-Plugin-Plus/issues/1822
