### ISSUE TITLE
观众不能显示发布数、做种数、保种体积

### ISSUE THREAD

**Issue by torch132** [pt-plugins/PT-Plugin-Plus#1830]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x ] 搜素过Issue，确认没有相关问题
- [ x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2614 
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
`v1.6.1.2595`和`v1.6.1.2614`不能更新出观众的发布数、做种数、保种体积。
尝试过：
 - 刷新
 - 删除站点重新添加
 - 更新到最新版本
以上办法都不能解决问题。

- 相关截图：
![](https://zotore-test.oss-cn-hangzhou.aliyuncs.com/img/iShot_2024-05-01_23.47.56.jpg)

- 重现步骤：刷新不出来

**Comment by trim21** [comment]
ref: https://github.com/pt-plugins/PT-Plugin-Plus/pull/1827
