### ISSUE TITLE
家园的列表页无法通过侧边栏和右键菜单下载

### ISSUE THREAD

**Issue by jzbqy** [pt-plugins/PT-Plugin-Plus#1832]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [√] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [√] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [√] 搜素过Issue，确认没有相关问题
- [√] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2623
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Google Chrome浏览器 124.0.6367.119（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

(HD)家园的列表页无法通过侧边栏和右键菜单下载（详情页可正常通过侧边栏下载），尝试在ptpp主页面获取各站首页种子，该站能成功获取，但依然无法正常推送到下载器（qb）

补充：
1.操作前已在该站手动下载过种子文件，已在站点设置中填入密钥，其他站点均正常使用
2.当在种子列表页批量推送时，会正常提示进度，进度结束后也会显示推送成功，但实际上并未在下载器（qb）里成功创建任务
3.以上操作多次尝试均为相同情况

- 相关截图：
![ptpp主页报错](https://github.com/pt-plugins/PT-Plugin-Plus/assets/126179646/9a6fddc1-fa17-4569-9f09-a35effca200b)
![列表页报错](https://github.com/pt-plugins/PT-Plugin-Plus/assets/126179646/f600ab4a-fe8a-4cb7-8540-81caf7431846)

- 重现步骤：

**Comment by IITII** [comment]
无法复现, 请补充相关日志, 参考 https://github.com/pt-plugins/PT-Plugin-Plus/blob/dev/dev.md#ptpp-%E5%90%8E%E7%AB%AF%E6%97%A5%E5%BF%97%E6%9F%A5%E7%9C%8B
