### ISSUE TITLE
馒头主域名问题

### ISSUE THREAD

**Issue by yatounoneko** [pt-plugins/PT-Plugin-Plus#1836]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2623 
- PT 助手安装方式：zip
- 浏览器名称及版本：Chrome 124.0.6367.119
- 浏览器是否安装了其他插件：~
- 停用其他插件后是否正常工作：~
- 问题描述：主域名xp.xxxxxx.io因站点原因已经取消，会导致获取资料失败。建议使用kp或其他域名

- 相关截图：鉴于站点不可言之规定添加打码，请见谅
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/22129910/ee808a89-5b53-43cc-8d60-b7939eda258a)

- 重现步骤：添加新站点即可重现

**Comment by DewittBlack** [comment]
可以在插件的文件夹里修改MT的配置，路径PT-Plugin-Plus-1.6.1.2623\resource\systemConfig.json，修改systemConfig.json中配置的MT域名，按ctrl+R将所有 xp.m-team.io 替换成 kp.m-team.cc ，然后文件内搜索这个域名，删除cdn里面多余的一个kp.m-team.cc
![mt](https://github.com/pt-plugins/PT-Plugin-Plus/assets/141751862/f945d489-0e71-4573-9684-754f70c8d4fd)

**Comment by DewittBlack** [comment]
可以在插件的文件夹里修改MT的配置，路径PT-Plugin-Plus-1.6.1.2623\resource\systemConfig.json，修改systemConfig.json中配置的MT域名，按ctrl+R将所有 xp.xxxxx.io 替换成 kp.xxxxx.cc ，然后文件内搜索这个域名，删除cdn括号里面多余的一个kp.xxxxxx.cc，还需要在PT-Plugin-Plus-1.6.1.2623\resource\sites文件夹底下找到馒头xp开头域名的文件夹，将文件夹名称改成kp.xxxxxx.cc，然后点进文件夹，将里面config.json文件中的域名也全部替换成kp.xxxxxxx.cc域名

**Comment by IITII** [comment]
更新 ptpp, 删除重新添加站点

**Comment by yatounoneko** [comment]
> 可以在插件的文件夹里修改MT的配置，路径PT-Plugin-Plus-1.6.1.2623\resource\systemConfig.json，修改systemConfig.json中配置的MT域名，按ctrl+R将所有 xp.xxxxx.io 替换成 kp.xxxxx.cc ，然后文件内搜索这个域名，删除cdn括号里面多余的一个kp.xxxxxx.cc，还需要在PT-Plugin-Plus-1.6.1.2623\resource\sites文件夹底下找到馒头xp开头域名的文件夹，将文件夹名称改成kp.xxxxxx.cc，然后点进文件夹，将里面config.json文件中的域名也全部替换成kp.xxxxxxx.cc域名

我就说我改完怎么还会自己变回去，原来\resource\systemConfig.json也要改，感谢！

**Comment by yatounoneko** [comment]
> 更新 ptpp, 删除重新添加站点

抱歉，v1.6.1.2623是在指Github上的版本
