### ISSUE TITLE
火狐2628版本安装完打开配置，显示“加载配置失败？？Options.readConfig.Error”

### ISSUE THREAD

**Issue by misamai** [pt-plugins/PT-Plugin-Plus#1840]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by frvery** [comment]
同样问题，安装2627也是一样报错，安装2626没这问题

**Comment by IITII** [comment]
1. 回滚
2. 备份配置
3. 卸载重装插件
4. 恢复配置

https://github.com/pt-plugins/PT-Plugin-Plus/pull/1827#issuecomment-2094649970

**Comment by frvery** [comment]
> 1. 回滚
> 
>     2. 备份配置
> 
>     3. 卸载重装插件
> 
>     4. 恢复配置
> 
> 
> [#1827 (comment)](https://github.com/pt-plugins/PT-Plugin-Plus/pull/1827#issuecomment-2094649970)

试了，还是没用

**Comment by IITII** [comment]
请补充相关日志, 参考 https://github.com/pt-plugins/PT-Plugin-Plus/blob/dev/dev.md#ptpp-%E5%90%8E%E7%AB%AF%E6%97%A5%E5%BF%97%E6%9F%A5%E7%9C%8B

**Comment by misamai** [comment]
控制界面都打不开 无法导出日志 而且我是火狐不是CHROME 菜单不一样

**Comment by misamai** [comment]
![4141](https://github.com/pt-plugins/PT-Plugin-Plus/assets/22916110/a47a9ce3-a716-427d-9285-280ef65d7245)
截图给你看吧
