### ISSUE TITLE
TL 搜索里时间显示错误

### ISSUE THREAD

**Issue by zdm9981** [pt-plugins/PT-Plugin-Plus#1846]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2644
- PT 助手安装方式：（市场安装，或zip包安装） zip
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

TL 搜索里时间显示错误
怀疑是由于在TL网站里已经设置了时区为+8导致的
- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/3750564/6d978b0e-75d2-4d71-b84e-b852d3368859)

- 重现步骤：

**Comment by trim21** [comment]
在站点设置里改一下时区试试？

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/13553903/c70aa98b-1d87-473b-a05c-a578d539e08b)
