### ISSUE TITLE
希望完善两台电脑数据同步功能

### ISSUE THREAD

**Issue by dzbl04230302** [pt-plugins/PT-Plugin-Plus#1848]
## 您的功能请求是否与问题有关？ 请描述一下。

公司和家里两台电脑，浏览器都安装了PTPP插件，都设置了备份服务器，现在想要保持两台电脑的PTPP数据同步（主要是站点上传下载量）只能每天在两台电脑上手动点击备份和恢复，无法自动实现两端同步

## 描述你想要的解决方案

希望增加两端/多端数据自动同步功能

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1581

**Comment by fqh1995** [comment]
我也有这种需求，尤其是多端同步的问题，安卓、pc
