### ISSUE TITLE
Audiences站做种体积显示为0

### ISSUE THREAD

**Issue by fx1492** [pt-plugins/PT-Plugin-Plus#1849]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2645
- PT 助手安装方式：（市场安装，或zip包安装）ZIP包安装
- 浏览器名称及版本：Microsoft Edge 版本 124.0.2478.80 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
Audiences站做种体积显示为0，但时魔、上传、下载等数据正常。

- 相关截图：
![数据截图](https://github.com/pt-plugins/PT-Plugin-Plus/assets/165245666/bfd347fc-d863-4a94-ba95-edb9ace85e25)

- 重现步骤：

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/pull/1827
