### ISSUE TITLE
馒头站点无法获取种子列表

### ISSUE THREAD

**Issue by torashen** [pt-plugins/PT-Plugin-Plus#1855]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

小弟刚刚入坑，添加馒头获取种子列表报错， 请教下是什么原因。谢谢大佬
![1715247688829](https://github.com/pt-plugins/PT-Plugin-Plus/assets/153890345/38149d70-4298-4c3c-bd46-7ae98ff6eac4)

**Comment by trim21** [comment]
ptpp什么版本？

**Comment by answerster** [comment]
v1.6.1.2645

**Comment by torashen** [comment]
1.6.1.2623

**Comment by answerster** [comment]
<img width="603" alt="iShot_2024-05-10_19 12 38" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/53866530/53d93a73-8000-4497-88ac-210424c936ee">

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1858#issuecomment-2104388962
