### ISSUE TITLE
学校更新数据出错

### ISSUE THREAD

**Issue by raycollab** [pt-plugins/PT-Plugin-Plus#1856]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 版本 v1.6.1.2625
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：Microsoft Edge 124.0.2478.51 (正式版本) (arm64)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
学校更新个人数据，提示出现错误，没法正常更新

- 相关截图：

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/61900092/ece05d57-44db-4bd1-9fd2-0867c2f1f0e3)

- 重现步骤：

**Comment by ted423** [comment]
手动打开下页面，可能对面开了cf盾

**Comment by starsjf** [comment]
> 手动打开下页面，可能对面开了cf盾

我的学校也出问题了，可以打开学校网页，但是一直状态是发生错误。是否需要重新登录一下？更新下cookie？

**Comment by chenbi001** [comment]
> 手动打开下页面，可能对面开了cf盾

手动打开能正常登录，但插件无法获取数据，提示“发生错误”，这个情况从7天前开始。

**Comment by chenbi001** [comment]
> > 手动打开下页面，可能对面开了cf盾
> 
> 我的学校也出问题了，可以打开学校网页，但是一直状态是发生错误。是否需要重新登录一下？更新下cookie？

我试过了，更新了cookie也没用
