### ISSUE TITLE
石墨，保种体积，以及入站时间无法获取

### ISSUE THREAD

**Issue by TAN-Z-H** [pt-plugins/PT-Plugin-Plus#1857]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2651
- PT 助手安装方式：使用action中.crx直接安装
- 浏览器名称及版本：edge 124.0.2478.80 X64
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
从45版本更新51#open后，此时还没刷新数据就已经无法显示标题所示，刷新之后也不行

- 相关截图：
- 
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/70757024/604d277c-79a8-42a1-894a-3d0a5439094c)

- 重现步骤：
从45版本更新51#open后

**Comment by TAN-Z-H** [comment]
经过测试，在1.6.1.2647以后的版本都有上述问题

**Comment by IITII** [comment]
无法复现, 请补充相关日志, 参考 https://github.com/pt-plugins/PT-Plugin-Plus/blob/dev/dev.md#ptpp-%E5%90%8E%E7%AB%AF%E6%97%A5%E5%BF%97%E6%9F%A5%E7%9C%8B

**Comment by TAN-Z-H** [comment]
> 无法复现， 请补充相关日志， 参考 https://github.com/pt-plugins/PT-Plugin-Plus/blob/dev/dev.md#ptpp-%E5%90%8E%E7%AB%AF%E6%97%A5%E5%BF%97%E6%9F%A5%E7%9C%8B

是否为这个
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/70757024/c94b0037-6ab5-4aeb-bfaa-805079ffc258)


因为实在不太懂，再描述一次我的复现步骤：在上述浏览器版本下，从47版直接升级至47之后的版本，刷新数据之后可以在数据总览发现做种体积等数据已经与先前的对不上了。重启浏览器后，大部分做种体积、石墨等消失，如最上面图所示。但是chrome经过测试似乎不存在此问题。

**Comment by mitlearn** [comment]
> > 无法复现， 请补充相关日志， 参考 https://github.com/pt-plugins/PT-Plugin-Plus/blob/dev/dev.md#ptpp-%E5%90%8E%E7%AB%AF%E6%97%A5%E5%BF%97%E6%9F%A5%E7%9C%8B
> 
> 是否为这个 ![image](https://private-user-images.githubusercontent.com/70757024/330255055-c94b0037-6ab5-4aeb-bfaa-805079ffc258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTM0MjUsIm5iZiI6MTcxNTY1MzEyNSwicGF0aCI6Ii83MDc1NzAyNC8zMzAyNTUwNTUtYzk0YjAwMzctNmFiNS00YWViLWJmYWEtODA1MDc5ZmZjMjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyMTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYzk1MDNlNmNlODdmOTVhZWNhNmMzZTJkOTY2ZDJiYmVjNWEzNTdlZDczNDJiYTJlZTFkYzBlZDJjZTI2MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bGsUG6wWQpo_5P3mm7P-N6_xYIzrB3n_wESUpDHNEDI)
> 
> 因为实在不太懂，再描述一次我的复现步骤：在上述浏览器版本下，从47版直接升级至47之后的版本，刷新数据之后可以在数据总览发现做种体积等数据已经与先前的对不上了。重启浏览器后，大部分做种体积、石墨等消失，如最上面图所示。但是chrome经过测试似乎不存在此问题。此问题在我的设备上100%重现。

打开PTPP右下角调试 而后刷新一次数据 再将调试页截图
并且在左侧边栏 找到日志 截图

**Comment by SayItDitto** [comment]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions



- PT 助手版本: v1.6.1.2655
- PT 助手安装方式：（市场安装，或zip包安装）actions中的crx安装
- 浏览器名称及版本：Chrome v124.0.6367.158
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
同无法获取大部分站点的发布数、做种数、做种体积、时魔、入站时间。
只有ZHUQUE的所有数据正确获取了。M-Team和FSM的入站时间可以获取，其余也无法获取。部分站点如PTer、憨憨可以获取做种数和做种体积，其余无法获取。
2651和2655版本都遇到了这个问题。
调试信息页面点开显示“无法访问您的文件 该文件可能已被移至别处、修改或删除。”所以暂时无法提供调试页截图。

- 相关截图：
![Snipaste_2024-05-14_12-11-18](https://github.com/pt-plugins/PT-Plugin-Plus/assets/123747090/df786663-f78d-4497-85eb-8b509388ee7f)

- 重现步骤：
安装新版本刷新数据后出现

**Comment by UrsaBear** [comment]
同样遇到了这个问题，刷新站点时背景页日志如下
![QQ截图20240514133407](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29115485/91ff6ac5-7829-4520-b276-22fc936a0246)

**Comment by UrsaBear** [comment]
同样遇到了这个问题，刷新站点时背景页日志如下
![QQ截图20240514133407](https://github.com/pt-plugins/PT-Plugin-Plus/assets/29115485/512fd259-92c3-48fb-add6-aa73572d1d86)
插件主页右下角“调试信息”按钮打开以后是404，故无法提供相关日志

**Comment by yuguansu** [comment]
5月11日发布的dev2657版本可以读取站点数据，其他版本均不行（已尝试265x所有版本，截止到今天2658版本）

**Comment by AaronC-Alpha** [comment]
问题相同，发布数、做种数、做种体积、时魔、入站时间均无法获取
