### ISSUE TITLE
无法获取m-team账号信息，显示未登录

### ISSUE THREAD

**Issue by EvanZhangJ** [pt-plugins/PT-Plugin-Plus#1858]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2623
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：chrome 124.0.6367.119
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：无法获取m-team账号信息，显示未登录

- 相关截图：

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/124326662/bee9867d-ec03-4cb4-9b58-962380ee60c8)
实际已登录

- 重现步骤：

**Comment by RtYkk** [comment]
https://t.me/s/ptpluginplus/198

**Comment by ted423** [comment]
新版需要删掉重新添加，并且实验室那里获取鉴权token
另外有二级域名被取消，cdn那里要改成现在在用的
