### ISSUE TITLE
kamept站，在开启“发送种子时将小写站点名添加到标签”功能后，会导致错误以至QB默认webui内的右键失效

### ISSUE THREAD

**Issue by lurne** [pt-plugins/PT-Plugin-Plus#1859]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.2623
- PT 助手安装方式：zip包
- 浏览器名称及版本：Chrome 124, EDGE 124
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：kamept站，在开启“发送种子时将小写站点名添加到标签”功能后，会导致错误以至QB默认webui内的右键失效。因为标签名称为“kamept ”，以及下载路径的背后都多了一个空格。不知道其他站点是否有相同的问题，望大佬们辛苦一下下，尽快修复！

**Comment by IITII** [comment]
提问之前, 请升级最新版本验证是否复现. 这 bug 修了快 3 月了=.=

**Comment by lurne** [comment]
> 提问之前, 请升级最新版本验证是否复现. 这 bug 修了快 3 月了=.=

抱歉，很久没上TG索取新版本了……
