### ISSUE TITLE
站点“学校btschool”无法正常登录和读取个人信息。

### ISSUE THREAD

**Issue by yourvid** [pt-plugins/PT-Plugin-Plus#1863]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2656
- PT 助手安装方式：crx安装（市场安装，或zip包安装）
- 浏览器名称及版本：谷歌浏览器124.0.6367.119（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
站点“学校”无法正常登录和读取个人信息。

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33681727/b96e14ad-cf8f-42fb-bf58-8c435e75f3c3)

- 重现步骤：
站点“学校”无法正常登录和读取个人信息，之前都是正常的。

**Comment by yourvid** [comment]
站点能正常打开，但是PT助手读取不到插件。不知和cf验证是否有关？

**Comment by chenbi001** [comment]
我也是这情况，提示未知错误，重新登录也没用，手动打开PT站点再刷新也没用。

**Comment by ted423** [comment]
@chenbi001 突然想起来，站点cookies清过试过没？或者回退扩展版本可以不

**Comment by chenbi001** [comment]
> @chenbi001 突然想起来，站点cookies清过试过没？或者回退扩展版本可以不

清过cookies，没用。回退没试。

**Comment by merlin0531** [comment]
同样“未知错误”已4天 更换多个版本无效（2654 、2633） 目前使用v1.6.1.2657

**Comment by trim21** [comment]
因为学校自己设置了很高的cf盾

**Comment by valianliu** [comment]
> 因为学校自己设置了很高的cf盾

的确是这样的。。。这种是不是就无解了？

**Comment by Zeaglefly** [comment]
这几天又无法获取用户信息了

**Comment by declandragon** [comment]
> 这几天又无法获取用户信息了

+1

**Comment by zhd-love** [comment]
+1

**Comment by ted423** [comment]
话题我先锁了，因为开高cf盾这种基本无法处理。+1这种回复只会骚扰收消息的人
