### ISSUE TITLE
Firefox 附加组件商店版本是否为官方发布版本？

### ISSUE THREAD

**Issue by leic4u** [pt-plugins/PT-Plugin-Plus#1866]
https://addons.mozilla.org/zh-CN/firefox/addon/pt-plugin-plus-myai/
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/32786903/5a36fd81-cc67-4da5-8a75-a360fddd5499)

**Comment by Rhilip** [comment]
不是，我们在Firefox 附加组件商店中才用不公开发布的形式，对应的扩展id为 `{e9c422a1-5740-4c0a-a10e-867939119613}`。
升级列表可以见 https://pt-plugins.github.io/PT-Plugin-Plus/update/firefox.json
