### ISSUE TITLE
 <我的数据>为空

### ISSUE THREAD

**Issue by allenmien** [pt-plugins/PT-Plugin-Plus#1868]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.0.ba3d87e
- PT 助手安装方式：（市场安装，或zip包安装）市场安装
- 浏览器名称及版本：macos edge 124.0.2478.105 (正式版本) (arm64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：
站点添加M-TEAM，但是我的数据显示为空。
且M-team搜索不到种子

- 相关截图：
<img width="1004" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/24579929/850f6183-6595-4657-a956-aee3e249284a">
<img width="958" alt="image" src="https://github.com/pt-plugins/PT-Plugin-Plus/assets/24579929/1b2e76ae-4e84-472c-8d67-2487a9353ef1">

- 重现步骤：

**Comment by mitlearn** [comment]
[解决方案](https://t.me/ptpluginplus/190)
更加推荐[解决方案](https://t.me/ptpluginplus/183)
