### ISSUE TITLE
插件中的xp.m-team.io地址无法访问，请更新为kp.m-team.cc

### ISSUE THREAD

**Issue by xinmans** [pt-plugins/PT-Plugin-Plus#1869]
嗯… 无法访问此页面找不到 xp.m-team.io 的 DNS 地址… 现在正在诊断问题。
DNS_PROBE_STARTED

**Comment by mitlearn** [comment]
今日[维护公告](https://t.me/M_Team_Chat/3269956)
请更新pre-release版 添加[教程](https://t.me/ptpluginplus/196)
