### ISSUE TITLE
BHD不能批量下载

### ISSUE THREAD

**Issue by laobanbiefangcu** [pt-plugins/PT-Plugin-Plus#1872]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2657
- PT 助手安装方式：crx安装
- 浏览器名称及版本：360极速浏览器
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：否
- 问题描述：
BHD不能批量下载种子

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
我这试了一下2623OK
还请提供更多信息
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/7042766/c0be82e6-bc0a-4488-957f-fc6e40389532)
