### ISSUE TITLE
m-team不能批量下载种子

### ISSUE THREAD

**Issue by lan771** [pt-plugins/PT-Plugin-Plus#1884]
- PT 助手版本: dev-build-1.6.1.2659-zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：EDGE
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
m-team 批量下载种子的时候报错：获取下载链接失败，未能正确定位到链接

**Comment by lan771** [comment]
单个种子是OK的

**Comment by lan771** [comment]
可以在插件的文件夹里修改MT的配置，路径PT-Plugin-Plus-1.6.1.xxxx\resource\systemConfig.json，修改systemConfig.json中配置的MT域名，按ctrl+R将所有 xp.xxxxx.io 替换成 kp.xxxxx.cc ，
然后文件内搜索这个域名，删除cdn括号里面多余的一个kp.xxxxxx.cc，还需要在PT-Plugin-Plus-1.6.1.2623\resource\sites文件夹底下找到馒头xp开头域名的文件夹，将文件夹名称改成kp.xxxxxx.cc，
然后点进文件夹，将里面config.json文件中的域名也全部替换成kp.xxxxxxx.cc域名 
这个方法也试过 还是不能批量下载

**Comment by lan771** [comment]
目前用的是 dev-build-1.6.1.2659-zip 版本 是需要重新加载一次吗？

**Comment by mitlearn** [comment]
> 目前用的是 dev-build-1.6.1.2659-zip 版本 是需要重新加载一次吗？

zip安装的正确更新方式为

1. 将新zip解压到原插件解压的文件夹内 覆盖
2. 在浏览器插件页找到插件 点击重新加载
3. 更新完成

**Comment by lyj0309** [comment]
+1
获取下载链接失败，未能正确定位到链接

**Comment by WuliYmm** [comment]
> > 可以在插件的文件夹里修改MT的配置，路径PT-Plugin-Plus-1.6.1.xxxx\resource\systemConfig.json，修改systemConfig.json中配置的MT域名，按ctrl+R将所有 xp.xxxxx.io 替换成 kp.xxxxx.cc ， 然后文件内搜索这个域名，删除cdn括号里面多余的一个kp.xxxxxx.cc，还需要在PT-Plugin-Plus-1.6.1.2623\resource\sites文件夹底下找到馒头xp开头域名的文件夹，将文件夹名称改成kp.xxxxxx.cc， 然后点进文件夹，将里面config.json文件中的域名也全部替换成kp.xxxxxxx.cc域名 这个方法也试过 还是不能批量下载
> 
> 请至少更新至最新pre-release版 直接修改配置文件并不会对插件生效 批量下载即使可用 受限于站点API 速度相当缓慢 修复意义并不是很大
> 
> [添加教程](https://t.me/ptpluginplus/198)

参照以上方法，依然显示未登录。
