### ISSUE TITLE
馒头种子列表页边栏报错

### ISSUE THREAD

**Issue by 6019972** [pt-plugins/PT-Plugin-Plus#1887]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2659
- PT 助手安装方式：zip安装
- 浏览器名称及版本：Chrome 124.0.6367.208
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
   馒头在种子列表页面，边栏的 复制链接、下载到服务器、所有种子、点击都会报错、而且我问了其他人也都是同样会报这个错

- 相关截图：
![WX20240523-141728@2x](https://github.com/pt-plugins/PT-Plugin-Plus/assets/46084062/3c849df7-e0eb-4d73-b502-c8f044fd54d2)
![WX20240523-141742@2x](https://github.com/pt-plugins/PT-Plugin-Plus/assets/46084062/ba482c2a-a7a5-442f-b476-3b9bb14cb9dc)
![WX20240523-141758@2x](https://github.com/pt-plugins/PT-Plugin-Plus/assets/46084062/457e195c-ff85-4faf-8502-9fab19b1f97b)

- 重现步骤：

**Comment by IITII** [comment]
更新

**Comment by 6019972** [comment]
更新到那个版本呢？ 我刚才试了下最新版的actions-2664也还是报错呀

**Comment by 6019972** [comment]
> 更新

更新到那个版本呢？ 我刚才试了下最新版的actions-2664也还是报错呀

**Comment by IOTA233** [comment]
一样的问题，v1.6.1.2657 可以单个下载，不可以批量下载

**Comment by IITII** [comment]
https://t.me/PTPPAction/2041 @IOTA233 @6019972

**Comment by 6019972** [comment]
> https://t.me/PTPPAction/2041 @IOTA233 @6019972

我在这个群里、我下的就是群里的actions-v1.6.1.2664的版本、基本是最新的版本了、还是单个下载是可以的，但是批量下载就报错、群里那个版本能解决这个问题吗？

**Comment by IOTA233** [comment]
> [t.me/PTPPAction/2041](https://t.me/PTPPAction/2041) @IOTA233 @6019972

v1.6.1.2668 最新的包也是一样

**Comment by moxuec** [comment]
版本号 v1.6.1.2668一样的问题，侧边栏保存种子报错，插件里面能正常下载
