### ISSUE TITLE
馒头genDlToken报错

### ISSUE THREAD

**Issue by tsymr** [pt-plugins/PT-Plugin-Plus#1889]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [X ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [X] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [X ] 搜素过Issue，确认没有相关问题
- [X ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2664
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件： 是
- 停用其他插件后是否正常工作：否
- 问题描述：
馒头点击下载种子到服务器后报错 ，馒头 genDlToken 接口 "Request method 'GET' is not supported"

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/11868091/e2348ddc-4223-47cb-88cc-a9b16fbb56b7)

- 重现步骤：

**Comment by awillheartwu** [comment]
我也出了这个问题，而且不止PTPP有这个问题，nastool也出现了

**Comment by trim21** [comment]
这个方法应该用post调用的

**Comment by trim21** [comment]
无法复现，现在就是用POST调用的。

**Comment by trim21** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/blob/6f07eb1ae00f19403f77578fd008344597f14b6e/src/service/public.ts#L504-L505

**Comment by awillheartwu** [comment]
> https://github.com/pt-plugins/PT-Plugin-Plus/blob/6f07eb1ae00f19403f77578fd008344597f14b6e/src/service/public.ts#L504-L505
应该是馒头后端的问题,当天晚些时候又正常了
