### ISSUE TITLE
ptpp导致filecrypt.cc无限刷新

### ISSUE THREAD

**Issue by elderren** [pt-plugins/PT-Plugin-Plus#1900]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2671
- PT 助手安装方式：crx
- 浏览器名称及版本：chrome 125.0.6422.142（64 位）on win 10 
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
安装并启用ptpp后，会导致filecrypt.cc的页面无限自动刷新，无法显示验证码，示例链接：
https://filecrypt.co/Container/EACE775260.html
停用ptpp即可正常显示。
已停用所有其他扩展，在chrome与edge上复现成功。通过逐个版本安装测试，确定此问题首次出现在1.6.1.2649，并影响所有后续版本。

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
好像没遇到，我点进去让我点一个不关闭的圆，然后有个download的东西，点那个download之后，ublock就弹阻止了
uBlock Origin 阻止了下列页面加载：

https://track.involvkgfr.com/

**Comment by elderren** [comment]
![屏幕截图 2024-06-07 215446](https://github.com/pt-plugins/PT-Plugin-Plus/assets/145200244/8b8f0e4c-aabe-483b-908e-b0a4fb0a3315)
奇怪，我只要启用ptpp就会卡在这个界面不断自动刷新，停用或者降级到2649以前的版本就可以正常加载出人机验证界面，删掉ptpp重装，清空浏览器缓存，换浏览器，挂不挂梯子，换节点，换其他的电脑，电脑连接手机热点都试了，也还是一样的现象。ptpp是从tg的actions频道下载的。
不知道其他维护者能否复现这个问题，ptpp会影响到非pt的网站还是挺诡异的。

**Comment by ted423** [comment]
cutcaptcha.net 好像是验证的域名，被墙掉了
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/7042766/46c70b4d-7317-44fd-b683-685c49925838)

网络不太好做完验证就进去了
因为他提醒我关ad block
我就把ublock打开了(之前没开)

不知道对方是不是做了个检测到广告过滤就自动刷新的脚本

**Comment by elderren** [comment]
辛苦大佬这么晚了还陪我找问题。ublock开和关我也试了，还是不行。我刚刚远程了一台放在另一个市的电脑，也能复现，怀疑是我脸有问题，就很玄学。

**Comment by ted423** [comment]
我把这个网站的cookies清掉之后确实能再现

**Comment by ted423** [comment]
目前可以确认的是，禁掉这个网站的脚本执行权限之后，他不会自动刷新。

2647的变动主要是这个commit 
https://github.com/pt-plugins/PT-Plugin-Plus/commit/4ce8bb94b790b7ef3dfaf6c35c083831db7a58cf

**Comment by ted423** [comment]
导致刷新的就是这个脚本 https://v2.cutcaptcha.net/captcha/SAs61IAI.js

**Comment by elderren** [comment]
2647是正常的，问题是从2649开始出现，应该是这个commit：
https://github.com/pt-plugins/PT-Plugin-Plus/commit/22ec75348b1b0645eb43cb2da058b05caf2768a8
但是我不懂代码，不知道是哪部分的更新导致了这个问题。

**Comment by Rhilip** [comment]
我不太认为这个是ptpp的问题。一方面，我们不向该网站注入script。另一方面指出来的2649与2647只是改了构造工具，最终构造出来的代码可能因为构造链的替换而不同，但是实现的内容是一致的。

从ted423和我的测试、题主上面的回复来看，也并不具有普遍性。如果题主觉得仍是ptpp的问题，我建议给出更多证据。

**Comment by elderren** [comment]
我也给不出更多证据了，手头能找到的环境都试过了，都能稳定复现。我不懂网络，也无法确定就是ptpp的问题，也有可能是这个网站的问题。没关系，我退回2647就行，感谢各位大佬的辛苦工作。
