### ISSUE TITLE
求适配milkie（米尔基），每次用都要手动挨个添加种子，且不支持数据图

### ISSUE THREAD

**Issue by pmy1325420923** [pt-plugins/PT-Plugin-Plus#1902]
- 站点名称：milkie
- 站点地址：https://milkie.cc/browse
- 站点描述：欧美电影、电子书、游戏、音乐、成人内容

- 资源类型：电影、电子书、游戏、音乐成人内容
- 开放注册：否
- 是否连坐：否
- 站点规则：无

**Comment by tomyangsh** [comment]
见 #1985
