### ISSUE TITLE
求适配bitporn（比特色情）

### ISSUE THREAD

**Issue by pmy1325420923** [pt-plugins/PT-Plugin-Plus#1903]
- 站点名称：bitporn/比特色情
- 站点地址：https://bitporn.eu/index.php
- 站点描述：成人影视

- 资源类型：成人影视，18+影视
- 开放注册：是/否
- 是否连坐：是/否
- 站点规则：一般规则</h2>
不要做任何我们禁止的事情。不要发送垃圾邮件。照顾好您的帐户。非活动帐户将根据以下规则删除：1.具有精英等级或更高级别的帐户，在停车后永远不会删除（在控制面板中）。2. 退伍军人级别或更高级别的帐户将永远不会被删除。3. 如果用户超过 400 天未登录，停放的帐户将被删除。4. 如果用户超过 150 天未登录，则未停放的帐户将被删除。5. 如果用户连续 100 天以上未登录，则上传和下载量均为 0 的帐户将被删除。实施欺诈的用户将被删除。不要冒险！论坛或服务器上的令人不安的行为将触发警告。你只会收到一个警告！再见......！
--

一般规则
列表不要做任何我们禁止的事情。
列表不要发送垃圾邮件。
列表照顾好您的帐户。

非活动帐户将根据以下规则删除：

1.具有精英等级或更高级别的帐户，在停车后永远不会删除（在控制面板中）。
2. 退伍军人级别或更高级别的帐户将永远不会被删除。
3. 如果用户超过 400 天未登录，停放的帐户将被删除。
4. 如果用户超过 150 天未登录，则未停放的帐户将被删除。
5. 如果用户连续 100 天以上未登录，则上传和下载量均为 0 的帐户将被删除。

列表实施欺诈的用户将被删除。不要冒险！
列表论坛或服务器上的令人不安的行为将触发警告。你只会收到一个警告！再见......！
下载规则
！！低利率可能会产生严重后果，包括禁止帐户！

H&R（肇事逃逸规则）
列表 10 个未完成的 H&R 将导致自动封禁！
列表我们每月一次从您的帐户中删除

未完成的 H&R 帖子 降级规则
列表 如果您的下载量大于 50GB 且速率低于 0.1 降级
列表 如果您的下载量大于 100GB 且速率低于 0.2 降级
列表如果您的下载量大于 200GB 且速率低于 0.3 降级
列表 如果您的下载量大于 400GB 且速率低于 0.4 降级
列表 如果您的下载量大于 800GB 且速率低于 0.5 降级

如果您被降级为农民，您有 30 天的时间来提高您的费率。如果您未在 30 天内修复它
，您将被自动封禁。

TORRENT 促销规则
列表随机促销（上传时随机促销）：
列表 2% 几率、50% 水蛭
列表 3% 几率、免费水蛭
列表 2% 几率、2X UP
列表 1% 几率、免费水蛭 + 2X UP
列表 1% 几率，2 倍上升 + 50% 下降
列表 2% 几率，30% 水蛭

大于 20GB 的列表种子会自动免费获得水蛭。
列表广受欢迎的种子将进行推广（由管理员自行决定）。

促销到期
列表促销活动将在 7 天后到期（从上传种子之日起）。
列表在特殊情况下，我们将整个网站设置为免费水蛭。尽可能多地下载。:-)
上传规则
我们要求您遵守规则，如果您有任何不清楚或可以理解的问题，请联系[工作人员](https://bitporn.eu/contactstaff.php)。

总则
列表您必须对上传的文件具有合法权限。
列表确保您的种子已正确加载。如果您至少花费 24 小时或直到其他人完成下载，或者您故意保持较低的上传速度，您将收到警告，并且您的上传权限可能会被撤销。
列表对于您上传的种子，您将获得两倍的上传积分。
列表如果您有一些有趣的东西在某种程度上违反了这些规则，请[将其发送给工作人员](https://bitporn.eu/contactstaff.php)并附上详细说明，我们可能会破例。

特权
列表每个人都可以上传。

允许的内容
列表仅限成人内容：
列表 高清 （HD） 视频
列表 高清 （4K） 视频
列表 全高清媒体，例如蓝光光盘、HD DVD 光盘等。 或 remux
列表 录制的 HDTV 流 其他高清视频，
列表如HD DV
列表 标清 （SD） 视频
列表 高清媒体的标清编码（最低 480p）
列表 DVDR/DVDISO
列表 DVDRip、CNDVDRip

不允许的内容
列表总内容
列表小于 100 MB 升级/部分升级的标清母带/制作内容
列表 标清分辨率但质量低的视频，例如 CAM、TC、TS、SCR、DVDSCR、R5、R5。Line、HalfCD 等
列表 RealVideo 编码视频（通常是 RMVB 或 RM）、flv 文件
列表 自定义示例（必须包含在“主种子”中）
列表 禁忌或敏感内容（政治或宗教敏感话题）
列表 损坏的文件，即在读取或播放时列表损坏的文件
垃圾邮件文件，例如病毒、特洛伊木马、网站链接、广告等，或不相关的文件。

种子信息
所有种子都应具有：
列表 标签：考虑到视频的内容，用逗号分隔。
列表说明：必须包含一张小封面图片和缩略图。

**Comment by HalfOfSunshine** [comment]
建议你先把你身份证电话坐标留下。方便警察上门的时候开发者供述

**Comment by pmy1325420923** [comment]
> 建议你先把你身份证电话坐标留下。方便警察上门的时候开发者供述

拉面为啥可以
