### ISSUE TITLE
限制同时刷新站点数量

### ISSUE THREAD

**Issue by UrsaBear** [pt-plugins/PT-Plugin-Plus#1904]
## 您的功能请求是否与问题有关？ 请描述一下。

定时任务或者手动刷新站点数据时，如果站点数量过多会导致浏览器卡顿，并偶尔出现部分站点数据读取不完全或刷新失败。
个人目前75个站点的情况下，几乎每次全量刷新都至少会出现三五个站点的数据不准确或者干脆失败，但是马上手动重试又能正常获取。

## 描述你想要的解决方案

可以考虑增加设置项，允许用户定义刷新线程数限制，分批刷新站点数据，避免卡顿同时提高成功率。
例如设置线程数10，则有100个站点的情况下每十个站点为一组分十组顺序执行刷新任务。

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/535
