### ISSUE TITLE
备份的历史记录里面出现了两个m-team，导致无法正确导入m-team的历史记录

### ISSUE THREAD

**Issue by jiang925** [pt-plugins/PT-Plugin-Plus#1907]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准 （注：安装的时候都是最新的。我现在要更新。发现了问题。）
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 2664 （注：安装的时候是最新的。用的时候没有发现问题。现在要更新，发现了问题。）
- PT 助手安装方式：zip 
- 浏览器名称及版本：Edge 版本 125.0.2535.92 (正式版本) (arm64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
插件内部的userHistoryData里面出现了两个m-team的key。导出以后如下：
```
{
  "xp.m-team.cc": { 
    // 正确的历史记录并一直在更新
  },
  "xp.m-team.io": {
    // 两条非常老的历史记录（一个月以前）
  },
}
```
这个数据在导入的时候，错误的数据会被导入，而正确的数据就消失了。这导致备份功能失效。不能升级PTPP版本。

数据可以手动修复。
1. 在插件管理页，打开PTPP的背景页。
2. 在控制台里，给getUserHistoryData函数设置断点。
3. 在插件里打开站点数据页面。
4. 这时背景页的断点会trigger。在控制台里面去掉多余的key。大概是这样的`delete this.service.items.userDatas["xp.m-team.io"]`

- 相关截图：

- 重现步骤：
我不记得一个月前是具体怎么操作的了。大体上是添加了m-team，但是过了两天m-team去掉了一个域名导致ptpp不能访问m-team。然后我就在m-team配置里面的CDN列表里去掉了那个失效的域名。

**Comment by IITII** [comment]
备份为 zip, 然后恢复

03297bbe698cec4a86d2106a4b2a2bb7bc2457f0 fix(mt): 历史数据丢失问题 #1762 #1785
