### ISSUE TITLE
馒头种子下载页面 点击下载和复制链接无效

### ISSUE THREAD

**Issue by Xhyen** [pt-plugins/PT-Plugin-Plus#1910]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 2668
- PT 助手安装方式：（市场安装，或zip包安装） zip安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
站点添加 并设置了token 尝试在页面下载当页的种子到qbit 提示如下图

并删除站点重新添加 还是无效

插件能获取个人信息数据 说明token是有效 而且能搜索出种子

- 相关截图：
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17582511/5b6f5711-30f7-4085-973c-6c6d88c8a6f9)

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17582511/ac28b1a9-e548-45ac-b09c-9ec0a86378c8)

![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/17582511/c13c853d-f535-4975-9662-f49003358fba)

- 重现步骤：

**Comment by TangKii** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/12776431/7a16e406-84de-454c-8450-55a38ce3f824)
2677版本侧边栏，mt可以使用啊，
复制链接和下载到指定服务器都可以用

**Comment by TangKii** [comment]
> ![image](https://private-user-images.githubusercontent.com/12776431/339590081-7a16e406-84de-454c-8450-55a38ce3f824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjU2NTgsIm5iZiI6MTcxODMyNTM1OCwicGF0aCI6Ii8xMjc3NjQzMS8zMzk1OTAwODEtN2ExNmU0MDYtODRkZS00NTRjLTg0NTAtNTVhMzhjZTNmODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAwMzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNjllM2RjNDhhMGEwODQxN2VjMzhkMThkNTgwZGJmY2Q0MmYzZWNiZmY4MWIyMTczYjE0YTIxNDdhZDAxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o-KugsRgjsupaS90eSaXt56UxlS5Njy6iZkNfv-Bp7M) 2677版本侧边栏，mt可以使用啊， 复制链接和下载到指定服务器都可以用

1.单种页面可以正常使用,如https://xxxxxx/detail/792908
2.种子列表页面无法使用,如https://xxxxxx/browse

**Comment by Xhyen** [comment]
> ![image](https://private-user-images.githubusercontent.com/12776431/339590081-7a16e406-84de-454c-8450-55a38ce3f824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjk3NzMsIm5iZiI6MTcxODMyOTQ3MywicGF0aCI6Ii8xMjc3NjQzMS8zMzk1OTAwODEtN2ExNmU0MDYtODRkZS00NTRjLTg0NTAtNTVhMzhjZTNmODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNTE5MGJlYTcwNjBiNjMyZWNhMTExYWQ3MmFjNDc5MTA2ZDJkMzRlMTgwZTUyNmFmOTc3OTFiMzQwNjgxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BfczYqK4op_87TJZvgjlAYAUn2LmwFHIdjXKSkNq5v8) 2677版本侧边栏，mt可以使用啊， 复制链接和下载到指定服务器都可以用

是不是我那里配置的不对？我点下载就提示这个

**Comment by Xhyen** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12776431/339590081-7a16e406-84de-454c-8450-55a38ce3f824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjU2NTgsIm5iZiI6MTcxODMyNTM1OCwicGF0aCI6Ii8xMjc3NjQzMS8zMzk1OTAwODEtN2ExNmU0MDYtODRkZS00NTRjLTg0NTAtNTVhMzhjZTNmODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAwMzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNjllM2RjNDhhMGEwODQxN2VjMzhkMThkNTgwZGJmY2Q0MmYzZWNiZmY4MWIyMTczYjE0YTIxNDdhZDAxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o-KugsRgjsupaS90eSaXt56UxlS5Njy6iZkNfv-Bp7M) 2677版本侧边栏，mt可以使用啊， 复制链接和下载到指定服务器都可以用
> 
> 1.单种页面可以正常使用,如https://xxxxxx/detail/792908 2.种子列表页面无法使用,如https://xxxxxx/browse

啊对 就是种子列表不能用。我说的就是这个

**Comment by jiuqianyuan** [comment]
貌似不能识别网址中有排序的页面，比如以下第二个网址就不行，会报获取链接失败
https://kp.m-team.cc/browse?cat=427&pageNumber=12
https://kp.m-team.cc/browse?cat=427&pageNumber=12&sort=size%3Aascend

**Comment by taylorSZSS** [comment]
没错，有排序就报错。

**Comment by taylorSZSS** [comment]
2677 ，默认页面可以下载。一点击排序，就无法正常使用

**Comment by lalalamiheart** [comment]
我这里复现，本来想拉一批种子的

**Comment by caco12138** [comment]
一样，现在还是这个问题，排序页面种子拉不下来，用的最新版

**Comment by IITII** [comment]
#1917

**Comment by Xhyen** [comment]
> #1917

是不是要等release更新？

**Comment by IITII** [comment]
嗯, 也可以直接下载 action 版本 https://t.me/PTPPAction/2162

**Comment by ptninja** [comment]
2688 可以正常解析种子，但是因为代码里有限流设置，要花15分钟解析一页100个种子，并且馒头种子似乎有时效。等全部解析完，种子下载链接已经失效了。所以结果还是无法批量下载。

**Comment by lalalamiheart** [comment]
> 2688 可以正常解析种子，但是因为代码里有限流设置，要花15分钟解析一页100个种子，并且馒头种子似乎有时效。等全部解析完，种子下载链接已经失效了。所以结果还是无法批量下载。

我这里复现

**Comment by caco12138** [comment]
> 2688 可以正常解析种子，但是因为代码里有限流设置，要花15分钟解析一页100个种子，并且馒头种子似乎有时效。等全部解析完，种子下载链接已经失效了。所以结果还是无法批量下载。

是的，我遇到了同样的问题，目前没有好的办法批量拉取mt的种子

**Comment by ptninja** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/blob/4d02cc3f6202eab3980fc8a16c0c5d084ade7e84/resource/sites/xp.m-team.cc/torrents.js#L50-L54

土办法，可以把这里的 timeout 改小点，或者 batch 一下每 N 个 timeout。就是不知道会不会有 rate limit ban 号风险。

这里的注释似乎也不行，馒头没找到“自行修改站点每页种子数量”的选项。
