### ISSUE TITLE
Firefox 127 使用下載該頁面所有種子後 下載下來的種子全是download.php檔案 

### ISSUE THREAD

**Issue by ChenBill900703** [pt-plugins/PT-Plugin-Plus#1911]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2677
- PT 助手安装方式：Firefox xpi安裝
- 浏览器名称及版本：Firefox 127
- 浏览器是否安装了其他插件：ublock origin
- 停用其他插件后是否正常工作：否
- 问题描述：

下載該頁面所有種子後 下載失敗

- 相关截图：

![螢幕擷取畫面 2024-06-17 171759](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/7de7811f-bbed-48a6-9202-7cd79c65509c)
![螢幕擷取畫面 2024-06-17 171819](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/a3636dbd-2923-4439-925d-4213d5962a25)
![螢幕擷取畫面 2024-06-17 171842](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/a0176d99-6008-40c3-9075-16e3eedb9dc3)
![螢幕擷取畫面 2024-06-17 172015](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/6ee31542-96b7-4d60-891d-64af07aa9013)

- 重现步骤：

![螢幕擷取畫面 2024-06-17 172015](https://github.com/pt-plugins/PT-Plugin-Plus/assets/55220464/9e0a26d8-0474-4a83-bc7f-f24708e6b691)

不知為何下載下來是download.php檔案 不是Torrent檔案

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/250
