### ISSUE TITLE
馒头更新api调用url

### ISSUE THREAD

**Issue by jiang925** [pt-plugins/PT-Plugin-Plus#1913]
## 描述你想要的解决方案

```
有使用到api調用功能的用戶或工具
原先
域名/api 的域名調用方式即將停用
請統一切換為
api.域名 (其他可用域名請自行查看接口)
例如
api.m-team.cc
api.m-team.io

舊方式調用將於七月一號正式停用
```

**Comment by ted423** [comment]
改了一下，似乎不行
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/7042766/a39d7465-967e-4171-b0e8-6f53d594bd38)
要等大佬了

**Comment by ted423** [comment]
@ted423 试了下可以直接改网站url,但是ptpp里点就会打开api这个域名
