### ISSUE TITLE
建议发送到qbittorrent支持添加category

### ISSUE THREAD

**Issue by jibwf** [pt-plugins/PT-Plugin-Plus#1918]
## 您的功能请求是否与问题有关？ 请描述一下。

目前发送到qbittorent目前只支持设置下载路径

## 描述你想要的解决方案

qbittorrent支持下载分类，不同分类会自动保存到不同的目录。但是PT助手下载时，不支持选择下载分类

看过https://github.com/pt-plugins/PT-Plugin-Plus/issues/821
2024年了，不知道有没有接口可以实现

**Comment by mitlearn** [comment]
已支持https://github.com/pt-plugins/PT-Plugin-Plus/pull/1588 请搜索issue无相关内容再提
教程 https://t.me/ptpluginplus/199
