### ISSUE TITLE
m-team七月一日之后刷新数据一直失败，提示403

### ISSUE THREAD

**Issue by Arnold133** [pt-plugins/PT-Plugin-Plus#1930]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2677
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：谷歌浏览器126.0.6478.127（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by mitlearn** [comment]
好歹你也是Github用户 不能先看看更新？
https://github.com/pt-plugins/PT-Plugin-Plus/releases
