### ISSUE TITLE
openCD（皇后）无法批量下载种子

### ISSUE THREAD

**Issue by z594lh** [pt-plugins/PT-Plugin-Plus#1939]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:[v1.6.1.2693](https://github.com/pt-plugins/PT-Plugin-Plus/releases/tag/v1.6.1.2693)
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：没有
- 停用其他插件后是否正常工作：
- 问题描述：皇后无法批量下载种子。下载链接为https://open.cd/plugin_download.php?id=159514&hit=1&https=1，实际上路径是错误的，https://open.cd/download.php?id=159514&hit=1&https=1这个才是正确的下载路径，plugin_download要去掉plugin_

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
没有复现，opencd的内容全是按np模板里处理的，没发现有plugin_这个

**Comment by z594lh** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/44962379/8d1448ea-98ee-4df4-8a1f-83f90ad002fe)
如图，我批量下载，在下载历史里面，全是失败，然后下载链接是https://open.cd/plugin_download.php?id=147105&hit=1&https=1，我去掉plugin_能正常下载种子下来

> 没有复现，opencd的内容全是按np模板里处理的，没发现有plugin_这个

**Comment by ted423** [comment]
你是什么时候添加的opencd?有没有改啥自定义操作？

**Comment by ted423** [comment]
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/7042766/35dae7f9-5b51-41d2-b401-5960f3e69155)
或者操作页面是哪

**Comment by ted423** [comment]
我刚试，是可以的
