### ISSUE TITLE
Edge BETA 版本里扩展商店里还是 2022 年更新的

### ISSUE THREAD

**Issue by Orange-Summer** [pt-plugins/PT-Plugin-Plus#1940]
Edge BETA 版本扩展商店里还是 2022 年更新的，是要用 DEV 版本吗？还是现在扩展商店都不行了只能 crx 和 zip？

**Comment by ted423** [comment]
不要在issue区问问题
https://github.com/pt-plugins/PT-Plugin-Plus/wiki/install-from-crx

**Comment by Orange-Summer** [comment]
那扩展商店不能安装建议把 wiki 里的相关内容删掉，不然容易误导
