### ISSUE TITLE
关于无法进一步编辑站点的反馈

### ISSUE THREAD

**Issue by fqh1995** [pt-plugins/PT-Plugin-Plus#1941]
- PT 助手版本:v1.6.1.2693 
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 浏览器 本版本 126.0.6478.127（正式版本
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：
- 问题描述：关于无法进一步编辑站点的反馈

- 相关截图：
![反馈](https://github.com/user-attachments/assets/fa2b74e0-3ebd-4bb6-a295-eb5364ce80fd)

点击编辑站点信息没有反应

- 重现步骤：

**Comment by fqh1995** [comment]
其次分组的信息怎么编辑？没找到入口，在wiki说明中查找也没有信息

**Comment by ted423** [comment]
没再现，试试crx?
我在怀疑你添加了什么把配置搞炸了

**Comment by fqh1995** [comment]
不知道啊，我就用了个白大插件。然后我用谷歌浏览器重新安装一下，还是不能用

**Comment by ted423** [comment]
@fqh1995 我倾向于这是受到影响了

**Comment by fqh1995** [comment]
解决了，用旧版备份的数据恢复，仅恢复站点收藏，可以编辑站点信息。虽然没找到具体bug
