### ISSUE TITLE
新站点请求 bitporn.eu

### ISSUE THREAD

**Issue by b5965** [pt-plugins/PT-Plugin-Plus#1943]
- 站点名称：https://bitporn.eu/
- 站点地址：https://bitporn.eu/
- 站点描述：9kg

- 资源类型：
- 开放注册：是
- 是否连坐：否
- 站点规则：

**Comment by ted423** [comment]
看了眼，暂不支持刚开不久的站点提请求，除非有人主动适配

**Comment by ted423** [comment]
弄错了，看起来这个站开的还是比较早的
