### ISSUE TITLE
新站点请求 pt.cdfile.org

### ISSUE THREAD

**Issue by b5965** [pt-plugins/PT-Plugin-Plus#1944]
- 站点名称：https://pt.cdfile.org/
- 站点地址：https://pt.cdfile.org/
- 站点描述：原盘

- 资源类型：
- 开放注册：是
- 是否连坐：否
- 站点规则：

**Comment by ted423** [comment]
看了眼，暂不支持刚开不久的站点提请求，除非有人主动适配
