### ISSUE TITLE
M-Team适配问题

### ISSUE THREAD

**Issue by Small-SaltedFish** [pt-plugins/PT-Plugin-Plus#1950]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ ] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2710
- PT 助手安装方式：（市场安装，或zip包安装）CRX
- 浏览器名称及版本：Chrome126.0.6478.182
- 浏览器是否安装了其他插件：Yes
- 停用其他插件后是否正常工作：No
- 问题描述：
馒头自架构升级更新后功能均瘫痪 具体是 数据刷新 种子搜索 已瘫痪很长时间 望开发者有空能给予修复

- 相关截图：
![image](https://github.com/user-attachments/assets/f33561d1-9909-48f7-a018-343bd1188ab5)

- 重现步骤：

**Comment by ted423** [comment]
这个修了好久好久了，你确定你的版本号不是随便写的不

**Comment by Small-SaltedFish** [comment]
![image](https://github.com/user-attachments/assets/22e84110-86ad-48be-8f42-0d399ae5eb37)
![image](https://github.com/user-attachments/assets/c5d5f29f-1532-4a23-909b-45d4b36401b4)

**Comment by mitlearn** [comment]
请阅读[教程](https://t.me/ptpluginplus/198)

**Comment by ted423** [comment]
配置了token没有呢

**Comment by jiang925** [comment]
馒头最近变化挺多的。得一个一个都修改好。
1. 新架构，更新就行。
2. 去掉了一个域名，把新域名放到CDN列表顶端。
3. 加了api专用域名，添加到api CDN。这个在版本2693以后才有。（好像是
具体域名可以去一个非公开的地方找。你是有馒头的，也可以看站内公告和系统消息。
