### ISSUE TITLE
BTschool用户信息获取发生错误

### ISSUE THREAD

**Issue by Zeaglefly** [pt-plugins/PT-Plugin-Plus#1957]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2716
- PT 助手安装方式：crx安装（市场安装，或zip包安装）
- 浏览器名称及版本：Microsoft Edge 版本 127.0.2651.74 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：BTschool用户信息获取发生错误

- 相关截图：
![微信截图_20240730085114](https://github.com/user-attachments/assets/802c398b-808b-4b9d-bf51-7b2b7e746192)

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1863
