### ISSUE TITLE
生成分享图片文字错位

### ISSUE THREAD

**Issue by picpo** [pt-plugins/PT-Plugin-Plus#1959]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x ] 搜素过Issue，确认没有相关问题
- [ x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2710 
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Firefox 128.0.3
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
插件内数据显示正常，但是导出后生成的图片错位

- 相关截图：
![图片](https://github.com/user-attachments/assets/d725dfa5-f25a-42bb-a124-53dd2a7990b6)
![图片](https://github.com/user-attachments/assets/604f764c-c02f-4b08-a8d5-65417ff75f4c)

- 重现步骤：

**Comment by fzlins** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1275
