### ISSUE TITLE
BTSCHOOL获取部分信息的临时解决方案

### ISSUE THREAD

**Issue by zty8023ys** [pt-plugins/PT-Plugin-Plus#1960]
## 您的功能请求是否与问题有关？ 请描述一下。

BTSCHOOL主页因为存在cf盾需要验证导致无法获取基础信息

## 描述你想要的解决方案

用种子搜索页面代替主页
例如发现获取首页种子的url没有套盾 https://****/torrents.php?search=&notnewword=1 
我在getInfos里判断了一下是btschool就把请求换成上边的这个, 但是因为解析规则有缺陷, 还是不能正常运作
希望制作组来加一下这个的解决方案

**Comment by zty8023ys** [comment]
> 网站的问题，没必要。换连接，cf盾就换别的地方了。

请问是因为网站错误的把盾套在主页了吗? 还是说怕污染了种子搜索界面, 网站到时候把种子搜索页面也套上盾?

**Comment by fzlins** [comment]
> > 网站的问题，没必要。换连接，cf盾就换别的地方了。
> 
> 请问是因为网站错误的把盾套在主页了吗? 还是说怕污染了种子搜索界面, 网站到时候把种子搜索页面也套上盾?

不知道啊。站点的问题，只能去问站点

**Comment by zty8023ys** [comment]
> > > 网站的问题，没必要。换连接，cf盾就换别的地方了。
> > 
> > 
> > 请问是因为网站错误的把盾套在主页了吗? 还是说怕污染了种子搜索界面, 网站到时候把种子搜索页面也套上盾?
> 
> 不知道啊。站点的问题，只能去问站点

明白了, 这个配置是各个站点自己维护自己的对吧
