### ISSUE TITLE
3个站点无法获得有效数据

### ISSUE THREAD

**Issue by wingswing1** [pt-plugins/PT-Plugin-Plus#1962]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2717
- PT 助手安装方式：（市场安装，或zip包安装）crx
- 浏览器名称及版本：360极速 22.3.2050.64
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
5个站点3个站点无法获得有效数据:
分别为:
btschool
fsm
m-team
换成edge浏览器一样的问题

- 相关截图：
![屏幕截图 2024-08-05 002558](https://github.com/user-attachments/assets/c3b50a8b-cfaf-4fd1-bfac-4a998db3d9c5)

- 重现步骤：

**Comment by mitlearn** [comment]
提起issue请先搜索
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1809#issuecomment-2087903026
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1863

**Comment by wingswing1** [comment]
> 提起issue请先搜索 [#1809 (comment)](https://github.com/pt-plugins/PT-Plugin-Plus/issues/1809#issuecomment-2087903026) #1863

感谢...已关闭
