### ISSUE TITLE
btschool和fsm刷新数据始终提示发生错误，但站点可以正常打开

### ISSUE THREAD

**Issue by okatu-loli** [pt-plugins/PT-Plugin-Plus#1964]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2717
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome  127.0.6533.89（正式版本） （64 位）
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：无
- 问题描述：
btschool和fsm刷新数据始终提示发生错误，但站点可以正常打开

- 相关截图：
![image](https://github.com/user-attachments/assets/7bd0010c-75cd-4017-9371-05242742e3fc)
![image](https://github.com/user-attachments/assets/ccd31204-b36a-44c1-b3bf-fdb1bee7ba26)
![image](https://github.com/user-attachments/assets/14a9b27a-2a5e-4cf0-983f-4f1e76c2a752)

- 重现步骤：
点击刷新分组按钮
![image](https://github.com/user-attachments/assets/2af69f1c-3558-46f3-ad0f-3d273e419c60)

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1934

bts也有过issue了
