### ISSUE TITLE
v1.6.1.2552 版本，学校的信息可以正常刷新，之后的版本就不行。似乎与CF盾无关？

### ISSUE THREAD

**Issue by danniel-o** [pt-plugins/PT-Plugin-Plus#1977]
- 经测试，v1.6.1.2552 版本，学校的信息刷了好几次都挺正常，之后的版本就不行，挂梯子也刷不出来。所以是不是可以认为并不是CF盾的问题，而是可能代码改动之后产生了bug？ 不知道有没有大佬能够排查一下～

**Comment by danniel-o** [comment]
今天2723版本，又突然可以刷新了，好奇怪。本来已经连续1个多月都刷新不了了

**Comment by microka** [comment]
同，已经一个月没法刷新数据了。
