### ISSUE TITLE
为什么搜“美食的俘虏”会有莫名奇妙的结果？

### ISSUE THREAD

**Issue by i990049** [pt-plugins/PT-Plugin-Plus#1987]
- PT 助手版本:1.6.1.2723
- PT 助手安装方式：zip包
- 浏览器名称及版本：EDGE 128.0.2739.54 (正式版本) (64 位)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：搜索“美食的俘虏”，电子书站点和纯9kg怎么也会有结果？该不会都是同样的架构所以出问题？
https://abtorrents.me/
https://www.happyfappy.org/
- 相关截图：
![屏幕截图(273)](https://github.com/user-attachments/assets/5a547737-9b51-4d9b-896c-79fb0fee441c)

**Comment by ted423** [comment]
@i990049 因为有些站就是会返回无关结果
