### ISSUE TITLE
KamePT站可以正常登录签到，但是PTPP刷新数据一直显示发生错误

### ISSUE THREAD

**Issue by scottymax** [pt-plugins/PT-Plugin-Plus#1995]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2731
- PT 助手安装方式：crx
- 浏览器名称及版本：chrome 126.0.6478.126
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
KamePT站可以正常登录签到，但是PTPP刷新数据一直显示发生错误

- 相关截图：
![image](https://github.com/user-attachments/assets/e7d513e6-d2d4-4400-b778-d75c6e0d3bff)

- 重现步骤：
刷新站点数据即可看到

**Comment by scottymax** [comment]
添加一个测试结果，用v1.6.1.2723测试kamept刷新没有问题，但是用最新的版本就会有问题。

**Comment by fzlins** [comment]
测试一下最新的版本，看看可以了吗

**Comment by scottymax** [comment]
> 测试一下最新的版本，看看可以了吗

感谢大佬，测试后恢复正常了
