### ISSUE TITLE
可以增加软件支持吗？

### ISSUE THREAD

**Issue by i990049** [pt-plugins/PT-Plugin-Plus#1998]
有个Azureus的辞职员工写的开源社区版软件叫Bigly BT，RSS订阅可以设置最大文件和最小文件数值，在PT里面碰上伪装的PCDN吸血鬼也可以搭配PeerBanHelper屏蔽IP，希望PTPP可以支持，谢谢。

**Comment by tomyangsh** [comment]
本项目注重于PT，你所提及的软件只能用于公共BT，故不会被支持。另根据[此文档](https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui/blob/master/rpc-spec.txt)，它应该是使用了 transmission rpc, 请自行研究。写一个 userscript 添加一键推送按钮大概是一个比较好的方案。

**Comment by i990049** [comment]
> 本项目注重于PT，你所提及的软件只能用于公共BT，故不会被支持。另根据[此文档](https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui/blob/master/rpc-spec.txt)，它应该是使用了 transmission rpc, 请自行研究。写一个 userscript 添加一键推送按钮大概是一个比较好的方案。

Nexusphp本来就支持Azureus，Az在2017年停更之后，辞职员工另外写了个一模一样界面的开源Bigly BT，并非没有PT站点使用，Unit3d和馒头、Hdarea、象岛ptvicomo都支持这个软件，谈不上PT没人用。
PS：PTPP是不是只能备份Nexusphp的cookies不能备份Unit3d的cookies？导出的cookies用到另外一个设备，发现NP站点可用，Unit3d还是没cookies。

**Comment by fzlins** [comment]
不考虑支持，如果你有能力请pr。

**Comment by i990049** [comment]
> 不考虑支持，如果你有能力请pr。

那比较可惜了，blutopia和hdtorrent都支持这个软件，我是比较喜欢里面的RSS文件大小过滤功能，太大太小的文件都不会下载。请问ptpp是不是不能备份unit 3d架构的cookie？试过最新版好像不行。

**Comment by ted423** [comment]
Bigly BT 是java的，预计资源使用率是高的。刷流这块不做讨论。
用户使用占比不高。
cookies这块其实我想取消掉的，cookies不是能备份就可以使用的，相反导致的问题还不少。

**Comment by i990049** [comment]
> Bigly BT 是java的，预计资源使用率是高的。刷流这块不做讨论。 用户使用占比不高。 cookies这块其实我想取消掉的，cookies不是能备份就可以使用的，相反导致的问题还不少。

资源使用高可以设置少一些任务，JAVA做的软件网速稳定性比libtorrent内核的软件好多了，还有一个frostwire也是JAVA做的，照样活了二十几年。utorrent占用资源最低，任务多了还不是照样跟qbtorrent会卡IO。

其实ptpp对nexusphp的cookies导出挺好用的，手机跟电脑备份的档案拿去给另外一台设备也能用，就是问问能不能也支持unit3d，不行就算了。
