### ISSUE TITLE
火狐上PTPP影响了XML样式的载入

### ISSUE THREAD

**Issue by ixff** [pt-plugins/PT-Plugin-Plus#2002]
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2746 
- PT 助手安装方式：托管
- 浏览器名称及版本：火狐 130
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：

  当启用PTPP后，网页为XML内容时，均不能正常渲染document tree，只显示为无格式文本。
  控制台有报错：style sheet could not be loaded. chrome://globaI/content/xml/XMLPrettyPrint.css

- 相关截图：

![firefox_DqGgtBccon](https://github.com/user-attachments/assets/d4964268-8cac-437d-855a-cc8b517d5648)

- 重现步骤：

![firefox_0G88zmAZdu](https://github.com/user-attachments/assets/57f2d12d-3d20-4fce-9ed6-04b71656c0ad)

**Comment by ted423** [comment]
@ixff 数据刷新，推送种子什么的正常？
