### ISSUE TITLE
PTPP 使用 IMDB 编码搜索 ilolicon PT 无效

### ISSUE THREAD

**Issue by bluicezhen** [pt-plugins/PT-Plugin-Plus#2009]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2743
- PT 助手安装方式：（市场安装，或zip包安装）crx
- 浏览器名称及版本：Microsoft Edge 128.0.2739.79 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  使用 IMDB 编码在 PTPP 搜索，ilolicon PT 在全部站点中和无结果站点中均不存在，如果不搜索IMDB 编码，搜索文字则正常存在 ilolicon PT

- 相关截图：

![image](https://github.com/user-attachments/assets/085ceecf-5150-4e86-a6c7-dc14db9b3682)

- 重现步骤：
  1. 添加站点 ilolicon PT
  2. 创建搜索方案，其中包含站点 ilolicon PT
  3. 搜索 IMDB 编码，发现在全部站点中和无结果站点中均不存在 ilolicon PT
  4. 搜索普通字符串，发现存在 ilolicon PT

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/blob/4270897d36c23f4aff09dd68ee3a5279ce50f23a/resource/sites/share.ilolicon.com/config.json#L174

**Comment by bluicezhen** [comment]
fixed by https://github.com/pt-plugins/PT-Plugin-Plus/pull/2013
