### ISSUE TITLE
MonikaDesign中文用户名获取错误

### ISSUE THREAD

**Issue by Lazy-Beee** [pt-plugins/PT-Plugin-Plus#2011]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本：v1.6.1.2743
- PT 助手安装方式：crx
- 浏览器名称及版本：chrome 129.0.6668.59
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：中文用户名在PTPP主界面显示为URL编码

- 相关截图：![image](https://github.com/user-attachments/assets/bb16f451-6cc2-4978-b493-5ea90c2163e0)
![image](https://github.com/user-attachments/assets/7322b6ed-0a7c-4974-9063-f11b2d0d9413)

- 重现步骤：正常自动刷新

**Comment by fzlins** [comment]
新出现的问题，还是一直都有？

**Comment by Lazy-Beee** [comment]
> 新出现的问题，还是一直都有？

可能一直有，我改名了之后发现的

**Comment by Lazy-Beee** [comment]
> 新出现的问题，还是一直都有？

这个改动好像一直没有进到pre-release里面？

**Comment by IITII** [comment]
pre-release 半月一次更新, 求效率可以下载 action 最新的 build. 或者去 [@PTPPAction](https://t.me/PTPPAction)下载
