### ISSUE TITLE
建议禁止弹框的点击遮罩层关闭事件，在编辑时很容易误触，导致编辑内容丢失

### ISSUE THREAD

**Issue by up55** [pt-plugins/PT-Plugin-Plus#2017]
- 
建议禁止弹窗的点击遮罩层关闭事件，在编辑时很容易误触，导致编辑内容丢失。
比如我想用鼠标选中弹窗中的文本，按下左键滑动时滑出了弹窗区域，松开左键弹窗就会关闭，丢失编辑内容，影响体验。

**Comment by ted423** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/issues/345
