### ISSUE TITLE
憨憨.club域名下不显示小助手悬浮框

### ISSUE THREAD

**Issue by nukewarrior** [pt-plugins/PT-Plugin-Plus#2024]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2756 
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 版本 129.0.6668.90（正式版本） (x86_64)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

憨憨使用.club域名时种子列表页、详情页均不显示小助手悬浮框
使用.top域名是正常显示

- 相关截图：

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/da37f5cb-6a7f-47fe-a400-871ad736a3e9">
<img width="1545" alt="image" src="https://github.com/user-attachments/assets/7a1b7044-4c15-4b06-803d-d7079a4aa24b">

- 重现步骤：

**Comment by SHL-COOL** [comment]
在憨憨`站点cdn`里面配置一下`.club`的域名就可以了

**Comment by nukewarrior** [comment]
> 在憨憨`站点cdn`里面配置一下`.club`的域名就可以了

感谢，确实可以
