### ISSUE TITLE
象岛在我的数据里不显示信息

### ISSUE THREAD

**Issue by SHNN16** [pt-plugins/PT-Plugin-Plus#2027]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:v1.6.1.2749
- PT 助手安装方式：crx（市场安装，或zip包安装）
- 浏览器名称及版本：edge 129.0.2792.79 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
刷新分组数据也不显示

- 相关截图：
![image](https://github.com/user-attachments/assets/f278c184-270d-470e-bdc2-e51c0e667f03)

- 重现步骤：

**Comment by MoogleXX** [comment]
同样这个问题。

**Comment by linsongze** [comment]
访问一次  /index.php 然后再更新数据就行了。。亲测可以。。

**Comment by MoogleXX** [comment]
> 访问一次 /index.php 然后再更新数据就行了。。亲测可以。。

果然立马正常。感谢！！
