### ISSUE TITLE
备份：保留备份数量

### ISSUE THREAD

**Issue by ljcbaby** [pt-plugins/PT-Plugin-Plus#2039]
## 您的功能请求是否与问题有关？ 请描述一下。

每日备份可能会有一堆文件。

## 描述你想要的解决方案

设置保留备份数量的上限

## 描述您考虑过的替代方案

写脚本自动删除

**Comment by ted423** [comment]
不需要每日备份

**Comment by ljcbaby** [comment]
设置了更新数据之后自动上传，是每天都会有的。

**Comment by ted423** [comment]
@ljcbaby 看了眼这个功能是为了自动同步弄得一个半成品。如果遇到备份版本太多的问题，要么建议关了不用，要么建议服务端弄个自动清理。基于临时方案做过多的处理不太合适。
我个人不倾向于浏览器扩展对远程文件夹或文件做任何的删除操作。
