### ISSUE TITLE
HaresClub获取的入站时间是错误信息。

### ISSUE THREAD

**Issue by voodooTTC** [pt-plugins/PT-Plugin-Plus#2046]
- PT 助手版本: v1.6.1.2765
- PT 助手安装方式：zip
- 浏览器名称及版本：Google Chrome
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：
![image](https://github.com/user-attachments/assets/c7eb62b8-e1b5-4f7f-870b-8cc59d094583)

- 重现步骤：

**Comment by szlx560223** [comment]
#2092

**Comment by ted423** [comment]
@szlx560223 站点已经说要关了😂

**Comment by ted423** [comment]
算了，先合了😅

**Comment by szlx560223** [comment]
@ted423 想着好歹让他在我的ptpp走的体面一些就还是修了233，不然每次都是错的时间ptpp图导出来p龄不对hhh
