### ISSUE TITLE
数据显示求助

### ISSUE THREAD

**Issue by declandragon** [pt-plugins/PT-Plugin-Plus#2059]
# 说明

某天把几百万魔力都买了上传，导致那天上传特别多，其他时间的上传特别少，导致看不到了

![image](https://github.com/user-attachments/assets/c3c007fc-c3f9-436e-a97b-65cd3753b2e1)

# 求助

可不可以手动改一下数据，把上传平摊到一段时间，比如每天 增加 1T，可能连续改一段时间的数据才会让报表好看一点

**Comment by fzlins** [comment]
不提供修改数据
