### ISSUE TITLE
馒头免费都显示成50%优惠

### ISSUE THREAD

**Issue by nukewarrior** [pt-plugins/PT-Plugin-Plus#2064]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2776
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 版本 131.0.6778.86（正式版本） (x86_64) macOS
- 问题描述：

最近馒头在站免，但是在PTPP里面搜出来，馒头的优惠都显示为50%

- 相关截图：

<img width="965" alt="image" src="https://github.com/user-attachments/assets/234e365b-e2e1-48dd-b113-a944b1589415">

- 重现步骤：

**Comment by ruchid123123** [comment]
我的无法添加馒头账号

**Comment by ted423** [comment]
站免结束，问题解决（
我怀疑可能是馒头的锅，api返回的毕竟
