### ISSUE TITLE
现在对馒头的支持还是不行吗？

### ISSUE THREAD

**Issue by guihu5277** [pt-plugins/PT-Plugin-Plus#2080]
按要求填写的馒头的Token,CDN设置如下，但时好时坏，有的时候可以正常使用，有的时候却又不能连接，显示未知错误。最近一次连接馒头还是12月3日。 这个是什么原因导致的？ 有一直稳定的吗？

CDN设置如下
https://kp.m-team.cc
https://xp.m-team.io
https://xp.m-team.cc
https://ap.m-team.cc

Apicdn
https://api.m-team.io/
https://api.m-team.cc/
https://api2.m-team.cc/
https://mtapi.m-team.cc/

**Comment by ted423** [comment]
不要随便开issue,时好时坏就说明不是扩展问题，基本是网络问题

**Comment by mitlearn** [comment]
![馒头新架构添加至PTPP](https://github.com/user-attachments/assets/6e26061d-128f-4f1b-8665-e346ea3e96cd)

**Comment by cikichen** [comment]
同样的问题，刚开始设置好了可以，过几天就无法获取数据了
![QQ_1735801423833](https://github.com/user-attachments/assets/f8450be2-1247-48a4-b36e-a3423f12ebce)

**Comment by cikichen** [comment]
找到解决办法，cdn删除下面两个，API也删除下面两个，就正常了

**Comment by geseaco** [comment]
按如上流程，已解决。

**Comment by ted423** [comment]
我总结一下，网络问题，cdn网络不通😓
