### ISSUE TITLE
在PTPP助手里面搜索后，MT就被封一小时，显示：帳戶被限制使用1小時: 不正確请求API

### ISSUE THREAD

**Issue by hurui79** [pt-plugins/PT-Plugin-Plus#2087]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [ ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2780
- PT 助手安装方式：ZIP
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：
在PTPP助手里面搜索后，MT就被封一小时，显示：帳戶被限制使用1小時: 不正確请求API

- 相关截图：

- 重现步骤：
昨天搜了一次被封了1小时，我昨天的版本是 v1.6.1.2765，我赶紧升级了一下版本，结果今天搜索还是被封了1小时

**Comment by hurui79** [comment]
一直到方案，一个小时后我试试是否有用

**Comment by ddddchende** [comment]
> 已找到方案，一个小时后我试试是否有用

你好，请问有用嘛

**Comment by nickybaby57** [comment]
> 已找到方案，一个小时后我试试是否有用

什么方案，哪里找的呢？

**Comment by hurui79** [comment]
> > 已找到方案，一个小时后我试试是否有用
> 
> 你好，请问有用嘛

有用，方案就是ptpp里面MT这个站点删了重新添加一下就行

**Comment by hurui79** [comment]
> > 已找到方案，一个小时后我试试是否有用
> 
> 什么方案，哪里找的呢？

有用，方案就是ptpp里面MT这个站点删了重新添加一下就行，贴吧
