### ISSUE TITLE
大佬，右测点下载到，总是会卡1-2秒，是因为设置目录过多的原因吗 

### ISSUE THREAD

**Issue by s3000s** [pt-plugins/PT-Plugin-Plus#2091]
- 大佬，右测点下载到，总是会卡1-2秒，是因为设置目录过多的原因吗  可以解决吗

这个点出来会卡1-2秒才会出现

![微信图片_20241228140329](https://github.com/user-attachments/assets/e7216193-5f81-4edf-a737-e11734ca6a87)

**Comment by IITII** [comment]
mt 需要先解析下载链接
