### ISSUE TITLE
是否可以调整搜索方式

### ISSUE THREAD

**Issue by luckiestone** [pt-plugins/PT-Plugin-Plus#257]
## 您的功能请求是否与问题有关？ 请描述一下。

目前的搜索方式是，在输入关键词搜索获得搜索结果后，如果改变搜索方案，则按照新方案搜索上次的关键词。

## 描述你想要的解决方案

如果搜索关键词变动，调整搜索方案，按照新关键词搜索

## 描述您考虑过的替代方案

每一次改变搜索方案，都以当前关键词输入框的中的词重新搜索。

**Comment by ronggang** [comment]
这个应该属于Bug
