### ISSUE TITLE
[Bug 反馈] 重复一键下载无有效报错信息

### ISSUE THREAD

**Issue by xfl03** [pt-plugins/PT-Plugin-Plus#386]
- PT 助手版本：1.4.6
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome 79
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
在任意站点，一键下载已有的种子出错，且无有效报错信息。
理应输出类似”种子已存在“等报错信息，或在种子已存在时禁用一键下载按钮。

- 相关截图：
![截图](https://i.loli.net/2020/01/04/hbFtEYkGsmQ3Npc.png)

- 重现步骤：
**重现方式1**
说明：针对已下载的种子
在任意站点点击一键下载，出错。
**重现方式2**
说明：针对未下载的种子
在任意站点点击一键下载，再点击一次一键下载，出错。

- 相关日志：
```json
{
	"data": {
		"0": "F",
		"1": "a",
		"2": "i",
		"3": "l",
		"4": "s",
		"5": ".",
		"msg": "",
		"status": ""
	},
	"event": "service.controller.doDownload.error",
	"id": "1ceb189cb749698b4a36aef509253bfc",
	"module": "background",
	"msg": "下载服务器qBittorrent Windows处理[addTorrentFromURL]命令失败！",
	"time": 1578121633590
}
```

~BBCode走错片场了~

**Comment by ted423** [comment]
@xfl03 哪个站或者哪个页面？

**Comment by ted423** [comment]
@ted423 我试的pth正常貌似，未下载指的暂停还是？

**Comment by xfl03** [comment]
@ted423 补充信息
已测试存在问题的站点：TTG、SSD、U2、PTer、NPUBits、BYRBT等NexusPHP站点
使用的操作系统：Windows 10
使用的BT客户端：qBittorrent 4.2.1

**Comment by ted423** [comment]
@xfl03 我试了qb确实这样，不知道是不是因为qb没有返回信息的原因，tr的话会提示种子已存在

**Comment by xfl03** [comment]
了解了，不过作为一键下载的执行者，PT插件应该给予确切的反馈，还行希望可以修复。

**Comment by Rhilip** [comment]
@xfl03 请注意，添加下载动作实际是各bt软件，插件只是把下载链接或种子文件发送给软件。
部分bt软件返回给助手的信息只有成功或失败，不足以完成你所说提示失败原因。

**Comment by xfl03** [comment]
@Rhilip 失败也至少需要一个提示吧，而不是单纯的一个什么都没有的红条……

**Comment by ronggang** [comment]
> @Rhilip 失败也至少需要一个提示吧，而不是单纯的一个什么都没有的红条……

是提示那里没做好，失败时应该提示一个失败。
不过qb发送种子时只有成功和失败的提示，不能直接获取是否重复。并未深入研究QB，不知是否有接口可用。

**Comment by ted423** [comment]
看了下，控制台里看到一个Fails,但是扩展仍多次添加。

看了下qb的API，不知道是不是

Returns:

HTTP Status Code	Scenario
415	Torrent file is not valid
200	All other scenarios

所以理论对于QB，红色就代表失败

**Comment by ted423** [comment]
此时的
```
result: Object
0: "F"
1: "a"
2: "i"
3: "l"
4: "s"
5: "."
msg: ""
status: ""```
