### ISSUE TITLE
1.47无法创建辅种任务

### ISSUE THREAD

**Issue by qwsxmkoi** [pt-plugins/PT-Plugin-Plus#442]
- PT 助手版本:1.47
- PT 助手安装方式：（市场安装，或zip包安装）zip，开发者模式
- 浏览器名称及版本：chrome：79.0.3945.130，macos：10.11.6，mbp 2015年初i5 8g版
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：创建辅种任务的时候，设置完目录后显示剩余操作在辅种任务中查看，然后辅种任务中无任何任务，并且我是从1.45倒入记录进来的，别的都导入了，就辅种任务没有，显示全部倒入成功
1.45正常使用

- 相关截图：
无，就是辅种任务列表空的

- 重现步骤：
1，搜索Ingmar Bergman's Cinema 1946-2003 Criterion Collection 30DISC 1080p Blu-ray AVC LPCM 1.0
2，我有七个结果：ptmsg，天空，岛，家园，yingk，猫站，leagueHD
3，全选，然后点击辅种
4，全部校验成功，然后设置目录，tr－自定义目录
5，显示创建辅种任务中，后续步骤在辅种任务列表查看
6，创建完成，窗口自动关闭，辅种任务列表空

**Comment by ted423** [comment]
看看现象一不一样 https://github.com/ronggang/PT-Plugin-Plus/issues/420

**Comment by qwsxmkoi** [comment]
> 看看现象一不一样 #420

不太一样，我刷新后也没有，并且1.45一直正常运行

**Comment by luckiestone** [comment]
win10 1909, Chrome最新64位，一模一样的问题，1.45是没问题的。我换了edge版也不行

**Comment by leoleoasd** [comment]
版本 v1.5.2.9af1753 一样无法创建，提示已经创建后前往辅种任务界面显示无内容
同时界面有报错：
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at chunk-46722ad3.a1a54f61.js:1:16065
    at Array.forEach (<anonymous>)
    at o.resetItems (chunk-46722ad3.a1a54f61.js:1:16036)
    at chunk-46722ad3.a1a54f61.js:1:16331
```

不知是否有sourcemap可以加载，来看具体报错源在哪儿？感觉是创建成功了但是查看的时候报错？


一下是创建任务时的log，看样子没有报错：
![image](https://user-images.githubusercontent.com/37735580/196140104-02048d14-8fe1-4fd1-8ad6-90390ef1d853.png)

**Comment by luckiestone** [comment]
经过研究，应该是array子项过多造成的bug，没有仔细研究造成这个bug的原因。已经尝试通过覆写解决这个问题。
