### ISSUE TITLE
在我的数据页面，增加站点种子列表的入口

### ISSUE THREAD

**Issue by chenyz1984** [pt-plugins/PT-Plugin-Plus#536]
## 您的功能请求是否与问题有关？ 请描述一下。

无关

## 描述你想要的解决方案

**一、现状**
目前，在“我的数据”标签页，点击站点图标，可直接打开站点首页。但是，如果查看资源列表，还需要再点击站点的种子按钮。
**二、建议**
在“我的数据”页面，增加站点“种子列表”的入口，并且建议入口的URL可以设置成可自定义的。这样，如果想打开各站点的资源列表，可通过助手直接打开。而无需先进首页，再切换种子标签。

**Comment by RtYkk** [comment]
#527 和这个issue有点像的，感觉不会做。

**Comment by ronggang** [comment]
需求应该和 #527 类似，不过不是为了解决盾的问题。
但需求提醒了我，可以为每个站点增加一个入口页面列表，当收藏用，需要时可配置多个页面入口，点击站点名称时可选择前往不同的页面。

**Comment by IITII** [comment]
@ted423
