### ISSUE TITLE
修正HDChina种子列表复制链接的问题

### ISSUE THREAD

**Issue by RtYkk** [pt-plugins/PT-Plugin-Plus#557]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
如我在上一个issue里面提到的 #556 
一般的NP架构的站点种子直链都是这样的
`https://<nexusphp.privatetracker.site>/download.php?id=<torrentid>&passkey=<mypasskey>&https=1`
但是HDChina是这样的
`https://hdchina.org/download.php?hash=<hash>&uid=<uid>&https=1`

导致的问题就是，我在站点设置里面填入了我的passkey。HDChina复制出来的链接是这样的
`https://hdchina.org/download.php?hash=<hash>&passkey=<mypasskey>&https=1`
然后访问会显示：您访问的页面不存在

如何解决这个问题：
1、对HDChina进行单独适配，修改种子链接的模板
2、在HDChina站点设置中，把“密钥”这一栏换一种说法，变成UID。
3、解决问题
- 相关截图：
![Yk0nbYUt1A](https://user-images.githubusercontent.com/45971730/86316295-fdd89a00-bc5e-11ea-94f5-842330592030.png)

- 重现步骤：

**Comment by Rhilip** [comment]
实际上，passkey并不是必填的。在HDC这个站点，不填反而会提取出正常的链接。

**Comment by Rhilip** [comment]
@ronggang 能否考虑把站点设置中的密钥一栏，改成和搜索方案配置一样，采用追加下载链接参数的形式。
随着我们将种子推送改成本地下载之后，原来站点设置中密钥栏显得并无多大作用。
前面 #361 也有用户提出对下载链接提出额外的params请求，但当初的解决方法是使用自定义插件。
此外，就目前链接提取的实现来看 https://github.com/ronggang/PT-Plugin-Plus/blob/c7b238304d6e237fa71290b4a49beb6c8d136b6f/resource/schemas/NexusPHP/torrents.js#L49-L59 
对参数附加也过于固定，这方面开放给用户可能会更好。

![站点设置](https://user-images.githubusercontent.com/13842140/86319261-b950fc80-bc66-11ea-8a84-6c3ab3069cd0.png)
![搜索方案配置](https://user-images.githubusercontent.com/13842140/86319372-f917e400-bc66-11ea-9449-eb36038bba51.png)

**Comment by RtYkk** [comment]
什么都不填是那个只有hash的链接吗？那个并不能在没有cookie的情况下下载…

**Comment by RtYkk** [comment]
自定义插件我研究一下…

**Comment by ted423** [comment]
临时使用，detail就懒得弄了，感觉直接右键复制就行

**Comment by RtYkk** [comment]
瓷佬，伟大！
但我希望插件在日后还是能改一改。这毕竟只是权宜之计

**Comment by Rhilip** [comment]
看了一下，和 #573 的问题还是有些不一样。还是等一下 @ronggang 关于前面意见的想法吧。 https://github.com/ronggang/PT-Plugin-Plus/issues/557#issuecomment-652791092

**Comment by fzlins** [comment]
fix: 946bed92dc16fcdb57c8671c956b34ad060460c7
