### ISSUE TITLE
做种数据丢失问题

### ISSUE THREAD

**Issue by gitnoobbbb** [pt-plugins/PT-Plugin-Plus#596]
- PT 助手版本:1.5.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 版本 85.0.564.51 (官方内部版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：偶尔打开助手会丢失**已读取过**的部分站点的**做种数量**和**做种体积**数据

**Comment by RtYkk** [comment]
Proof needed.

**Comment by gitnoobbbb** [comment]
> Proof needed.

[9:08刷新数据后的截图](https://i.postimg.cc/BbQTbgBB/LNN-BET-5-H8-AO5-ALB-LL.png).
关闭ptpp和浏览器,一段时间后再次打开插件(并未重新刷新数据):
[站点A截图](https://i.postimg.cc/2yc4ZZHR/QQ-20200919102844.png),所有数据都消失;
[站点B截图](https://i.postimg.cc/9XJPS6c8/QQ-20200919102859.png),做种数和做种体积数据消失.
以上...

**Comment by ted423** [comment]
@gitnoobbbb 有试过别的浏览器不

**Comment by gitnoobbbb** [comment]
@ted423 
Google Chrome 版本 85.0.4183.102（正式版本） （64 位)
1.5.0 crx安装,同样的问题.

**Comment by ted423** [comment]
突然想起来我应该也有遇到过，不过我目前配置了自动刷新，也没长期关注
