### ISSUE TITLE
关于备份到google

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#614]
- PT 助手版本:1.5.0自编译
- PT 助手安装方式：crx
- 浏览器名称及版本：cent browser
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
自编译得crx支持备份到google和从google恢复(不过卸掉扩展会导致数据被清掉)
主要是方便多端同步数据

希望官方版本支持

必须重开浏览器或重开扩展才显示数据

- 相关截图：
![1](https://user-images.githubusercontent.com/7042766/95332003-63cb6200-08dd-11eb-866b-2eebab51443b.gif)

- 重现步骤：

**Comment by ronggang** [comment]
cent 的 crx 可以多设备同步吗？

**Comment by ted423** [comment]
@ronggang 会同步打开状态，但不会同步到crx本身我记得。

**Comment by ted423** [comment]
才想起来

**Comment by ted423** [comment]
试了下，会报错(
我猜可能是因为在商店里被ban了导致的。
或者考虑彻底移除这个功能？
目前用的官方的chrome,目前不准备自己打包，原来是自己打包的，不是一个扩展id
