### ISSUE TITLE
发送到群晖DownloadStation的种子会被统一命名为"file"

### ISSUE THREAD

**Issue by tainewoo** [pt-plugins/PT-Plugin-Plus#618]
- PT 助手版本:  PT-Plugin-Plus v1.5.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 86.0.622.38 
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
从站点种子页面单独选择某一个种子,发送到群晖DownloadStation并选择一个目录,添加任务成功.
后续到DownloadStation查看,任务正常执行,不足的地方是,任务常规信息页中的"网址"属性,如果是通过种子文件添加的,正常是该种子文件的文件名.一般从各个PT站点下载的多数是[站点名].资源名.torrent.
DownloadStation任务管理过滤比较不方便,这个时候可以通过这个信息比较简单判断是哪个站点的任务.
但是通过PT助手这样添加的种子,网址属性都是"file", 会有一些不便.

不确定批量添加或者其他添加方式结果如何.

- 相关截图：
![torrentfilename](https://user-images.githubusercontent.com/13391232/95938763-23a03e00-0e0d-11eb-9dfa-d443ab1e1629.png)

- 重现步骤：
从站点种子页面单独选择某一个种子,发送到群晖DownloadStation并选择一个目录,添加任务成功.
后续到DownloadStation查看

**Comment by Rhilip** [comment]
这块目前确实是写死的，等ronggang他看吧。我没DS的测试环境。

https://github.com/ronggang/PT-Plugin-Plus/blob/7d0b92828eddaed2ff4387ae09c8942a45321548/resource/clients/synologyDownloadStation/init.js#L146

**Comment by tainewoo** [comment]
请大佬别忘了这个~

**Comment by walker365** [comment]
rutorrent也有相同的问题，都是js文件里面写死了文件名，在rutorrent的种子文件夹里就出现了file1，2，3，4排序的情况= =

**Comment by sdjnmxd** [comment]
关联PR：https://github.com/pt-plugins/PT-Plugin-Plus/pull/1341
三年之期已到

**Comment by ted423** [comment]
一般来说在pr里带上issue其实就好了
