### ISSUE TITLE
希望能增加自动同步功能

### ISSUE THREAD

**Issue by willie91** [pt-plugins/PT-Plugin-Plus#628]
## 您的功能请求是否与问题有关？ 请描述一下。

主要是方便有几台电脑的人

## 描述你想要的解决方案

1. 检测到配置变化自动同步到webdav或者其他
2. 保留备份3份就够了，我看现在的备份都是每次备份都留下来了，其实很多时候备份都是备份cookie方便另外一台电脑不用再登陆一次.

**Comment by ted423** [comment]
或许可以考虑tampermonkey的模式
![image](https://user-images.githubusercontent.com/7042766/97851828-db4fae00-1d30-11eb-84a2-f2c5054f2e0e.png)

**Comment by willie91** [comment]
> 或许可以考虑tampermonkey的模式
> ![图片](https://user-images.githubusercontent.com/7042766/97851828-db4fae00-1d30-11eb-84a2-f2c5054f2e0e.png)

没看明白，pt plugin跟油猴有啥关系啊？

**Comment by tainewoo** [comment]
应该是自动同步到配置的某个云端空间?然后其他设备自动从云端空间同步? 

补充: 建议支持备份到google之外的其他空间, 毕竟这个在国内不太好用.

**Comment by RtYkk** [comment]
@ted423 tempermonkey就是把本地的js传个压缩包到GD .etc吧，ptpp有没有类似于这种配置可以作为文件导出的？不过为什么只支持WebDav呢？

@willie91 指采用相同的同步模式吧…

**Comment by Rhilip** [comment]
> 或许可以考虑tampermonkey的模式
> ![image](https://user-images.githubusercontent.com/7042766/97851828-db4fae00-1d30-11eb-84a2-f2c5054f2e0e.png)

稍微有些困难，而且目前插件的配置较为分散。此外，自动同步还会带来**配置冲突**等问题，可能也不是很好的方式。
所以，目前暂无精力增加该功能以及自动同步功能，以及另一方面我的意见是将目前v1给EOF，不太可能添加新的功能。

---------------------

从Tampermonkey的几种方式来看：

**浏览器同步** 这块不太好说，目前使用的都是 `chrome.storage.local` 的方法形式调用，部分配置分散在插件背景页的localstorage中，注定无法使用浏览器自带配置同步功能，此外 `chrome.storage.sync` 方式仅在“备份到Google”和“从Google中恢复”两个按钮中用到，且受到Google限制，能同步的空间大小有限。
**Google Drive的同步** 类型需要申请client id和client secert，@ronggang 之前表示一直没申请下来。
**OneDrive** 同样走Graph API的话，一样需要client id和client secert两个，就我用Rclone的经验来看，申请应该是比较容易的，但是我这边不好越俎代庖， ronggang 他之前有表示过申请，但最终申请情况我不太清楚。
Yandex.Disk 和 Dropbox 没用过，不太清楚。国内应该用上的也不多。

**Comment by ted423** [comment]
@Rhilip dropbox我在用，farbox(bitcron)和tampermonkey有依赖这个

**Comment by ted423** [comment]
> 应该是自动同步到配置的某个云端空间?然后其他设备自动从云端空间同步?
> 
> 补充: 建议支持备份到google之外的其他空间, 毕竟这个在国内不太好用.

https://blog.farbox.com/post/stop-them
这个或许可以作为不接入国内厂商的考虑原因



> > 或许可以考虑tampermonkey的模式
> > ![image](https://user-images.githubusercontent.com/7042766/97851828-db4fae00-1d30-11eb-84a2-f2c5054f2e0e.png)
> 
> 稍微有些困难，而且目前插件的配置较为分散。此外，自动同步还会带来**配置冲突**等问题，可能也不是很好的方式。
> 所以，目前暂无精力增加该功能以及自动同步功能，以及另一方面我的意见是将目前v1给EOF，不太可能添加新的功能。
> 
> 从Tampermonkey的几种方式来看：
> 
> **浏览器同步** 这块不太好说，目前使用的都是 `chrome.storage.local` 的方法形式调用，部分配置分散在插件背景页的localstorage中，注定无法使用浏览器自带配置同步功能，此外 `chrome.storage.sync` 方式仅在“备份到Google”和“从Google中恢复”两个按钮中用到，且受到Google限制，能同步的空间大小有限。
> **Google Drive的同步** 类型需要申请client id和client secert，@ronggang 之前表示一直没申请下来。
> **OneDrive** 同样走Graph API的话，一样需要client id和client secert两个，就我用Rclone的经验来看，申请应该是比较容易的，但是我这边不好越俎代庖， ronggang 他之前有表示过申请，但最终申请情况我不太清楚。
> Yandex.Disk 和 Dropbox 没用过，不太清楚。国内应该用上的也不多。
只是作为可行性的考虑，webDAV的同步是否可以做呢

**Comment by foxconndmd** [comment]
支持添加自动备份
