### ISSUE TITLE
希望增加“新增下载目录定义”对站点的多选功能

### ISSUE THREAD

**Issue by Charon4013** [pt-plugins/PT-Plugin-Plus#701]
## 您的功能请求是否与问题有关？ 请描述一下。
下载目录设置的新增里面希望能加一个多选的功能，目前只有单选和全选。
某几个特色站点的资源想要下载到同一个文件夹，暂时只能一个个设置。
谢谢

**Comment by fgott** [comment]
目前在配置新增瞎子目录定义时出现bug
不选择站点是（即默认站点），在新增第二个下载目录时会覆盖原先下载目录。变成唯一值。

下载服务器 qb  默认所有站点
新增第一个下载路径/volume2/下载区/Movie/ 正常新增
新增第二个下载路径/volume2/下载区/Music/  将第一个覆盖，只显示最后新增下载路径。

希望修复。

**Comment by IITII** [comment]
@Charon4013 建议使用下载器的分类功能，或者手动设置一遍
@fgott 请提供复现步骤和截图，从你描述中感觉是用错了。
