### ISSUE TITLE
建议发送到下载器(qb)支持添加标签 分类

### ISSUE THREAD

**Issue by fang232629** [pt-plugins/PT-Plugin-Plus#77]
感谢提供PT助手插件，希望添加“添加标签”功能，目前是默认无标签。谢谢

===============================================
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 问题描述：
- 相关截图：

**Comment by ronggang** [comment]
@fang232629 不好意思，我没明白你想要表达什么。

**Comment by fang232629** [comment]
就是这个分类的功能，这样方便管理种子

![2](https://user-images.githubusercontent.com/48897119/54893152-72b31500-4eef-11e9-84bd-4a1ee1e7c174.jpg)
![1](https://user-images.githubusercontent.com/48897119/54893153-734bab80-4eef-11e9-90f9-0530f7a2789b.jpg)

**Comment by ronggang** [comment]
@fang232629 这个不是每个客户端都支持，所以近期应该不会考虑增加。后期看情况而定。

**Comment by fang232629** [comment]
好的，谢谢，辛苦了

**Comment by Rhilip** [comment]
移入PTPP v2中
