### ISSUE TITLE
[功能建议]建议支持pronbay

### ISSUE THREAD

**Issue by weigeloveu** [pt-plugins/PT-Plugin-Plus#82]
两大porn站的框架都不支持。
https://pornbay.org的gazelle只能看看，各种功能都不支持

**Comment by ronggang** [comment]
@weigeloveu 暂时无能为力，有号的同学路过帮忙一下。

**Comment by CocoShun** [comment]
希望啥时候能支持，刚想发申请，突然发现已经这帖子已经发过了。

**Comment by cwu137** [comment]
直接add - custom用 GazelleJSONAPI 可直接适配

**Comment by tomyangsh** [comment]
见 #1982
