### ISSUE TITLE
视力障碍人士请求背景深色模式

### ISSUE THREAD

**Issue by wtaill** [pt-plugins/PT-Plugin-Plus#928]
## 您的功能请求是否与问题有关？ 请描述一下。

白色或者亮色背景给我及其他视力障碍人士带来不好的体验，麻烦作者能在下个版本中给予一个背景浅色or深色的开关，谢谢！

**Comment by Rhilip** [comment]
next分支有做处理，目前master和dev channel不会考虑了。

**Comment by Rhilip** [comment]
顺带给几个目前next分支的开发进展图吧

![image](https://user-images.githubusercontent.com/13842140/143258381-49d7e08d-81dc-4440-ad8e-f07cf1e31676.png)
![image](https://user-images.githubusercontent.com/13842140/143258414-ff8c2819-e514-483f-877b-b03abeda955a.png)
