### ISSUE TITLE
下载服务器暂时离线

### ISSUE THREAD

**Issue by ted423** [pt-plugins/PT-Plugin-Plus#974]
## 您的功能请求是否与问题有关？ 请描述一下。

有些下载器可能有段时间不会用到，比如带着笔记本出门一段时间，
但下载服务器多的话又很乱，删的话，后面需要还要重新添加回来

## 描述你想要的解决方案

所以想有个临时关闭不显示的选项

**Comment by zhufeng** [comment]
对，挺好的建议

**Comment by cocoer1** [comment]
服务器怎么添加

**Comment by IITII** [comment]
@ted423 已支持
